/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c -w -ferror-limit=3 -pthread --coverage -O0 -g   -I/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib -I/Users/schwarzy/dev/status/nim-brokers/test -o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_mt_large_payload/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.2.4@slib@sstd@sobjectdollar.nim.c.o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_mt_large_payload/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.2.4@slib@sstd@sobjectdollar.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_BigResp__zWgydHaiPw1a0RPvlQvrWQ tyObject_BigResp__zWgydHaiPw1a0RPvlQvrWQ;
typedef struct tyObject_SpillResp__v11TONOKTgajld8bMh9ccfw tyObject_SpillResp__v11TONOKTgajld8bMh9ccfw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_BigResp__zWgydHaiPw1a0RPvlQvrWQ {
	NimStringV2 blob;
};
struct tyObject_SpillResp__v11TONOKTgajld8bMh9ccfw {
	NimStringV2 blob;
};
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__stdZprivateZoscommon_u119)(NimStringV2* s_p0, NimStringV2 x_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4709)(void);
static N_INLINE(void, popFrame)(void);
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__US7tUPSVHwyWbwv9cB5DrpQ_2 = { 1 | NIM_STRLIT_FLAG, "(" };
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_3 = {1, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_2};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__US7tUPSVHwyWbwv9cB5DrpQ_4 = { 2 | NIM_STRLIT_FLAG, ", " };
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_5 = {2, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_4};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__US7tUPSVHwyWbwv9cB5DrpQ_7 = { 4 | NIM_STRLIT_FLAG, "blob" };
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_8 = {4, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_7};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__US7tUPSVHwyWbwv9cB5DrpQ_9 = { 2 | NIM_STRLIT_FLAG, ": " };
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_10 = {2, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_9};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__US7tUPSVHwyWbwv9cB5DrpQ_11 = { 1 | NIM_STRLIT_FLAG, ")" };
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_12 = {1, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_11};
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_13 = {1, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_2};
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_14 = {2, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_4};
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_15 = {4, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_7};
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_16 = {2, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_9};
static const NimStringV2 TM__US7tUPSVHwyWbwv9cB5DrpQ_17 = {1, (NimStrPayload*)&TM__US7tUPSVHwyWbwv9cB5DrpQ_11};
extern NIM_THREADVAR TFrame* framePtr__system_u2723;
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__US7tUPSVHwyWbwv9cB5DrpQ_6;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1731(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__US7tUPSVHwyWbwv9cB5DrpQ_6)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__US7tUPSVHwyWbwv9cB5DrpQ_6);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2723;
	framePtr__system_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2723 = (*framePtr__system_u2723).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___test95mt95large95payload_u7647)(tyObject_BigResp__zWgydHaiPw1a0RPvlQvrWQ x_p0) {
	NimStringV2 result;
	NI countX60gensym513__1;
	nimfr_("$", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/std/objectdollar.nim");
	nimlf_(13, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/std/objectdollar.nim");	nimlf_(19, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/std/private/miscdollars.nim");	result = TM__US7tUPSVHwyWbwv9cB5DrpQ_3;
	nimln_(21);	countX60gensym513__1 = ((NI)0);
	{
		if (!NIM_TRUE) goto LA3_;
		nimln_(23);		{
			if (!(((NI)0) < countX60gensym513__1)) goto LA7_;
			prepareAdd((&result), 2);
appendString((&result), TM__US7tUPSVHwyWbwv9cB5DrpQ_5);
		}
LA7_: ;
		nimln_(25);		prepareAdd((&result), 4);
appendString((&result), TM__US7tUPSVHwyWbwv9cB5DrpQ_8);
		nimln_(26);		prepareAdd((&result), 2);
appendString((&result), TM__US7tUPSVHwyWbwv9cB5DrpQ_10);
		nimln_(27);		countX60gensym513__1 += ((NI)1);
		nimln_(33);		addQuoted__stdZprivateZoscommon_u119((&result), x_p0.blob);
	}
LA3_: ;
	nimln_(39);	prepareAdd((&result), 1);
appendString((&result), TM__US7tUPSVHwyWbwv9cB5DrpQ_12);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___test95mt95large95payload_u10824)(tyObject_SpillResp__v11TONOKTgajld8bMh9ccfw x_p0) {
	NimStringV2 result;
	NI countX60gensym834__1;
	nimfr_("$", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/std/objectdollar.nim");
	nimlf_(13, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/std/objectdollar.nim");	nimlf_(19, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/std/private/miscdollars.nim");	result = TM__US7tUPSVHwyWbwv9cB5DrpQ_13;
	nimln_(21);	countX60gensym834__1 = ((NI)0);
	{
		if (!NIM_TRUE) goto LA3_;
		nimln_(23);		{
			if (!(((NI)0) < countX60gensym834__1)) goto LA7_;
			prepareAdd((&result), 2);
appendString((&result), TM__US7tUPSVHwyWbwv9cB5DrpQ_14);
		}
LA7_: ;
		nimln_(25);		prepareAdd((&result), 4);
appendString((&result), TM__US7tUPSVHwyWbwv9cB5DrpQ_15);
		nimln_(26);		prepareAdd((&result), 2);
appendString((&result), TM__US7tUPSVHwyWbwv9cB5DrpQ_16);
		nimln_(27);		countX60gensym834__1 += ((NI)1);
		nimln_(33);		addQuoted__stdZprivateZoscommon_u119((&result), x_p0.blob);
	}
LA3_: ;
	nimln_(39);	prepareAdd((&result), 1);
appendString((&result), TM__US7tUPSVHwyWbwv9cB5DrpQ_17);
	popFrame();
	return result;
}
