/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c -w -ferror-limit=3 -pthread --coverage -O0 -g   -I/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib -I/Users/schwarzy/dev/status/nim-brokers/test -o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_broker_interface_api/@m..@snimbledeps@spkgs2@schronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0@schronos@ssrcloc.nim.c.o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_broker_interface_api/@m..@snimbledeps@spkgs2@schronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0@schronos@ssrcloc.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w {
	NCSTRING procedure;
	NCSTRING file;
	NI line;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4709)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toString__pkgZchronosZsrcloc_u10)(NU64 value_p1);
static N_INLINE(NI, nimCStrLen)(NCSTRING a_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_2 = { 1 | NIM_STRLIT_FLAG, "(" };
static const NimStringV2 TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_3 = {1, (NimStrPayload*)&TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_2};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_5 = { 1 | NIM_STRLIT_FLAG, ")" };
static const NimStringV2 TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_6 = {1, (NimStrPayload*)&TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_5};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_7 = { 4 | NIM_STRLIT_FLAG, "    " };
static const NimStringV2 TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_8 = {4, (NimStrPayload*)&TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_7};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_9 = { 13 | NIM_STRLIT_FLAG, "[unspecified]" };
static const NimStringV2 TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_10 = {13, (NimStrPayload*)&TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_9};
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u7884 = {"getCode", "", ((NI)2)}
;
extern NIM_THREADVAR TFrame* framePtr__system_u2723;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4491;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u7849 = {"", "", ((NI)2)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u14237 = {"echoLen", "", ((NI)2)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u14493 = {"getCode", "test_broker_interface_api.nim", ((NI)32)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u14458 = {"", "test_broker_interface_api.nim", ((NI)32)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u14633 = {"echoLen", "test_broker_interface_api.nim", ((NI)37)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u14598 = {"", "test_broker_interface_api.nim", ((NI)37)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u1688 = {"handleMsgGetCode", "mt_request_broker.nim", ((NI)705)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u1479 = {"", "mt_request_broker.nim", ((NI)635)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__OOZbrokersZinternalZmt95broker95common_u942 = {"brokerDispatchLoop", "mt_broker_common.nim", ((NI)175)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__OOZbrokersZinternalZmt95broker95common_u885 = {"", "mt_broker_common.nim", ((NI)175)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__pkgZchronosZthreadsync_u812 = {"asyncthreadsignal.wait", "threadsync.nim", ((NI)369)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__pkgZchronosZthreadsync_u954 = {"", "threadsync.nim", ((NI)413)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__pkgZchronosZthreadsync_u841 = {"", "threadsync.nim", ((NI)393)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__pkgZchronosZthreadsync_u861 = {"", "threadsync.nim", ((NI)396)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__pkgZchronosZthreadsync_u900 = {"", "threadsync.nim", ((NI)400)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__pkgZchronosZthreadsync_u912 = {"", "threadsync.nim", ((NI)402)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__pkgZchronosZthreadsync_u993 = {"", "threadsync.nim", ((NI)417)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u14797 = {"anonymous", "", ((NI)3)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u14734 = {"", "", ((NI)3)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u9034 = {"handleMsgEchoLen", "mt_request_broker.nim", ((NI)705)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u8974 = {"", "mt_request_broker.nim", ((NI)700)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u15221 = {"anonymous", "", ((NI)5)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u15158 = {"", "", ((NI)5)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u5592 = {"request", "mt_request_broker.nim", ((NI)1149)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u5557 = {"", "mt_request_broker.nim", ((NI)1192)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u4631 = {"sendAndAwaitGetCode", "mt_request_broker.nim", ((NI)926)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u3227 = {"request.GetCode", "mt_request_broker.nim", ((NI)989)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u3267 = {"", "mt_request_broker.nim", ((NI)1016)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u4567 = {"", "mt_request_broker.nim", ((NI)1042)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u3318 = {"chronos.withTimeout", "asyncfutures.nim", ((NI)1502)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u3772 = {"", "asyncfutures.nim", ((NI)1554)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u3792 = {"", "asyncfutures.nim", ((NI)1557)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u3709 = {"", "asyncfutures.nim", ((NI)1548)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u3491 = {"", "asyncfutures.nim", ((NI)1512)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u3618 = {"", "asyncfutures.nim", ((NI)1515)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u3633 = {"", "asyncfutures.nim", ((NI)1517)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u3643 = {"", "asyncfutures.nim", ((NI)1534)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u3858 = {"", "mt_request_broker.nim", ((NI)1023)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u3973 = {"", "mt_request_broker.nim", ((NI)1030)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u13162 = {"request", "mt_request_broker.nim", ((NI)1313)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u13127 = {"", "mt_request_broker.nim", ((NI)1357)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u10186 = {"sendAndAwaitEchoLen", "mt_request_broker.nim", ((NI)926)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95broker95interface95api_u9378 = {"request.EchoLen", "mt_request_broker.nim", ((NI)989)}
;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2723;
	framePtr__system_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2723 = (*framePtr__system_u2723).prev;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u7876)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimlf_(37, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u7884);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_4;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1731(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_4)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_4);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
static N_INLINE(NI, nimCStrLen)(NCSTRING a_p0) {
	NI result;
	size_t T5_;
{	result = (NI)0;
	{
		if (!(a_p0 == 0)) goto LA3_;
		result = ((NI)0);
		goto BeforeRet_;
	}
LA3_: ;
	T5_ = (size_t)0;
	T5_ = strlen(a_p0);
	result = ((NI) (T5_));
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4491);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pkgZchronosZsrcloc_u6)(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* loc_p0) {
	NimStringV2 result;
	NimStringV2 res_1;
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("$", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	res_1.len = 0; res_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimln_(21);	res_1 = cstrToNimstr((*loc_p0).file);
	nimln_(22);	prepareAdd((&res_1), 1);
appendString((&res_1), TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_3);
	nimln_(23);	colontmpD_ = toString__pkgZchronosZsrcloc_u10(((NU64) ((*loc_p0).line)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	prepareAdd((&res_1), colontmpD_.len + 0);
appendString((&res_1), colontmpD_);
	nimln_(24);	prepareAdd((&res_1), 1);
appendString((&res_1), TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_6);
	nimln_(25);	prepareAdd((&res_1), 4);
appendString((&res_1), TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_8);
	nimln_(26);	{
		if (!(nimCStrLen((*loc_p0).procedure) == ((NI)0))) goto LA3_;
		nimln_(27);		prepareAdd((&res_1), 13);
appendString((&res_1), TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_10);
	}
	goto LA1_;
LA3_: ;
	{
		NimStringV2 colontmpD__2;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		nimln_(29);		colontmpD__2 = cstrToNimstr((*loc_p0).procedure);
		prepareAdd((&res_1), colontmpD__2.len + 0);
appendString((&res_1), colontmpD__2);
		nimlf_(394, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
	}
LA1_: ;
	nimlf_(20, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");	nimln_(30);	result = res_1;
	nimlf_(394, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u7841)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimlf_(37, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u7849);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u14229)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u14237);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u14485)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u14493);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u14450)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u14458);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u14625)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u14633);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u14590)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u14598);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u1680)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u1688);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u1471)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u1479);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__OOZbrokersZinternalZmt95broker95common_u934)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__OOZbrokersZinternalZmt95broker95common_u942);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__OOZbrokersZinternalZmt95broker95common_u877)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__OOZbrokersZinternalZmt95broker95common_u885);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__pkgZchronosZthreadsync_u804)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__pkgZchronosZthreadsync_u812);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__pkgZchronosZthreadsync_u946)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__pkgZchronosZthreadsync_u954);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__pkgZchronosZthreadsync_u833)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__pkgZchronosZthreadsync_u841);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__pkgZchronosZthreadsync_u853)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__pkgZchronosZthreadsync_u861);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__pkgZchronosZthreadsync_u892)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__pkgZchronosZthreadsync_u900);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__pkgZchronosZthreadsync_u904)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__pkgZchronosZthreadsync_u912);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__pkgZchronosZthreadsync_u985)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__pkgZchronosZthreadsync_u993);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u14789)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u14797);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u14726)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u14734);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u9026)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u9034);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u8966)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u8974);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u15213)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u15221);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u15150)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u15158);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u5584)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u5592);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u5549)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u5557);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u4623)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u4631);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u3219)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u3227);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u3259)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u3267);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u4559)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u4567);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u3310)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u3318);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u3764)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u3772);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u3784)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u3792);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u3701)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u3709);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u3483)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u3491);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u3610)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u3618);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u3625)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u3633);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u3635)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u3643);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u3850)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u3858);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u3965)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u3973);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u13154)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u13162);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u13119)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u13127);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u10178)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u10186);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95broker95interface95api_u9370)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95broker95interface95api_u9378);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
