/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c -w -ferror-limit=3 -pthread --coverage -O0 -g   -I/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib -I/Users/schwarzy/dev/status/nim-brokers/test -o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_broker_interface_api/@m..@sbrokers@sinternal@smt_codec.nim.c.o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_broker_interface_api/@m..@sbrokers@sinternal@smt_codec.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_GetCodeMtRequestMsg__wpU4BAqJ9ak9bBMfSF37nggQ tyObject_GetCodeMtRequestMsg__wpU4BAqJ9ak9bBMfSF37nggQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_EchoLenMtRequestMsg__HP3xLSagsTQgWQF4x1fU9cw tyObject_EchoLenMtRequestMsg__HP3xLSagsTQgWQF4x1fU9cw;
typedef struct tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_EchoLenMtRequestMsg__HP3xLSagsTQgWQF4x1fU9cw {
	NI requestKind;
	NimStringV2 s;
	NU32 responseSlotIdx;
	tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA* requesterSignal;
};
struct tyObject_GetCodeMtRequestMsg__wpU4BAqJ9ak9bBMfSF37nggQ {
	NI requestKind;
	NU32 responseSlotIdx;
	tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA* requesterSignal;
};
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4709)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95broker95interface95api_u8237)(NU8* buf_p0, NI len_p1, NI* value_p2, NI* pos_p3);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95broker95interface95api_u745)(NU8* buf_p0, NI len_p1, NimStringV2* value_p2, NI* pos_p3);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2696)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95broker95interface95api_u8267)(NU8* buf_p0, NI len_p1, NU32* value_p2, NI* pos_p3);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95broker95interface95api_u8291)(NU8* buf_p0, NI len_p1, tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA** value_p2, NI* pos_p3);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95broker95interface95api_u8118)(NU8* buf_p0, NI cap_p1, NI value_p2, NI* pos_p3);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95broker95interface95api_u679)(NU8* buf_p0, NI cap_p1, NimStringV2 value_p2, NI* pos_p3);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95broker95interface95api_u8148)(NU8* buf_p0, NI cap_p1, NU32 value_p2, NI* pos_p3);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95broker95interface95api_u8172)(NU8* buf_p0, NI cap_p1, tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA* value_p2, NI* pos_p3);
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95broker95interface95api_u8331)(NI value_p0);
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95broker95interface95api_u859)(NimStringV2 value_p0);
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95broker95interface95api_u8353)(NU32 value_p0);
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95broker95interface95api_u8368)(tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA* value_p0);
extern NIM_THREADVAR TFrame* framePtr__system_u2723;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4491;
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2723;
	framePtr__system_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2723 = (*framePtr__system_u2723).prev;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95broker95interface95api_u532)(NU8* buf_p0, NI len_p1, tyObject_GetCodeMtRequestMsg__wpU4BAqJ9ak9bBMfSF37nggQ* value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_3;
	nimfr_("mtUnmarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimlf_(175, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_2;
		if (nimAddInt((*pos_p3), ((NI)24), &TM__gSOrWU7W2lzpIJkvkwiA9bw_2)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(len_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_2))) goto LA3_;
		nimln_(176);		nimln_(153);		nimln_(176);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(177);	copyMem__system_u1731(((void*) (value_p2)), ((void*) ((&buf_p0[(*pos_p3)]))), ((NI)24));
	nimln_(178);	if (nimAddInt((*pos_p3), ((NI)24), &TM__gSOrWU7W2lzpIJkvkwiA9bw_3)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_3);
	nimln_(179);	nimln_(153);	nimln_(179);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95broker95interface95api_u632)(NU8* buf_p0, NI cap_p1, NI32 value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_5;
	nimfr_("mtMarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(115);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_4;
		if (nimAddInt((*pos_p3), ((NI)4), &TM__gSOrWU7W2lzpIJkvkwiA9bw_4)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(cap_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_4))) goto LA3_;
		nimln_(116);		nimln_(91);		nimln_(116);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(117);	copyMem__system_u1731(((void*) ((&buf_p0[(*pos_p3)]))), ((void*) ((&value_p2))), ((NI)4));
	nimln_(118);	if (nimAddInt((*pos_p3), ((NI)4), &TM__gSOrWU7W2lzpIJkvkwiA9bw_5)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_5);
	nimln_(119);	nimln_(91);	nimln_(119);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95broker95interface95api_u679)(NU8* buf_p0, NI cap_p1, NimStringV2 value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NU32 sLen_1;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_8;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_9;
	nimfr_("mtMarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	result = (NIM_BOOL)0;
	nimln_(121);	sLen_1 = ((NU32) (value_p2.len));
	nimln_(122);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_6;
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_7;
		if (nimAddInt((*pos_p3), ((NI)4), &TM__gSOrWU7W2lzpIJkvkwiA9bw_6)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimAddInt((NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_6), ((NI) (sLen_1)), &TM__gSOrWU7W2lzpIJkvkwiA9bw_7)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(cap_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_7))) goto LA3_;
		nimln_(123);		nimln_(91);		nimln_(123);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(124);	copyMem__system_u1731(((void*) ((&buf_p0[(*pos_p3)]))), ((void*) ((&sLen_1))), ((NI)4));
	nimln_(125);	if (nimAddInt((*pos_p3), ((NI)4), &TM__gSOrWU7W2lzpIJkvkwiA9bw_8)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_8);
	nimln_(126);	{
		if (!((NU32)(((NU32)0)) < (NU32)(sLen_1))) goto LA7_;
		nimln_(127);		if (((NI)0) < 0 || ((NI)0) >= value_p2.len){ raiseIndexError2(((NI)0),value_p2.len-1); goto BeforeRet_;
		}
		if ((((NI) (sLen_1))) < ((NI)0) || (((NI) (sLen_1))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(((NI) (sLen_1)), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1731(((void*) ((&buf_p0[(*pos_p3)]))), ((void*) ((&value_p2.p->data[((NI)0)]))), (((NI) (sLen_1))));
	}
LA7_: ;
	nimln_(128);	if (nimAddInt((*pos_p3), ((NI) (sLen_1)), &TM__gSOrWU7W2lzpIJkvkwiA9bw_9)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_9);
	nimln_(129);	nimln_(91);	nimln_(129);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95broker95interface95api_u827)(NI32 value_p0) {
	NI result;
	nimfr_("mtMarshalSizeValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(244);	nimln_(236);	nimln_(244);	result = ((NI)4);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95broker95interface95api_u859)(NimStringV2 value_p0) {
	NI result;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_10;
	nimfr_("mtMarshalSizeValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(246);	nimln_(236);	nimln_(246);	if (nimAddInt(((NI)4), value_p0.len, &TM__gSOrWU7W2lzpIJkvkwiA9bw_10)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_10);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95broker95interface95api_u8237)(NU8* buf_p0, NI len_p1, NI* value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_12;
	nimfr_("mtUnmarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(175);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_11;
		if (nimAddInt((*pos_p3), ((NI)8), &TM__gSOrWU7W2lzpIJkvkwiA9bw_11)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(len_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_11))) goto LA3_;
		nimln_(176);		nimln_(153);		nimln_(176);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(177);	copyMem__system_u1731(((void*) (value_p2)), ((void*) ((&buf_p0[(*pos_p3)]))), ((NI)8));
	nimln_(178);	if (nimAddInt((*pos_p3), ((NI)8), &TM__gSOrWU7W2lzpIJkvkwiA9bw_12)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_12);
	nimln_(179);	nimln_(153);	nimln_(179);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95broker95interface95api_u745)(NU8* buf_p0, NI len_p1, NimStringV2* value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NU32 sLen_1;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_14;
	NimStringV2 T9_;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_16;
	nimfr_("mtUnmarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	result = (NIM_BOOL)0;
	nimln_(181);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_13;
		if (nimAddInt((*pos_p3), ((NI)4), &TM__gSOrWU7W2lzpIJkvkwiA9bw_13)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(len_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_13))) goto LA3_;
		nimln_(182);		nimln_(153);		nimln_(182);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	sLen_1 = (NU32)0;
	nimln_(184);	copyMem__system_u1731(((void*) ((&sLen_1))), ((void*) ((&buf_p0[(*pos_p3)]))), ((NI)4));
	nimln_(185);	if (nimAddInt((*pos_p3), ((NI)4), &TM__gSOrWU7W2lzpIJkvkwiA9bw_14)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_14);
	nimln_(186);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_15;
		if (nimAddInt((*pos_p3), ((NI) (sLen_1)), &TM__gSOrWU7W2lzpIJkvkwiA9bw_15)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(len_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_15))) goto LA7_;
		nimln_(187);		nimln_(153);		nimln_(187);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA7_: ;
	nimlf_(1694, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	nimlf_(188, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");	if ((((NI) (sLen_1))) < ((NI)0) || (((NI) (sLen_1))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(((NI) (sLen_1)), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	T9_.len = 0; T9_.p = NIM_NIL;
	T9_ = mnewString((((NI) (sLen_1))));
	nimlf_(1694, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	eqsink___system_u2696((&(*value_p2)), T9_);
	nimlf_(189, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");	{
		if (!((NU32)(((NU32)0)) < (NU32)(sLen_1))) goto LA12_;
		nimln_(190);		if (((NI)0) < 0 || ((NI)0) >= (*value_p2).len){ raiseIndexError2(((NI)0),(*value_p2).len-1); goto BeforeRet_;
		}
		if ((((NI) (sLen_1))) < ((NI)0) || (((NI) (sLen_1))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(((NI) (sLen_1)), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1731(((void*) ((&(*value_p2).p->data[((NI)0)]))), ((void*) ((&buf_p0[(*pos_p3)]))), (((NI) (sLen_1))));
	}
LA12_: ;
	nimln_(191);	if (nimAddInt((*pos_p3), ((NI) (sLen_1)), &TM__gSOrWU7W2lzpIJkvkwiA9bw_16)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_16);
	nimln_(192);	nimln_(153);	nimln_(192);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95broker95interface95api_u8267)(NU8* buf_p0, NI len_p1, NU32* value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_18;
	nimfr_("mtUnmarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(175);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_17;
		if (nimAddInt((*pos_p3), ((NI)4), &TM__gSOrWU7W2lzpIJkvkwiA9bw_17)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(len_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_17))) goto LA3_;
		nimln_(176);		nimln_(153);		nimln_(176);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(177);	copyMem__system_u1731(((void*) (value_p2)), ((void*) ((&buf_p0[(*pos_p3)]))), ((NI)4));
	nimln_(178);	if (nimAddInt((*pos_p3), ((NI)4), &TM__gSOrWU7W2lzpIJkvkwiA9bw_18)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_18);
	nimln_(179);	nimln_(153);	nimln_(179);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95broker95interface95api_u8291)(NU8* buf_p0, NI len_p1, tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA** value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_20;
	nimfr_("mtUnmarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(175);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_19;
		if (nimAddInt((*pos_p3), ((NI)8), &TM__gSOrWU7W2lzpIJkvkwiA9bw_19)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(len_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_19))) goto LA3_;
		nimln_(176);		nimln_(153);		nimln_(176);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(177);	copyMem__system_u1731(((void*) (value_p2)), ((void*) ((&buf_p0[(*pos_p3)]))), ((NI)8));
	nimln_(178);	if (nimAddInt((*pos_p3), ((NI)8), &TM__gSOrWU7W2lzpIJkvkwiA9bw_20)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_20);
	nimln_(179);	nimln_(153);	nimln_(179);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4491);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95broker95interface95api_u8221)(NU8* buf_p0, NI len_p1, tyObject_EchoLenMtRequestMsg__HP3xLSagsTQgWQF4x1fU9cw* value_p2, NI* pos_p3) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("mtUnmarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{nimErr_ = nimErrorFlag();
	{
		if (!NIM_TRUE) goto LA3_;
		nimln_(202);		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = mtUnmarshalValue__test95broker95interface95api_u8237(buf_p0, len_p1, (&(*value_p2).requestKind), pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T7_)) goto LA8_;
			nimln_(203);			nimln_(153);			nimln_(203);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA8_: ;
	}
LA3_: ;
	{
		if (!NIM_TRUE) goto LA12_;
		nimln_(202);		{
			NIM_BOOL T16_;
			T16_ = (NIM_BOOL)0;
			T16_ = mtUnmarshalValue__test95broker95interface95api_u745(buf_p0, len_p1, (&(*value_p2).s), pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T16_)) goto LA17_;
			nimln_(203);			nimln_(153);			nimln_(203);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA17_: ;
	}
LA12_: ;
	{
		if (!NIM_TRUE) goto LA21_;
		nimln_(202);		{
			NIM_BOOL T25_;
			T25_ = (NIM_BOOL)0;
			T25_ = mtUnmarshalValue__test95broker95interface95api_u8267(buf_p0, len_p1, (&(*value_p2).responseSlotIdx), pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T25_)) goto LA26_;
			nimln_(203);			nimln_(153);			nimln_(203);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA26_: ;
	}
LA21_: ;
	{
		if (!NIM_TRUE) goto LA30_;
		nimln_(202);		{
			NIM_BOOL T34_;
			T34_ = (NIM_BOOL)0;
			T34_ = mtUnmarshalValue__test95broker95interface95api_u8291(buf_p0, len_p1, &(*value_p2).requesterSignal, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T34_)) goto LA35_;
			nimln_(203);			nimln_(153);			nimln_(203);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA35_: ;
	}
LA30_: ;
	nimln_(204);	nimln_(153);	nimln_(204);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95broker95interface95api_u483)(NU8* buf_p0, NI cap_p1, tyObject_GetCodeMtRequestMsg__wpU4BAqJ9ak9bBMfSF37nggQ value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_22;
	nimfr_("mtMarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(115);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_21;
		if (nimAddInt((*pos_p3), ((NI)24), &TM__gSOrWU7W2lzpIJkvkwiA9bw_21)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(cap_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_21))) goto LA3_;
		nimln_(116);		nimln_(91);		nimln_(116);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(117);	copyMem__system_u1731(((void*) ((&buf_p0[(*pos_p3)]))), ((void*) ((&value_p2))), ((NI)24));
	nimln_(118);	if (nimAddInt((*pos_p3), ((NI)24), &TM__gSOrWU7W2lzpIJkvkwiA9bw_22)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_22);
	nimln_(119);	nimln_(91);	nimln_(119);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95broker95interface95api_u559)(tyObject_GetCodeMtRequestMsg__wpU4BAqJ9ak9bBMfSF37nggQ value_p0) {
	NI result;
	nimfr_("mtMarshalSizeValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(244);	nimln_(236);	nimln_(244);	result = ((NI)24);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95broker95interface95api_u713)(NU8* buf_p0, NI len_p1, NI32* value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_24;
	nimfr_("mtUnmarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(175);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_23;
		if (nimAddInt((*pos_p3), ((NI)4), &TM__gSOrWU7W2lzpIJkvkwiA9bw_23)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(len_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_23))) goto LA3_;
		nimln_(176);		nimln_(153);		nimln_(176);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(177);	copyMem__system_u1731(((void*) (value_p2)), ((void*) ((&buf_p0[(*pos_p3)]))), ((NI)4));
	nimln_(178);	if (nimAddInt((*pos_p3), ((NI)4), &TM__gSOrWU7W2lzpIJkvkwiA9bw_24)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_24);
	nimln_(179);	nimln_(153);	nimln_(179);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95broker95interface95api_u8118)(NU8* buf_p0, NI cap_p1, NI value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_26;
	nimfr_("mtMarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(115);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_25;
		if (nimAddInt((*pos_p3), ((NI)8), &TM__gSOrWU7W2lzpIJkvkwiA9bw_25)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(cap_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_25))) goto LA3_;
		nimln_(116);		nimln_(91);		nimln_(116);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(117);	copyMem__system_u1731(((void*) ((&buf_p0[(*pos_p3)]))), ((void*) ((&value_p2))), ((NI)8));
	nimln_(118);	if (nimAddInt((*pos_p3), ((NI)8), &TM__gSOrWU7W2lzpIJkvkwiA9bw_26)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_26);
	nimln_(119);	nimln_(91);	nimln_(119);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95broker95interface95api_u8148)(NU8* buf_p0, NI cap_p1, NU32 value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_28;
	nimfr_("mtMarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(115);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_27;
		if (nimAddInt((*pos_p3), ((NI)4), &TM__gSOrWU7W2lzpIJkvkwiA9bw_27)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(cap_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_27))) goto LA3_;
		nimln_(116);		nimln_(91);		nimln_(116);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(117);	copyMem__system_u1731(((void*) ((&buf_p0[(*pos_p3)]))), ((void*) ((&value_p2))), ((NI)4));
	nimln_(118);	if (nimAddInt((*pos_p3), ((NI)4), &TM__gSOrWU7W2lzpIJkvkwiA9bw_28)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_28);
	nimln_(119);	nimln_(91);	nimln_(119);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95broker95interface95api_u8172)(NU8* buf_p0, NI cap_p1, tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA* value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_30;
	nimfr_("mtMarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(115);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_29;
		if (nimAddInt((*pos_p3), ((NI)8), &TM__gSOrWU7W2lzpIJkvkwiA9bw_29)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(cap_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_29))) goto LA3_;
		nimln_(116);		nimln_(91);		nimln_(116);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(117);	copyMem__system_u1731(((void*) ((&buf_p0[(*pos_p3)]))), ((void*) (&value_p2)), ((NI)8));
	nimln_(118);	if (nimAddInt((*pos_p3), ((NI)8), &TM__gSOrWU7W2lzpIJkvkwiA9bw_30)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_30);
	nimln_(119);	nimln_(91);	nimln_(119);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95broker95interface95api_u8102)(NU8* buf_p0, NI cap_p1, tyObject_EchoLenMtRequestMsg__HP3xLSagsTQgWQF4x1fU9cw* value_p2, NI* pos_p3) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("mtMarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{nimErr_ = nimErrorFlag();
	{
		if (!NIM_TRUE) goto LA3_;
		nimln_(140);		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = mtMarshalValue__test95broker95interface95api_u8118(buf_p0, cap_p1, (*value_p2).requestKind, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T7_)) goto LA8_;
			nimln_(141);			nimln_(91);			nimln_(141);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA8_: ;
	}
LA3_: ;
	{
		if (!NIM_TRUE) goto LA12_;
		nimln_(140);		{
			NIM_BOOL T16_;
			T16_ = (NIM_BOOL)0;
			T16_ = mtMarshalValue__test95broker95interface95api_u679(buf_p0, cap_p1, (*value_p2).s, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T16_)) goto LA17_;
			nimln_(141);			nimln_(91);			nimln_(141);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA17_: ;
	}
LA12_: ;
	{
		if (!NIM_TRUE) goto LA21_;
		nimln_(140);		{
			NIM_BOOL T25_;
			T25_ = (NIM_BOOL)0;
			T25_ = mtMarshalValue__test95broker95interface95api_u8148(buf_p0, cap_p1, (*value_p2).responseSlotIdx, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T25_)) goto LA26_;
			nimln_(141);			nimln_(91);			nimln_(141);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA26_: ;
	}
LA21_: ;
	{
		if (!NIM_TRUE) goto LA30_;
		nimln_(140);		{
			NIM_BOOL T34_;
			T34_ = (NIM_BOOL)0;
			T34_ = mtMarshalValue__test95broker95interface95api_u8172(buf_p0, cap_p1, (*value_p2).requesterSignal, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T34_)) goto LA35_;
			nimln_(141);			nimln_(91);			nimln_(141);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA35_: ;
	}
LA30_: ;
	nimln_(142);	nimln_(91);	nimln_(142);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95broker95interface95api_u8331)(NI value_p0) {
	NI result;
	nimfr_("mtMarshalSizeValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(244);	nimln_(236);	nimln_(244);	result = ((NI)8);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95broker95interface95api_u8353)(NU32 value_p0) {
	NI result;
	nimfr_("mtMarshalSizeValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(244);	nimln_(236);	nimln_(244);	result = ((NI)4);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95broker95interface95api_u8368)(tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA* value_p0) {
	NI result;
	nimfr_("mtMarshalSizeValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(244);	nimln_(236);	nimln_(244);	result = ((NI)8);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95broker95interface95api_u8318)(tyObject_EchoLenMtRequestMsg__HP3xLSagsTQgWQF4x1fU9cw* value_p0) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("mtMarshalSizeValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{nimErr_ = nimErrorFlag();
	nimln_(254);	result = ((NI)0);
	{
		NI T5_;
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_31;
		if (!NIM_TRUE) goto LA3_;
		nimln_(256);		T5_ = (NI)0;
		T5_ = mtMarshalSizeValue__test95broker95interface95api_u8331((*value_p0).requestKind);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt(result, T5_, &TM__gSOrWU7W2lzpIJkvkwiA9bw_31)) { raiseOverflow(); goto BeforeRet_;
		};
		result = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_31);
	}
LA3_: ;
	{
		NI T10_;
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_32;
		if (!NIM_TRUE) goto LA8_;
		nimln_(256);		T10_ = (NI)0;
		T10_ = mtMarshalSizeValue__test95broker95interface95api_u859((*value_p0).s);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt(result, T10_, &TM__gSOrWU7W2lzpIJkvkwiA9bw_32)) { raiseOverflow(); goto BeforeRet_;
		};
		result = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_32);
	}
LA8_: ;
	{
		NI T15_;
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_33;
		if (!NIM_TRUE) goto LA13_;
		nimln_(256);		T15_ = (NI)0;
		T15_ = mtMarshalSizeValue__test95broker95interface95api_u8353((*value_p0).responseSlotIdx);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt(result, T15_, &TM__gSOrWU7W2lzpIJkvkwiA9bw_33)) { raiseOverflow(); goto BeforeRet_;
		};
		result = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_33);
	}
LA13_: ;
	{
		NI T20_;
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_34;
		if (!NIM_TRUE) goto LA18_;
		nimln_(256);		T20_ = (NI)0;
		T20_ = mtMarshalSizeValue__test95broker95interface95api_u8368((*value_p0).requesterSignal);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt(result, T20_, &TM__gSOrWU7W2lzpIJkvkwiA9bw_34)) { raiseOverflow(); goto BeforeRet_;
		};
		result = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_34);
	}
LA18_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
