# Auto-generated by brokers/api_codegen_cmake.nim — do not edit.
# CMake package for the 'cbtest' broker FFI library.
#
# Provides:
#   cbtest::cbtest       — IMPORTED SHARED library + C headers
#   cbtest::cbtest_cpp   — INTERFACE for C++ consumers (C++20)
#       (depends on jsoncons; set CBTEST_JSONCONS_INCLUDE_DIR to override discovery)

cmake_minimum_required(VERSION 3.16)

get_filename_component(_cbtest_pkg_dir "${CMAKE_CURRENT_LIST_DIR}" ABSOLUTE)

if(WIN32)
  set(_cbtest_shared_name "cbtest.dll")
  set(_cbtest_import_name "cbtest.lib")
elseif(APPLE)
  set(_cbtest_shared_name "libcbtest.dylib")
else()
  set(_cbtest_shared_name "libcbtest.so")
endif()

set(_cbtest_shared_path "${_cbtest_pkg_dir}/${_cbtest_shared_name}")
if(NOT EXISTS "${_cbtest_shared_path}")
  message(FATAL_ERROR "cbtest: shared library not found at '${_cbtest_shared_path}'.")
endif()

set(_cbtest_header_path "${_cbtest_pkg_dir}/cbtest.h")
if(NOT EXISTS "${_cbtest_header_path}")
  message(FATAL_ERROR "cbtest: C header not found at '${_cbtest_header_path}'.")
endif()

if(NOT TARGET cbtest::cbtest)
  add_library(cbtest::cbtest SHARED IMPORTED)
  set_target_properties(cbtest::cbtest PROPERTIES
    IMPORTED_LOCATION "${_cbtest_shared_path}"
    INTERFACE_INCLUDE_DIRECTORIES "${_cbtest_pkg_dir}"
  )
  if(WIN32)
    set(_cbtest_import_path "${_cbtest_pkg_dir}/${_cbtest_import_name}")
    if(EXISTS "${_cbtest_import_path}")
      set_target_properties(cbtest::cbtest PROPERTIES IMPORTED_IMPLIB "${_cbtest_import_path}")
    endif()
  endif()
endif()

if(NOT TARGET cbtest::cbtest_cpp)
  add_library(cbtest::cbtest_cpp INTERFACE IMPORTED)
  set_property(TARGET cbtest::cbtest_cpp PROPERTY INTERFACE_LINK_LIBRARIES cbtest::cbtest)
  set_property(TARGET cbtest::cbtest_cpp PROPERTY INTERFACE_COMPILE_FEATURES cxx_std_20)

  # jsoncons (header-only) is required by the CBOR-mode C++ wrapper.
  if(NOT DEFINED CBTEST_JSONCONS_INCLUDE_DIR)
    find_path(CBTEST_JSONCONS_INCLUDE_DIR
      NAMES jsoncons/json.hpp
      PATHS
        "${_cbtest_pkg_dir}/../../vendor/jsoncons/include"
        "${_cbtest_pkg_dir}/../vendor/jsoncons/include"
        "${_cbtest_pkg_dir}/vendor/jsoncons/include"
      DOC "Path to the jsoncons header-only library (root containing 'jsoncons/json.hpp')."
    )
  endif()
  if(NOT CBTEST_JSONCONS_INCLUDE_DIR)
    message(FATAL_ERROR "cbtest (CBOR mode): jsoncons headers not found. Install jsoncons or set CBTEST_JSONCONS_INCLUDE_DIR.")
  endif()
  set_property(TARGET cbtest::cbtest_cpp APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${CBTEST_JSONCONS_INCLUDE_DIR}")
endif()

set(cbtest_FOUND TRUE)
set(cbtest_VERSION "0.1.0")
set(cbtest_LIBRARY "${_cbtest_shared_path}")
set(cbtest_INCLUDE_DIR "${_cbtest_pkg_dir}")
