/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c -w -ferror-limit=3 -pthread --coverage -O0 -g   -I/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib -I/Users/schwarzy/dev/status/nim-brokers/test -o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_api_codec/@m..@snimbledeps@spkgs2@scbor_serialization-0.3.0-ab126eae09a6e39c72972a6a0b83cb06a2ffe8f0@scbor_serialization@sstd@soptions.nim.c.o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_api_codec/@m..@snimbledeps@spkgs2@scbor_serialization-0.3.0-ab126eae09a6e39c72972a6a0b83cb06a2ffe8f0@scbor_serialization@sstd@soptions.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_CborWriter__xEBM3Te82WVh9bEvuN4TCDA tyObject_CborWriter__xEBM3Te82WVh9bEvuN4TCDA;
typedef struct tyObject_Option__pvvSnZeKH2zYR1ucaskI2Q tyObject_Option__pvvSnZeKH2zYR1ucaskI2Q;
typedef struct tyObject_UnpackDefect__9boKnUzzlKIwZ8YT0xflFwg tyObject_UnpackDefect__9boKnUzzlKIwZ8YT0xflFwg;
typedef struct tyObject_Defect__OLYFuJPT5QhYBTTeFCXlVw tyObject_Defect__OLYFuJPT5QhYBTTeFCXlVw;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__89azkb4JUGfhEDamui6ufig tySequence__89azkb4JUGfhEDamui6ufig;
typedef struct tySequence__89azkb4JUGfhEDamui6ufig_Content tySequence__89azkb4JUGfhEDamui6ufig_Content;
typedef struct tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw;
typedef struct tyObject_CborParser__IDniep5pczeSdSoPTCW49bA tyObject_CborParser__IDniep5pczeSdSoPTCW49bA;
typedef struct tyObject_InputStreamcolonObjectType___eCBhO30DCqpSAp7CCGbLpQ tyObject_InputStreamcolonObjectType___eCBhO30DCqpSAp7CCGbLpQ;
typedef struct tyObject_CborReaderConf__jXtWckj6pLnpFAtODteNbA tyObject_CborReaderConf__jXtWckj6pLnpFAtODteNbA;
typedef struct tyObject_Option__6YPMiqKtxsl9cNAxTGMCGRw tyObject_Option__6YPMiqKtxsl9cNAxTGMCGRw;
typedef struct tyObject_Option__dzYlIYYfBcOnary9bSUvnEw tyObject_Option__dzYlIYYfBcOnary9bSUvnEw;
typedef struct tyObject_Player__9byiOJu6V6reRS1OaIqhosA tyObject_Player__9byiOJu6V6reRS1OaIqhosA;
typedef struct tyObject_Point__rzRRYfAs7f2wLSNNgzBIdQ tyObject_Point__rzRRYfAs7f2wLSNNgzBIdQ;
typedef struct tyObject_Option__p3Fp2wt7a9bxd3AbI5df7WA tyObject_Option__p3Fp2wt7a9bxd3AbI5df7WA;
typedef struct tyObject_CborUnit__kgU055IFf9aZaWkN089aQR9aA tyObject_CborUnit__kgU055IFf9aZaWkN089aQR9aA;
typedef struct tyObject_StackTraceEntry__w39bij9cdqZCCca2z9b9aO6Teg tyObject_StackTraceEntry__w39bij9cdqZCCca2z9b9aO6Teg;
struct tyObject_Option__pvvSnZeKH2zYR1ucaskI2Q {
	NI32 val;
	NIM_BOOL has;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__89azkb4JUGfhEDamui6ufig {
  NI len; tySequence__89azkb4JUGfhEDamui6ufig_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__89azkb4JUGfhEDamui6ufig trace;
	Exception* up;
};
struct tyObject_Defect__OLYFuJPT5QhYBTTeFCXlVw {
	Exception Sup;
};
struct tyObject_UnpackDefect__9boKnUzzlKIwZ8YT0xflFwg {
	tyObject_Defect__OLYFuJPT5QhYBTTeFCXlVw Sup;
};
typedef NU8 tyEnum_CborValueKind__wziIkCT08cTZ71gMnjCCkw;
struct tyObject_CborReaderConf__jXtWckj6pLnpFAtODteNbA {
	NI nestedDepthLimit;
	NI arrayElementsLimit;
	NI objectFieldsLimit;
	NI stringLengthLimit;
	NI byteStringLengthLimit;
	NI bigNumBytesLimit;
};
struct tyObject_CborParser__IDniep5pczeSdSoPTCW49bA {
	tyObject_InputStreamcolonObjectType___eCBhO30DCqpSAp7CCGbLpQ* stream;
	tyObject_CborReaderConf__jXtWckj6pLnpFAtODteNbA conf;
	NI currDepth;
};
struct tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw {
	tyObject_CborParser__IDniep5pczeSdSoPTCW49bA parser;
};
struct tyObject_Option__6YPMiqKtxsl9cNAxTGMCGRw {
	NimStringV2 val;
	NIM_BOOL has;
};
typedef NU8 tyEnum_Color__qRnCJ4qtf0Ta2W9bSnAtf7w;
struct tyObject_Point__rzRRYfAs7f2wLSNNgzBIdQ {
	NI32 x;
	NI32 y;
};
struct tyObject_Player__9byiOJu6V6reRS1OaIqhosA {
	NimStringV2 name;
	NU64 score;
	tyEnum_Color__qRnCJ4qtf0Ta2W9bSnAtf7w favorite;
	tyObject_Point__rzRRYfAs7f2wLSNNgzBIdQ pos;
};
struct tyObject_Option__dzYlIYYfBcOnary9bSUvnEw {
	tyObject_Player__9byiOJu6V6reRS1OaIqhosA val;
	NIM_BOOL has;
};
struct tyObject_CborUnit__kgU055IFf9aZaWkN089aQR9aA {
	char dummy;
};
struct tyObject_Option__p3Fp2wt7a9bxd3AbI5df7WA {
	tyObject_CborUnit__kgU055IFf9aZaWkN089aQR9aA val;
	NIM_BOOL has;
};
struct tyObject_StackTraceEntry__w39bij9cdqZCCca2z9b9aO6Teg {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__89azkb4JUGfhEDamui6ufig_Content { NI cap; tyObject_StackTraceEntry__w39bij9cdqZCCca2z9b9aO6Teg data[SEQ_DECL_SIZE]; };
static N_INLINE(NIM_BOOL, isSome__test95api95codec_u9633)(tyObject_Option__pvvSnZeKH2zYR1ucaskI2Q self_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4709)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, write__test95api95codec_u218)(tyObject_CborWriter__xEBM3Te82WVh9bEvuN4TCDA* w_p0, NI32 val_p1);
static N_INLINE(NI32*, get__test95api95codec_u9660)(tyObject_Option__pvvSnZeKH2zYR1ucaskI2Q* self_p0);
static N_INLINE(NIM_BOOL, isNone__test95api95codec_u9668)(tyObject_Option__pvvSnZeKH2zYR1ucaskI2Q self_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, write__test95api95codec_u2126)(tyObject_CborWriter__xEBM3Te82WVh9bEvuN4TCDA* w_p0, NU8 val_p1);
N_LIB_PRIVATE N_NIMCALL(tyEnum_CborValueKind__wziIkCT08cTZ71gMnjCCkw, cborKind__pkgZcbor95serializationZparser_u909)(tyObject_CborParser__IDniep5pczeSdSoPTCW49bA* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, reset__test95api95codec_u9824)(tyObject_Option__pvvSnZeKH2zYR1ucaskI2Q* obj_p0);
N_LIB_PRIVATE N_NIMCALL(NU8, parseSimpleValue__test95api95codec_u2273)(tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw* r_p0);
static N_INLINE(tyObject_Option__pvvSnZeKH2zYR1ucaskI2Q, some__test95api95codec_u9866)(NI32 val_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NI32, readValue__test95api95codec_u6395)(tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw* reader_p0);
static N_INLINE(NIM_BOOL, isSome__test95api95codec_u24128)(tyObject_Option__6YPMiqKtxsl9cNAxTGMCGRw self_p0);
N_LIB_PRIVATE N_NIMCALL(void, write__test95api95codec_u2460)(tyObject_CborWriter__xEBM3Te82WVh9bEvuN4TCDA* w_p0, NIM_CHAR* val_p1, NI val_p1Len_0);
static N_INLINE(NimStringV2*, get__test95api95codec_u24279)(tyObject_Option__6YPMiqKtxsl9cNAxTGMCGRw* self_p0);
static N_INLINE(NIM_BOOL, isNone__test95api95codec_u24287)(tyObject_Option__6YPMiqKtxsl9cNAxTGMCGRw self_p0);
N_LIB_PRIVATE N_NIMCALL(void, reset__test95api95codec_u24721)(tyObject_Option__6YPMiqKtxsl9cNAxTGMCGRw* obj_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___test95api95codec_u23979)(tyObject_Option__6YPMiqKtxsl9cNAxTGMCGRw* dest_p0, tyObject_Option__6YPMiqKtxsl9cNAxTGMCGRw src_p1);
static N_INLINE(tyObject_Option__6YPMiqKtxsl9cNAxTGMCGRw, some__test95api95codec_u24009)(NimStringV2 val_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readValue__test95api95codec_u5918)(tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw* reader_p0);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95api95codec_u23970)(tyObject_Option__6YPMiqKtxsl9cNAxTGMCGRw* dest_p0);
static N_INLINE(NIM_BOOL, isSome__test95api95codec_u28035)(tyObject_Option__dzYlIYYfBcOnary9bSUvnEw* self_p0);
N_LIB_PRIVATE N_NIMCALL(void, write__test95api95codec_u5035)(tyObject_CborWriter__xEBM3Te82WVh9bEvuN4TCDA* w_p0, tyObject_Player__9byiOJu6V6reRS1OaIqhosA* value_p1);
static N_INLINE(tyObject_Player__9byiOJu6V6reRS1OaIqhosA*, get__test95api95codec_u28162)(tyObject_Option__dzYlIYYfBcOnary9bSUvnEw* self_p0);
static N_INLINE(NIM_BOOL, isNone__test95api95codec_u28170)(tyObject_Option__dzYlIYYfBcOnary9bSUvnEw* self_p0);
N_LIB_PRIVATE N_NIMCALL(void, reset__test95api95codec_u28550)(tyObject_Option__dzYlIYYfBcOnary9bSUvnEw* obj_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___test95api95codec_u27898)(tyObject_Option__dzYlIYYfBcOnary9bSUvnEw* dest_p0, tyObject_Option__dzYlIYYfBcOnary9bSUvnEw* src_p1);
static N_INLINE(void, some__test95api95codec_u27880)(tyObject_Player__9byiOJu6V6reRS1OaIqhosA* val_p0, tyObject_Option__dzYlIYYfBcOnary9bSUvnEw* Result);
N_LIB_PRIVATE N_NIMCALL(void, readValue__test95api95codec_u28567)(tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw* reader_p0, tyObject_Player__9byiOJu6V6reRS1OaIqhosA* Result);
static N_INLINE(NIM_BOOL, isSome__test95api95codec_u31368)(tyObject_Option__p3Fp2wt7a9bxd3AbI5df7WA self_p0);
N_LIB_PRIVATE N_NIMCALL(void, write__test95api95codec_u31511)(tyObject_CborWriter__xEBM3Te82WVh9bEvuN4TCDA* w_p0, tyObject_CborUnit__kgU055IFf9aZaWkN089aQR9aA value_p1);
static N_INLINE(tyObject_CborUnit__kgU055IFf9aZaWkN089aQR9aA*, get__test95api95codec_u31495)(tyObject_Option__p3Fp2wt7a9bxd3AbI5df7WA* self_p0);
static N_INLINE(NIM_BOOL, isNone__test95api95codec_u31503)(tyObject_Option__p3Fp2wt7a9bxd3AbI5df7WA self_p0);
N_LIB_PRIVATE N_NIMCALL(void, reset__test95api95codec_u31907)(tyObject_Option__p3Fp2wt7a9bxd3AbI5df7WA* obj_p0);
static N_INLINE(tyObject_Option__p3Fp2wt7a9bxd3AbI5df7WA, some__test95api95codec_u31166)(tyObject_CborUnit__kgU055IFf9aZaWkN089aQR9aA val_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_CborUnit__kgU055IFf9aZaWkN089aQR9aA, readValue__test95api95codec_u31924)(tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw* reader_p0);
extern TNimTypeV2 NTIv2__9boKnUzzlKIwZ8YT0xflFwg_;
static const struct {
  NI cap; NIM_CHAR data[34+1];
} TM__IJ2gDy9bOIla2kgqdNePUvQ_2 = { 34 | NIM_STRLIT_FLAG, "Can\'t obtain a value from a `none`" };
static const NimStringV2 TM__IJ2gDy9bOIla2kgqdNePUvQ_3 = {34, (NimStrPayload*)&TM__IJ2gDy9bOIla2kgqdNePUvQ_2};
static const NimStringV2 TM__IJ2gDy9bOIla2kgqdNePUvQ_4 = {34, (NimStrPayload*)&TM__IJ2gDy9bOIla2kgqdNePUvQ_2};
static const NimStringV2 TM__IJ2gDy9bOIla2kgqdNePUvQ_5 = {34, (NimStrPayload*)&TM__IJ2gDy9bOIla2kgqdNePUvQ_2};
static const NimStringV2 TM__IJ2gDy9bOIla2kgqdNePUvQ_6 = {34, (NimStrPayload*)&TM__IJ2gDy9bOIla2kgqdNePUvQ_2};
extern NIM_THREADVAR TFrame* framePtr__system_u2723;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4491;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2723;
	framePtr__system_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2723 = (*framePtr__system_u2723).prev;
}
static N_INLINE(NIM_BOOL, isSome__test95api95codec_u9633)(tyObject_Option__pvvSnZeKH2zYR1ucaskI2Q self_p0) {
	NIM_BOOL result;
	nimfr_("isSome", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");
	nimlf_(162, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");	result = self_p0.has;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, isNone__test95api95codec_u9668)(tyObject_Option__pvvSnZeKH2zYR1ucaskI2Q self_p0) {
	NIM_BOOL result;
	nimfr_("isNone", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");
	nimln_(177);	nimln_(189);	result = !(self_p0.has);
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4491);
	return result;
}
static N_INLINE(NI32*, get__test95api95codec_u9660)(tyObject_Option__pvvSnZeKH2zYR1ucaskI2Q* self_p0) {
	NI32* result;
NIM_BOOL* nimErr_;
	nimfr_("get", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");
{nimErr_ = nimErrorFlag();
	result = (NI32*)0;
	nimln_(202);	{
		NIM_BOOL T3_;
		tyObject_UnpackDefect__9boKnUzzlKIwZ8YT0xflFwg* T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = isNone__test95api95codec_u9668((*self_p0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		T6_ = NIM_NIL;
		T6_ = (tyObject_UnpackDefect__9boKnUzzlKIwZ8YT0xflFwg*) nimNewObj(sizeof(tyObject_UnpackDefect__9boKnUzzlKIwZ8YT0xflFwg), NIM_ALIGNOF(tyObject_UnpackDefect__9boKnUzzlKIwZ8YT0xflFwg));
		(*T6_).Sup.Sup.Sup.m_type = (&NTIv2__9boKnUzzlKIwZ8YT0xflFwg_);
		(*T6_).Sup.Sup.name = "UnpackDefect";
		(*T6_).Sup.Sup.message = TM__IJ2gDy9bOIla2kgqdNePUvQ_3;
		(*T6_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(203);		raiseExceptionEx((Exception*)T6_, "UnpackDefect", "get", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim", 203);
goto BeforeRet_;
	}
LA4_: ;
	nimln_(204);	result = (&(*self_p0).val);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, write__test95api95codec_u9624)(tyObject_CborWriter__xEBM3Te82WVh9bEvuN4TCDA* writer_p0, tyObject_Option__pvvSnZeKH2zYR1ucaskI2Q value_p1) {
NIM_BOOL* nimErr_;
	nimfr_("write", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/cbor_serialization-0.3.0-ab126eae09a6e39c72972a6a0b83cb06a2ffe8f0/cbor_serialization/std/options.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(21, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/cbor_serialization-0.3.0-ab126eae09a6e39c72972a6a0b83cb06a2ffe8f0/cbor_serialization/std/options.nim");	{
		NIM_BOOL T3_;
		NI32* T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = isSome__test95api95codec_u9633(value_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		nimln_(22);		T6_ = (NI32*)0;
		T6_ = get__test95api95codec_u9660((&value_p1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		write__test95api95codec_u218(writer_p0, (*T6_));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA4_: ;
	{
		nimln_(24);		write__test95api95codec_u2126(writer_p0, ((NU8)22));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(tyObject_Option__pvvSnZeKH2zYR1ucaskI2Q, some__test95api95codec_u9866)(NI32 val_p0) {
	tyObject_Option__pvvSnZeKH2zYR1ucaskI2Q result;
	nimfr_("some", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_Option__pvvSnZeKH2zYR1ucaskI2Q));
	nimlf_(142, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");	result.has = NIM_TRUE;
	result.val = val_p0;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, read__test95api95codec_u9814)(tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw* reader_p0, tyObject_Option__pvvSnZeKH2zYR1ucaskI2Q* value_p1) {
NIM_BOOL* nimErr_;
	nimfr_("read", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/cbor_serialization-0.3.0-ab126eae09a6e39c72972a6a0b83cb06a2ffe8f0/cbor_serialization/std/options.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(31, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/cbor_serialization-0.3.0-ab126eae09a6e39c72972a6a0b83cb06a2ffe8f0/cbor_serialization/std/options.nim");	{
		tyEnum_CborValueKind__wziIkCT08cTZ71gMnjCCkw T3_;
		NU8 T6_;
		T3_ = (tyEnum_CborValueKind__wziIkCT08cTZ71gMnjCCkw)0;
		T3_ = cborKind__pkgZcbor95serializationZparser_u909((&(*reader_p0).parser));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!(T3_ == ((tyEnum_CborValueKind__wziIkCT08cTZ71gMnjCCkw)10) || T3_ == ((tyEnum_CborValueKind__wziIkCT08cTZ71gMnjCCkw)11))) goto LA4_;
		nimln_(32);		reset__test95api95codec_u9824(value_p1);
		nimln_(33);		T6_ = (NU8)0;
		T6_ = parseSimpleValue__test95api95codec_u2273(reader_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(void)(T6_);
	}
	goto LA1_;
LA4_: ;
	{
		NI32 T8_;
		tyObject_Option__pvvSnZeKH2zYR1ucaskI2Q T9_;
		nimln_(35);		T8_ = (NI32)0;
		T8_ = readValue__test95api95codec_u6395(reader_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimZeroMem((void*)(&T9_), sizeof(tyObject_Option__pvvSnZeKH2zYR1ucaskI2Q));
		T9_ = some__test95api95codec_u9866(T8_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*value_p1) = T9_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NIM_BOOL, isSome__test95api95codec_u24128)(tyObject_Option__6YPMiqKtxsl9cNAxTGMCGRw self_p0) {
	NIM_BOOL result;
	nimfr_("isSome", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");
	nimlf_(162, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");	result = self_p0.has;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, isNone__test95api95codec_u24287)(tyObject_Option__6YPMiqKtxsl9cNAxTGMCGRw self_p0) {
	NIM_BOOL result;
	nimfr_("isNone", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");
	nimln_(177);	nimln_(189);	result = !(self_p0.has);
	popFrame();
	return result;
}
static N_INLINE(NimStringV2*, get__test95api95codec_u24279)(tyObject_Option__6YPMiqKtxsl9cNAxTGMCGRw* self_p0) {
	NimStringV2* result;
NIM_BOOL* nimErr_;
	nimfr_("get", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");
{nimErr_ = nimErrorFlag();
	result = (NimStringV2*)0;
	nimln_(202);	{
		NIM_BOOL T3_;
		tyObject_UnpackDefect__9boKnUzzlKIwZ8YT0xflFwg* T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = isNone__test95api95codec_u24287((*self_p0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		T6_ = NIM_NIL;
		T6_ = (tyObject_UnpackDefect__9boKnUzzlKIwZ8YT0xflFwg*) nimNewObj(sizeof(tyObject_UnpackDefect__9boKnUzzlKIwZ8YT0xflFwg), NIM_ALIGNOF(tyObject_UnpackDefect__9boKnUzzlKIwZ8YT0xflFwg));
		(*T6_).Sup.Sup.Sup.m_type = (&NTIv2__9boKnUzzlKIwZ8YT0xflFwg_);
		(*T6_).Sup.Sup.name = "UnpackDefect";
		(*T6_).Sup.Sup.message = TM__IJ2gDy9bOIla2kgqdNePUvQ_4;
		(*T6_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(203);		raiseExceptionEx((Exception*)T6_, "UnpackDefect", "get", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim", 203);
goto BeforeRet_;
	}
LA4_: ;
	nimln_(204);	result = (&(*self_p0).val);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, write__test95api95codec_u24245)(tyObject_CborWriter__xEBM3Te82WVh9bEvuN4TCDA* writer_p0, tyObject_Option__6YPMiqKtxsl9cNAxTGMCGRw value_p1) {
NIM_BOOL* nimErr_;
	nimfr_("write", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/cbor_serialization-0.3.0-ab126eae09a6e39c72972a6a0b83cb06a2ffe8f0/cbor_serialization/std/options.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(21, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/cbor_serialization-0.3.0-ab126eae09a6e39c72972a6a0b83cb06a2ffe8f0/cbor_serialization/std/options.nim");	{
		NIM_BOOL T3_;
		NimStringV2* T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = isSome__test95api95codec_u24128(value_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		nimln_(22);		T6_ = (NimStringV2*)0;
		T6_ = get__test95api95codec_u24279((&value_p1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		write__test95api95codec_u2460(writer_p0, (((*T6_)).p) ? ((*T6_).p->data) : NIM_NIL, (*T6_).len);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA4_: ;
	{
		nimln_(24);		write__test95api95codec_u2126(writer_p0, ((NU8)22));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(tyObject_Option__6YPMiqKtxsl9cNAxTGMCGRw, some__test95api95codec_u24009)(NimStringV2 val_p0) {
	tyObject_Option__6YPMiqKtxsl9cNAxTGMCGRw result;
	NimStringV2 blitTmp_1;
	nimfr_("some", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_Option__6YPMiqKtxsl9cNAxTGMCGRw));
	nimlf_(142, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");	result.has = NIM_TRUE;
	blitTmp_1 = val_p0;
	result.val = blitTmp_1;
	popFrame();
	return result;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
	nimfr_("=destroy", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, read__test95api95codec_u24712)(tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw* reader_p0, tyObject_Option__6YPMiqKtxsl9cNAxTGMCGRw* value_p1) {
NIM_BOOL* nimErr_;
	nimfr_("read", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/cbor_serialization-0.3.0-ab126eae09a6e39c72972a6a0b83cb06a2ffe8f0/cbor_serialization/std/options.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(31, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/cbor_serialization-0.3.0-ab126eae09a6e39c72972a6a0b83cb06a2ffe8f0/cbor_serialization/std/options.nim");	{
		tyEnum_CborValueKind__wziIkCT08cTZ71gMnjCCkw T3_;
		NU8 T6_;
		T3_ = (tyEnum_CborValueKind__wziIkCT08cTZ71gMnjCCkw)0;
		T3_ = cborKind__pkgZcbor95serializationZparser_u909((&(*reader_p0).parser));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!(T3_ == ((tyEnum_CborValueKind__wziIkCT08cTZ71gMnjCCkw)10) || T3_ == ((tyEnum_CborValueKind__wziIkCT08cTZ71gMnjCCkw)11))) goto LA4_;
		nimln_(32);		reset__test95api95codec_u24721(value_p1);
		nimln_(33);		T6_ = (NU8)0;
		T6_ = parseSimpleValue__test95api95codec_u2273(reader_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(void)(T6_);
	}
	goto LA1_;
LA4_: ;
	{
		NimStringV2 T8_;
		tyObject_Option__6YPMiqKtxsl9cNAxTGMCGRw T9_;
		nimlf_(155, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");		nimlf_(35, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/cbor_serialization-0.3.0-ab126eae09a6e39c72972a6a0b83cb06a2ffe8f0/cbor_serialization/std/options.nim");		T8_.len = 0; T8_.p = NIM_NIL;
		T8_ = readValue__test95api95codec_u5918(reader_p0);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T8_); goto BeforeRet_;}
		T9_ = some__test95api95codec_u24009(T8_);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___test95api95codec_u23970(&T9_); goto BeforeRet_;}
		nimlf_(155, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");		eqsink___test95api95codec_u23979((&(*value_p1)), T9_);
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NIM_BOOL, isSome__test95api95codec_u28035)(tyObject_Option__dzYlIYYfBcOnary9bSUvnEw* self_p0) {
	NIM_BOOL result;
	nimfr_("isSome", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");
	nimln_(162);	result = (*self_p0).has;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, isNone__test95api95codec_u28170)(tyObject_Option__dzYlIYYfBcOnary9bSUvnEw* self_p0) {
	NIM_BOOL result;
	nimfr_("isNone", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");
	nimln_(177);	nimln_(189);	result = !((*self_p0).has);
	popFrame();
	return result;
}
static N_INLINE(tyObject_Player__9byiOJu6V6reRS1OaIqhosA*, get__test95api95codec_u28162)(tyObject_Option__dzYlIYYfBcOnary9bSUvnEw* self_p0) {
	tyObject_Player__9byiOJu6V6reRS1OaIqhosA* result;
NIM_BOOL* nimErr_;
	nimfr_("get", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");
{nimErr_ = nimErrorFlag();
	result = (tyObject_Player__9byiOJu6V6reRS1OaIqhosA*)0;
	nimln_(202);	{
		NIM_BOOL T3_;
		tyObject_UnpackDefect__9boKnUzzlKIwZ8YT0xflFwg* T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = isNone__test95api95codec_u28170(self_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		T6_ = NIM_NIL;
		T6_ = (tyObject_UnpackDefect__9boKnUzzlKIwZ8YT0xflFwg*) nimNewObj(sizeof(tyObject_UnpackDefect__9boKnUzzlKIwZ8YT0xflFwg), NIM_ALIGNOF(tyObject_UnpackDefect__9boKnUzzlKIwZ8YT0xflFwg));
		(*T6_).Sup.Sup.Sup.m_type = (&NTIv2__9boKnUzzlKIwZ8YT0xflFwg_);
		(*T6_).Sup.Sup.name = "UnpackDefect";
		(*T6_).Sup.Sup.message = TM__IJ2gDy9bOIla2kgqdNePUvQ_5;
		(*T6_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(203);		raiseExceptionEx((Exception*)T6_, "UnpackDefect", "get", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim", 203);
goto BeforeRet_;
	}
LA4_: ;
	nimln_(204);	result = (&(*self_p0).val);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, write__test95api95codec_u28128)(tyObject_CborWriter__xEBM3Te82WVh9bEvuN4TCDA* writer_p0, tyObject_Option__dzYlIYYfBcOnary9bSUvnEw* value_p1) {
NIM_BOOL* nimErr_;
	nimfr_("write", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/cbor_serialization-0.3.0-ab126eae09a6e39c72972a6a0b83cb06a2ffe8f0/cbor_serialization/std/options.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(21, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/cbor_serialization-0.3.0-ab126eae09a6e39c72972a6a0b83cb06a2ffe8f0/cbor_serialization/std/options.nim");	{
		NIM_BOOL T3_;
		tyObject_Player__9byiOJu6V6reRS1OaIqhosA* T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = isSome__test95api95codec_u28035(value_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		nimln_(22);		T6_ = (tyObject_Player__9byiOJu6V6reRS1OaIqhosA*)0;
		T6_ = get__test95api95codec_u28162(value_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		write__test95api95codec_u5035(writer_p0, (&(*T6_)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA4_: ;
	{
		nimln_(24);		write__test95api95codec_u2126(writer_p0, ((NU8)22));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, some__test95api95codec_u27880)(tyObject_Player__9byiOJu6V6reRS1OaIqhosA* val_p0, tyObject_Option__dzYlIYYfBcOnary9bSUvnEw* Result) {
	tyObject_Player__9byiOJu6V6reRS1OaIqhosA blitTmp_1;
	nimfr_("some", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");
	nimZeroMem((void*)Result, sizeof(tyObject_Option__dzYlIYYfBcOnary9bSUvnEw));
	nimlf_(142, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");	(*Result).has = NIM_TRUE;
	nimZeroMem((void*)(&blitTmp_1), sizeof(tyObject_Player__9byiOJu6V6reRS1OaIqhosA));
	blitTmp_1 = (*val_p0);
	(*Result).val = blitTmp_1;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, read__test95api95codec_u28541)(tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw* reader_p0, tyObject_Option__dzYlIYYfBcOnary9bSUvnEw* value_p1) {
NIM_BOOL* nimErr_;
	nimfr_("read", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/cbor_serialization-0.3.0-ab126eae09a6e39c72972a6a0b83cb06a2ffe8f0/cbor_serialization/std/options.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(31, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/cbor_serialization-0.3.0-ab126eae09a6e39c72972a6a0b83cb06a2ffe8f0/cbor_serialization/std/options.nim");	{
		tyEnum_CborValueKind__wziIkCT08cTZ71gMnjCCkw T3_;
		NU8 T6_;
		T3_ = (tyEnum_CborValueKind__wziIkCT08cTZ71gMnjCCkw)0;
		T3_ = cborKind__pkgZcbor95serializationZparser_u909((&(*reader_p0).parser));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!(T3_ == ((tyEnum_CborValueKind__wziIkCT08cTZ71gMnjCCkw)10) || T3_ == ((tyEnum_CborValueKind__wziIkCT08cTZ71gMnjCCkw)11))) goto LA4_;
		nimln_(32);		reset__test95api95codec_u28550(value_p1);
		nimln_(33);		T6_ = (NU8)0;
		T6_ = parseSimpleValue__test95api95codec_u2273(reader_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(void)(T6_);
	}
	goto LA1_;
LA4_: ;
	{
		tyObject_Player__9byiOJu6V6reRS1OaIqhosA T8_;
		tyObject_Option__dzYlIYYfBcOnary9bSUvnEw T9_;
		nimlf_(142, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");		nimlf_(35, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/cbor_serialization-0.3.0-ab126eae09a6e39c72972a6a0b83cb06a2ffe8f0/cbor_serialization/std/options.nim");		nimZeroMem((void*)(&T8_), sizeof(tyObject_Player__9byiOJu6V6reRS1OaIqhosA));
		readValue__test95api95codec_u28567(reader_p0, (&T8_));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimZeroMem((void*)(&T9_), sizeof(tyObject_Option__dzYlIYYfBcOnary9bSUvnEw));
		some__test95api95codec_u27880((&T8_), (&T9_));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(142, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");		eqsink___test95api95codec_u27898((&(*value_p1)), (&T9_));
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NIM_BOOL, isSome__test95api95codec_u31368)(tyObject_Option__p3Fp2wt7a9bxd3AbI5df7WA self_p0) {
	NIM_BOOL result;
	nimfr_("isSome", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");
	nimln_(162);	result = self_p0.has;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, isNone__test95api95codec_u31503)(tyObject_Option__p3Fp2wt7a9bxd3AbI5df7WA self_p0) {
	NIM_BOOL result;
	nimfr_("isNone", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");
	nimln_(177);	nimln_(189);	result = !(self_p0.has);
	popFrame();
	return result;
}
static N_INLINE(tyObject_CborUnit__kgU055IFf9aZaWkN089aQR9aA*, get__test95api95codec_u31495)(tyObject_Option__p3Fp2wt7a9bxd3AbI5df7WA* self_p0) {
	tyObject_CborUnit__kgU055IFf9aZaWkN089aQR9aA* result;
NIM_BOOL* nimErr_;
	nimfr_("get", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");
{nimErr_ = nimErrorFlag();
	result = (tyObject_CborUnit__kgU055IFf9aZaWkN089aQR9aA*)0;
	nimln_(202);	{
		NIM_BOOL T3_;
		tyObject_UnpackDefect__9boKnUzzlKIwZ8YT0xflFwg* T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = isNone__test95api95codec_u31503((*self_p0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		T6_ = NIM_NIL;
		T6_ = (tyObject_UnpackDefect__9boKnUzzlKIwZ8YT0xflFwg*) nimNewObj(sizeof(tyObject_UnpackDefect__9boKnUzzlKIwZ8YT0xflFwg), NIM_ALIGNOF(tyObject_UnpackDefect__9boKnUzzlKIwZ8YT0xflFwg));
		(*T6_).Sup.Sup.Sup.m_type = (&NTIv2__9boKnUzzlKIwZ8YT0xflFwg_);
		(*T6_).Sup.Sup.name = "UnpackDefect";
		(*T6_).Sup.Sup.message = TM__IJ2gDy9bOIla2kgqdNePUvQ_6;
		(*T6_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(203);		raiseExceptionEx((Exception*)T6_, "UnpackDefect", "get", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim", 203);
goto BeforeRet_;
	}
LA4_: ;
	nimln_(204);	result = (&(*self_p0).val);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, write__test95api95codec_u31461)(tyObject_CborWriter__xEBM3Te82WVh9bEvuN4TCDA* writer_p0, tyObject_Option__p3Fp2wt7a9bxd3AbI5df7WA value_p1) {
NIM_BOOL* nimErr_;
	nimfr_("write", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/cbor_serialization-0.3.0-ab126eae09a6e39c72972a6a0b83cb06a2ffe8f0/cbor_serialization/std/options.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(21, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/cbor_serialization-0.3.0-ab126eae09a6e39c72972a6a0b83cb06a2ffe8f0/cbor_serialization/std/options.nim");	{
		NIM_BOOL T3_;
		tyObject_CborUnit__kgU055IFf9aZaWkN089aQR9aA* T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = isSome__test95api95codec_u31368(value_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		nimln_(22);		T6_ = (tyObject_CborUnit__kgU055IFf9aZaWkN089aQR9aA*)0;
		T6_ = get__test95api95codec_u31495((&value_p1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		write__test95api95codec_u31511(writer_p0, (*T6_));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA4_: ;
	{
		nimln_(24);		write__test95api95codec_u2126(writer_p0, ((NU8)22));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(tyObject_Option__p3Fp2wt7a9bxd3AbI5df7WA, some__test95api95codec_u31166)(tyObject_CborUnit__kgU055IFf9aZaWkN089aQR9aA val_p0) {
	tyObject_Option__p3Fp2wt7a9bxd3AbI5df7WA result;
	nimfr_("some", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_Option__p3Fp2wt7a9bxd3AbI5df7WA));
	nimlf_(142, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim");	result.has = NIM_TRUE;
	result.val = val_p0;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, read__test95api95codec_u31898)(tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw* reader_p0, tyObject_Option__p3Fp2wt7a9bxd3AbI5df7WA* value_p1) {
NIM_BOOL* nimErr_;
	nimfr_("read", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/cbor_serialization-0.3.0-ab126eae09a6e39c72972a6a0b83cb06a2ffe8f0/cbor_serialization/std/options.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(31, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/cbor_serialization-0.3.0-ab126eae09a6e39c72972a6a0b83cb06a2ffe8f0/cbor_serialization/std/options.nim");	{
		tyEnum_CborValueKind__wziIkCT08cTZ71gMnjCCkw T3_;
		NU8 T6_;
		T3_ = (tyEnum_CborValueKind__wziIkCT08cTZ71gMnjCCkw)0;
		T3_ = cborKind__pkgZcbor95serializationZparser_u909((&(*reader_p0).parser));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!(T3_ == ((tyEnum_CborValueKind__wziIkCT08cTZ71gMnjCCkw)10) || T3_ == ((tyEnum_CborValueKind__wziIkCT08cTZ71gMnjCCkw)11))) goto LA4_;
		nimln_(32);		reset__test95api95codec_u31907(value_p1);
		nimln_(33);		T6_ = (NU8)0;
		T6_ = parseSimpleValue__test95api95codec_u2273(reader_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(void)(T6_);
	}
	goto LA1_;
LA4_: ;
	{
		tyObject_CborUnit__kgU055IFf9aZaWkN089aQR9aA T8_;
		tyObject_Option__p3Fp2wt7a9bxd3AbI5df7WA T9_;
		nimln_(35);		T8_ = readValue__test95api95codec_u31924(reader_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimZeroMem((void*)(&T9_), sizeof(tyObject_Option__p3Fp2wt7a9bxd3AbI5df7WA));
		T9_ = some__test95api95codec_u31166(T8_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*value_p1) = T9_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
