/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c -w -ferror-limit=3 -pthread --coverage -O0 -g   -I/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib -I/Users/schwarzy/dev/status/nim-brokers/test/typemappingtestlib -o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_typemappingtestlib/@m..@s..@sbrokers@sinternal@sapi_cbor_descriptor.nim.c.o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_typemappingtestlib/@m..@s..@sbrokers@sinternal@sapi_cbor_descriptor.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_ApiList__N00lzPe3dwihCpxBcKgV0A tyObject_ApiList__N00lzPe3dwihCpxBcKgV0A;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw;
typedef struct tyObject_OrderedTable__hZyYhH6CvUHU9cEVLp9agatA tyObject_OrderedTable__hZyYhH6CvUHU9cEVLp9agatA;
typedef struct tySequence__5YRVByHdKFa72AAJfXUXjQ tySequence__5YRVByHdKFa72AAJfXUXjQ;
typedef struct tySequence__5YRVByHdKFa72AAJfXUXjQ_Content tySequence__5YRVByHdKFa72AAJfXUXjQ_Content;
typedef struct tySequence__9bdcSarWORsi4cOqRdIOOXQ tySequence__9bdcSarWORsi4cOqRdIOOXQ;
typedef struct tySequence__9bdcSarWORsi4cOqRdIOOXQ_Content tySequence__9bdcSarWORsi4cOqRdIOOXQ_Content;
typedef struct tyTuple__ekdACjJFcmcbOGuV0hdwVg tyTuple__ekdACjJFcmcbOGuV0hdwVg;
typedef struct tyObject_LibraryDescriptor__QvDjwGu3delxSFSwZO5eMA tyObject_LibraryDescriptor__QvDjwGu3delxSFSwZO5eMA;
typedef struct tySequence__tJlMjm9cU6lRR9cy1OOInnuw tySequence__tJlMjm9cU6lRR9cy1OOInnuw;
typedef struct tySequence__tJlMjm9cU6lRR9cy1OOInnuw_Content tySequence__tJlMjm9cU6lRR9cy1OOInnuw_Content;
typedef struct tySequence__2SBu9aV86IFAxsC5ppelRjw tySequence__2SBu9aV86IFAxsC5ppelRjw;
typedef struct tySequence__2SBu9aV86IFAxsC5ppelRjw_Content tySequence__2SBu9aV86IFAxsC5ppelRjw_Content;
typedef struct tySequence__FIas0Yj0j3UPajfxGZPIIQ tySequence__FIas0Yj0j3UPajfxGZPIIQ;
typedef struct tySequence__FIas0Yj0j3UPajfxGZPIIQ_Content tySequence__FIas0Yj0j3UPajfxGZPIIQ_Content;
typedef struct tyObject_ApiRequestInfo__ehCYMbx4h5K2onwe9bfcUFQ tyObject_ApiRequestInfo__ehCYMbx4h5K2onwe9bfcUFQ;
typedef struct tySequence__mK9atymt9bnUW3uKIG1KeiTA tySequence__mK9atymt9bnUW3uKIG1KeiTA;
typedef struct tySequence__mK9atymt9bnUW3uKIG1KeiTA_Content tySequence__mK9atymt9bnUW3uKIG1KeiTA_Content;
typedef struct tyObject_ApiFieldInfo__zZUT3CKatIAo9cOD0Bx0KxA tyObject_ApiFieldInfo__zZUT3CKatIAo9cOD0Bx0KxA;
typedef struct tyObject_ApiEventInfo__9b7mI9aFH6Y7VBlPwkLzaJEA tyObject_ApiEventInfo__9b7mI9aFH6Y7VBlPwkLzaJEA;
typedef struct tyObject_ApiTypeInfo__GhTFYIpPViKs4WGR6UUHhQ tyObject_ApiTypeInfo__GhTFYIpPViKs4WGR6UUHhQ;
typedef struct tySequence__9bF3b2qSHKSvvCHOrjrjRGA tySequence__9bF3b2qSHKSvvCHOrjrjRGA;
typedef struct tySequence__9bF3b2qSHKSvvCHOrjrjRGA_Content tySequence__9bF3b2qSHKSvvCHOrjrjRGA_Content;
typedef struct tyObject_ApiEnumValueInfo__UtUmVKLQogO7tmILqu6HaA tyObject_ApiEnumValueInfo__UtUmVKLQogO7tmILqu6HaA;
typedef struct tyTuple__6BCBbAPQluFlKPrrAWiDng tyTuple__6BCBbAPQluFlKPrrAWiDng;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyObject_ApiList__N00lzPe3dwihCpxBcKgV0A {
	NimStringV2 libName;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ requests;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ events;
};
typedef NU8 tyEnum_JsonNodeKind__Fnu9aJYjpd15z1gCnQKswxA;
struct tySequence__5YRVByHdKFa72AAJfXUXjQ {
  NI len; tySequence__5YRVByHdKFa72AAJfXUXjQ_Content* p;
};
struct tyObject_OrderedTable__hZyYhH6CvUHU9cEVLp9agatA {
	tySequence__5YRVByHdKFa72AAJfXUXjQ data;
	NI counter;
	NI first;
	NI last;
};
struct tySequence__9bdcSarWORsi4cOqRdIOOXQ {
  NI len; tySequence__9bdcSarWORsi4cOqRdIOOXQ_Content* p;
};
struct tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw {
	NIM_BOOL isUnquoted;
	tyEnum_JsonNodeKind__Fnu9aJYjpd15z1gCnQKswxA kind;
union{
	struct {
	NimStringV2 str;
} _kind_1;
	struct {
	NI64 num;
} _kind_2;
	struct {
	NF fnum;
} _kind_3;
	struct {
	NIM_BOOL bval;
} _kind_4;
	struct {
	tyObject_OrderedTable__hZyYhH6CvUHU9cEVLp9agatA fields;
} _kind_6;
	struct {
	tySequence__9bdcSarWORsi4cOqRdIOOXQ elems;
} _kind_7;
};
};
struct tyTuple__ekdACjJFcmcbOGuV0hdwVg {
	NimStringV2 Field0;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* Field1;
};
typedef tyTuple__ekdACjJFcmcbOGuV0hdwVg tyArray__i7SIYz7cZQZPEf2k1h169ag[3];
struct tySequence__tJlMjm9cU6lRR9cy1OOInnuw {
  NI len; tySequence__tJlMjm9cU6lRR9cy1OOInnuw_Content* p;
};
struct tySequence__2SBu9aV86IFAxsC5ppelRjw {
  NI len; tySequence__2SBu9aV86IFAxsC5ppelRjw_Content* p;
};
struct tySequence__FIas0Yj0j3UPajfxGZPIIQ {
  NI len; tySequence__FIas0Yj0j3UPajfxGZPIIQ_Content* p;
};
struct tyObject_LibraryDescriptor__QvDjwGu3delxSFSwZO5eMA {
	NimStringV2 libName;
	NimStringV2 cddl;
	tySequence__tJlMjm9cU6lRR9cy1OOInnuw requests;
	tySequence__2SBu9aV86IFAxsC5ppelRjw events;
	tySequence__FIas0Yj0j3UPajfxGZPIIQ types;
};
struct tySequence__mK9atymt9bnUW3uKIG1KeiTA {
  NI len; tySequence__mK9atymt9bnUW3uKIG1KeiTA_Content* p;
};
struct tyObject_ApiRequestInfo__ehCYMbx4h5K2onwe9bfcUFQ {
	NimStringV2 apiName;
	NimStringV2 argsType;
	tySequence__mK9atymt9bnUW3uKIG1KeiTA argFields;
	NimStringV2 responseType;
};
struct tyObject_ApiFieldInfo__zZUT3CKatIAo9cOD0Bx0KxA {
	NimStringV2 name;
	NimStringV2 nimType;
};
struct tyObject_ApiEventInfo__9b7mI9aFH6Y7VBlPwkLzaJEA {
	NimStringV2 apiName;
	NimStringV2 payloadType;
};
struct tySequence__9bF3b2qSHKSvvCHOrjrjRGA {
  NI len; tySequence__9bF3b2qSHKSvvCHOrjrjRGA_Content* p;
};
struct tyObject_ApiTypeInfo__GhTFYIpPViKs4WGR6UUHhQ {
	NimStringV2 name;
	NimStringV2 kind;
	tySequence__mK9atymt9bnUW3uKIG1KeiTA fields;
	tySequence__9bF3b2qSHKSvvCHOrjrjRGA enumValues;
	NimStringV2 underlyingType;
};
struct tyObject_ApiEnumValueInfo__UtUmVKLQogO7tmILqu6HaA {
	NimStringV2 name;
	NI ordinal;
};
typedef tyTuple__ekdACjJFcmcbOGuV0hdwVg tyArray__BC49ca8niQgi69aOLyubTa8Q[5];
typedef tyTuple__ekdACjJFcmcbOGuV0hdwVg tyArray__5atYQrfpRKpGPven8cNr1g[4];
typedef tyTuple__ekdACjJFcmcbOGuV0hdwVg tyArray__i9afe3LVVNlXrk60VmgiJZQ[2];
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tyTuple__6BCBbAPQluFlKPrrAWiDng {
	NI Field0;
	NI Field1;
	NimStringV2 Field2;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* Field3;
};
struct tySequence__5YRVByHdKFa72AAJfXUXjQ_Content { NI cap; tyTuple__6BCBbAPQluFlKPrrAWiDng data[SEQ_DECL_SIZE]; };
struct tySequence__9bdcSarWORsi4cOqRdIOOXQ_Content { NI cap; tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* data[SEQ_DECL_SIZE]; };
struct tySequence__tJlMjm9cU6lRR9cy1OOInnuw_Content { NI cap; tyObject_ApiRequestInfo__ehCYMbx4h5K2onwe9bfcUFQ data[SEQ_DECL_SIZE]; };
struct tySequence__2SBu9aV86IFAxsC5ppelRjw_Content { NI cap; tyObject_ApiEventInfo__9b7mI9aFH6Y7VBlPwkLzaJEA data[SEQ_DECL_SIZE]; };
struct tySequence__FIas0Yj0j3UPajfxGZPIIQ_Content { NI cap; tyObject_ApiTypeInfo__GhTFYIpPViKs4WGR6UUHhQ data[SEQ_DECL_SIZE]; };
struct tySequence__mK9atymt9bnUW3uKIG1KeiTA_Content { NI cap; tyObject_ApiFieldInfo__zZUT3CKatIAo9cOD0Bx0KxA data[SEQ_DECL_SIZE]; };
struct tySequence__9bF3b2qSHKSvvCHOrjrjRGA_Content { NI cap; tyObject_ApiEnumValueInfo__UtUmVKLQogO7tmILqu6HaA data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3851)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pureZjson_u4844)(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* node_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw*, toJson__OOZOOZbrokersZinternalZapi95cbor95descriptor_u679)(tyObject_ApiList__N00lzPe3dwihCpxBcKgV0A* a_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw*, percent___pureZjson_u2178)(tyTuple__ekdACjJFcmcbOGuV0hdwVg* keyVals_p0, NI keyVals_p0Len_0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw*, percent___pureZjson_u2149)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw*, percent___OOZOOZbrokersZinternalZapi95cbor95descriptor_u682)(NimStringV2* elements_p0, NI elements_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u321)(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* dest_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4709)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZbrokersZinternalZapi95cbor95descriptor_u865)(tySequence__tJlMjm9cU6lRR9cy1OOInnuw dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZbrokersZinternalZapi95cbor95descriptor_u280)(tySequence__mK9atymt9bnUW3uKIG1KeiTA dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZbrokersZinternalZapi95cbor95descriptor_u1036)(tySequence__2SBu9aV86IFAxsC5ppelRjw dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZbrokersZinternalZapi95cbor95descriptor_u1203)(tySequence__FIas0Yj0j3UPajfxGZPIIQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZbrokersZinternalZapi95cbor95descriptor_u447)(tySequence__9bF3b2qSHKSvvCHOrjrjRGA dest_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw*, toJson__OOZOOZbrokersZinternalZapi95cbor95descriptor_u754)(tyObject_LibraryDescriptor__QvDjwGu3delxSFSwZO5eMA* d_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw*, newJArray__pureZjson_u503)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__pureZjson_u647)(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* father_p0, tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* child_p1);
static N_INLINE(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw*, X5BX5D___pureZjson_u3473)(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* node_p0, NimStringV2 name_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u324)(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw** dest_p0, tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* src_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw**, X5BX5D___pureZjson_u3043)(tyObject_OrderedTable__hZyYhH6CvUHU9cEVLp9agatA* t_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pureZjson_u20)(tyEnum_JsonNodeKind__Fnu9aJYjpd15z1gCnQKswxA e_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldErrorStr)(NimStringV2 f_p0, NimStringV2 discVal_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw*, toJson__OOZOOZbrokersZinternalZapi95cbor95descriptor_u591)(tyObject_ApiRequestInfo__ehCYMbx4h5K2onwe9bfcUFQ* r_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw*, toJson__OOZOOZbrokersZinternalZapi95cbor95descriptor_u34)(tyObject_ApiFieldInfo__zZUT3CKatIAo9cOD0Bx0KxA* f_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw*, toJson__OOZOOZbrokersZinternalZapi95cbor95descriptor_u659)(tyObject_ApiEventInfo__9b7mI9aFH6Y7VBlPwkLzaJEA* e_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw*, toJson__OOZOOZbrokersZinternalZapi95cbor95descriptor_u148)(tyObject_ApiTypeInfo__GhTFYIpPViKs4WGR6UUHhQ* t_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw*, toJson__OOZOOZbrokersZinternalZapi95cbor95descriptor_u128)(tyObject_ApiEnumValueInfo__UtUmVKLQogO7tmILqu6HaA v_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw*, percent___pureZjson_u2159)(NI n_p0);
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__yzRo69c2o9bstRNsREZJujPQ_2 = { 7 | NIM_STRLIT_FLAG, "libName" };
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_3 = {7, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_2};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__yzRo69c2o9bstRNsREZJujPQ_4 = { 8 | NIM_STRLIT_FLAG, "requests" };
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_5 = {8, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_4};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__yzRo69c2o9bstRNsREZJujPQ_6 = { 6 | NIM_STRLIT_FLAG, "events" };
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_7 = {6, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_6};
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_8 = {7, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_2};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__yzRo69c2o9bstRNsREZJujPQ_9 = { 4 | NIM_STRLIT_FLAG, "cddl" };
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_10 = {4, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_9};
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_11 = {8, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_4};
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_12 = {6, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_6};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__yzRo69c2o9bstRNsREZJujPQ_13 = { 5 | NIM_STRLIT_FLAG, "types" };
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_14 = {5, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_13};
static const struct {
  NI cap; NIM_CHAR data[92+1];
} TM__yzRo69c2o9bstRNsREZJujPQ_15 = { 92 | NIM_STRLIT_FLAG, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/json.nim(521, 9) `not isNil(node)` " };
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_16 = {92, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_15};
static const struct {
  NI cap; NIM_CHAR data[97+1];
} TM__yzRo69c2o9bstRNsREZJujPQ_17 = { 97 | NIM_STRLIT_FLAG, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/json.nim(522, 9) `node.kind == JObject` " };
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_18 = {97, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_17};
static const struct {
  NI cap; NIM_CHAR data[70+1];
} TM__yzRo69c2o9bstRNsREZJujPQ_19 = { 70 | NIM_STRLIT_FLAG, "field \'fields\' is not accessible for type \'JsonNodeObj\' using \'kind = " };
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_20 = {70, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_19};
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_21 = {8, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_4};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__yzRo69c2o9bstRNsREZJujPQ_22 = { 7 | NIM_STRLIT_FLAG, "apiName" };
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_23 = {7, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_22};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__yzRo69c2o9bstRNsREZJujPQ_24 = { 8 | NIM_STRLIT_FLAG, "argsType" };
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_25 = {8, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_24};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__yzRo69c2o9bstRNsREZJujPQ_26 = { 9 | NIM_STRLIT_FLAG, "argFields" };
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_27 = {9, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_26};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__yzRo69c2o9bstRNsREZJujPQ_28 = { 12 | NIM_STRLIT_FLAG, "responseType" };
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_29 = {12, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_28};
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_30 = {9, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_26};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__yzRo69c2o9bstRNsREZJujPQ_31 = { 4 | NIM_STRLIT_FLAG, "name" };
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_32 = {4, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_31};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__yzRo69c2o9bstRNsREZJujPQ_33 = { 7 | NIM_STRLIT_FLAG, "nimType" };
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_34 = {7, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_33};
static const struct {
  NI cap; NIM_CHAR data[149+1];
} TM__yzRo69c2o9bstRNsREZJujPQ_35 = { 149 | NIM_STRLIT_FLAG, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_36 = {149, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_35};
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_37 = {149, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_35};
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_38 = {6, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_6};
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_39 = {7, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_22};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__yzRo69c2o9bstRNsREZJujPQ_40 = { 11 | NIM_STRLIT_FLAG, "payloadType" };
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_41 = {11, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_40};
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_42 = {149, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_35};
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_43 = {5, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_13};
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_44 = {4, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_31};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__yzRo69c2o9bstRNsREZJujPQ_45 = { 4 | NIM_STRLIT_FLAG, "kind" };
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_46 = {4, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_45};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__yzRo69c2o9bstRNsREZJujPQ_47 = { 6 | NIM_STRLIT_FLAG, "fields" };
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_48 = {6, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_47};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__yzRo69c2o9bstRNsREZJujPQ_49 = { 10 | NIM_STRLIT_FLAG, "enumValues" };
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_50 = {10, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_49};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__yzRo69c2o9bstRNsREZJujPQ_51 = { 14 | NIM_STRLIT_FLAG, "underlyingType" };
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_52 = {14, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_51};
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_53 = {6, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_47};
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_54 = {149, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_35};
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_55 = {10, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_49};
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_56 = {4, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_31};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__yzRo69c2o9bstRNsREZJujPQ_57 = { 7 | NIM_STRLIT_FLAG, "ordinal" };
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_58 = {7, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_57};
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_59 = {149, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_35};
static const NimStringV2 TM__yzRo69c2o9bstRNsREZJujPQ_60 = {149, (NimStrPayload*)&TM__yzRo69c2o9bstRNsREZJujPQ_35};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4491;
extern NIM_THREADVAR TFrame* framePtr__system_u2723;
N_LIB_PRIVATE N_NIMCALL(void, eqsink___typemappingtestlib_u386615)(tyObject_ApiList__N00lzPe3dwihCpxBcKgV0A* dest_p0, tyObject_ApiList__N00lzPe3dwihCpxBcKgV0A* src_p1) {
	if ((*dest_p0).libName.p != (*src_p1).libName.p) {	if ((*dest_p0).libName.p && !((*dest_p0).libName.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).libName.p);
}
	}
(*dest_p0).libName.len = (*src_p1).libName.len; (*dest_p0).libName.p = (*src_p1).libName.p;
	if ((*dest_p0).requests.p != (*src_p1).requests.p) {	eqdestroy___system_u3851((*dest_p0).requests);
	}
(*dest_p0).requests.len = (*src_p1).requests.len; (*dest_p0).requests.p = (*src_p1).requests.p;
	if ((*dest_p0).events.p != (*src_p1).events.p) {	eqdestroy___system_u3851((*dest_p0).events);
	}
(*dest_p0).events.len = (*src_p1).events.len; (*dest_p0).events.p = (*src_p1).events.p;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4491);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2723;
	framePtr__system_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2723 = (*framePtr__system_u2723).prev;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw*, toJson__OOZOOZbrokersZinternalZapi95cbor95descriptor_u679)(tyObject_ApiList__N00lzPe3dwihCpxBcKgV0A* a_p0) {
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* result;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD_;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__2;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__3;
	tyArray__i7SIYz7cZQZPEf2k1h169ag T1_;
NIM_BOOL* nimErr_;
	nimfr_("toJson", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	colontmpD__3 = NIM_NIL;
	nimlf_(96, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");	nimZeroMem((void*)T1_, sizeof(tyArray__i7SIYz7cZQZPEf2k1h169ag));
	T1_[0].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_3;
	colontmpD_ = percent___pureZjson_u2149((*a_p0).libName);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_[0].Field1 = colontmpD_;
	T1_[1].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_5;
	colontmpD__2 = percent___OOZOOZbrokersZinternalZapi95cbor95descriptor_u682((((*a_p0).requests).p) ? ((*a_p0).requests.p->data) : NIM_NIL, (*a_p0).requests.len);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_[1].Field1 = colontmpD__2;
	T1_[2].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_7;
	colontmpD__3 = percent___OOZOOZbrokersZinternalZapi95cbor95descriptor_u682((((*a_p0).events).p) ? ((*a_p0).events.p->data) : NIM_NIL, (*a_p0).events.len);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_[2].Field1 = colontmpD__3;
	result = percent___pureZjson_u2178(T1_, 3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(934, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	eqdestroy___pureZjson_u321(colontmpD__3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___pureZjson_u321(colontmpD__2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___pureZjson_u321(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toJsonString__OOZOOZbrokersZinternalZapi95cbor95descriptor_u1354)(tyObject_ApiList__N00lzPe3dwihCpxBcKgV0A* a_p0) {
	NimStringV2 result;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("toJsonString", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_ = NIM_NIL;
	nimlf_(114, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");	colontmpD_ = toJson__OOZOOZbrokersZinternalZapi95cbor95descriptor_u679(a_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = dollar___pureZjson_u4844(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(934, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	eqdestroy___pureZjson_u321(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZbrokersZinternalZapi95cbor95descriptor_u280)(tySequence__mK9atymt9bnUW3uKIG1KeiTA dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].name.p && !(dest_p0.p->data[colontmp_].name.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].name.p);
}
			if (dest_p0.p->data[colontmp_].nimType.p && !(dest_p0.p->data[colontmp_].nimType.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].nimType.p);
}
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_ApiFieldInfo__zZUT3CKatIAo9cOD0Bx0KxA));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZbrokersZinternalZapi95cbor95descriptor_u865)(tySequence__tJlMjm9cU6lRR9cy1OOInnuw dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].apiName.p && !(dest_p0.p->data[colontmp_].apiName.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].apiName.p);
}
			if (dest_p0.p->data[colontmp_].argsType.p && !(dest_p0.p->data[colontmp_].argsType.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].argsType.p);
}
			eqdestroy___OOZOOZbrokersZinternalZapi95cbor95descriptor_u280(dest_p0.p->data[colontmp_].argFields);
			if (dest_p0.p->data[colontmp_].responseType.p && !(dest_p0.p->data[colontmp_].responseType.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].responseType.p);
}
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_ApiRequestInfo__ehCYMbx4h5K2onwe9bfcUFQ));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZbrokersZinternalZapi95cbor95descriptor_u1036)(tySequence__2SBu9aV86IFAxsC5ppelRjw dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].apiName.p && !(dest_p0.p->data[colontmp_].apiName.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].apiName.p);
}
			if (dest_p0.p->data[colontmp_].payloadType.p && !(dest_p0.p->data[colontmp_].payloadType.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].payloadType.p);
}
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_ApiEventInfo__9b7mI9aFH6Y7VBlPwkLzaJEA));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZbrokersZinternalZapi95cbor95descriptor_u447)(tySequence__9bF3b2qSHKSvvCHOrjrjRGA dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].name.p && !(dest_p0.p->data[colontmp_].name.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].name.p);
}
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_ApiEnumValueInfo__UtUmVKLQogO7tmILqu6HaA));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZbrokersZinternalZapi95cbor95descriptor_u1203)(tySequence__FIas0Yj0j3UPajfxGZPIIQ dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].name.p && !(dest_p0.p->data[colontmp_].name.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].name.p);
}
			if (dest_p0.p->data[colontmp_].kind.p && !(dest_p0.p->data[colontmp_].kind.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].kind.p);
}
			eqdestroy___OOZOOZbrokersZinternalZapi95cbor95descriptor_u280(dest_p0.p->data[colontmp_].fields);
			eqdestroy___OOZOOZbrokersZinternalZapi95cbor95descriptor_u447(dest_p0.p->data[colontmp_].enumValues);
			if (dest_p0.p->data[colontmp_].underlyingType.p && !(dest_p0.p->data[colontmp_].underlyingType.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].underlyingType.p);
}
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_ApiTypeInfo__GhTFYIpPViKs4WGR6UUHhQ));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___typemappingtestlib_u386586)(tyObject_LibraryDescriptor__QvDjwGu3delxSFSwZO5eMA* dest_p0, tyObject_LibraryDescriptor__QvDjwGu3delxSFSwZO5eMA* src_p1) {
	if ((*dest_p0).libName.p != (*src_p1).libName.p) {	if ((*dest_p0).libName.p && !((*dest_p0).libName.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).libName.p);
}
	}
(*dest_p0).libName.len = (*src_p1).libName.len; (*dest_p0).libName.p = (*src_p1).libName.p;
	if ((*dest_p0).cddl.p != (*src_p1).cddl.p) {	if ((*dest_p0).cddl.p && !((*dest_p0).cddl.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).cddl.p);
}
	}
(*dest_p0).cddl.len = (*src_p1).cddl.len; (*dest_p0).cddl.p = (*src_p1).cddl.p;
	if ((*dest_p0).requests.p != (*src_p1).requests.p) {	eqdestroy___OOZOOZbrokersZinternalZapi95cbor95descriptor_u865((*dest_p0).requests);
	}
(*dest_p0).requests.len = (*src_p1).requests.len; (*dest_p0).requests.p = (*src_p1).requests.p;
	if ((*dest_p0).events.p != (*src_p1).events.p) {	eqdestroy___OOZOOZbrokersZinternalZapi95cbor95descriptor_u1036((*dest_p0).events);
	}
(*dest_p0).events.len = (*src_p1).events.len; (*dest_p0).events.p = (*src_p1).events.p;
	if ((*dest_p0).types.p != (*src_p1).types.p) {	eqdestroy___OOZOOZbrokersZinternalZapi95cbor95descriptor_u1203((*dest_p0).types);
	}
(*dest_p0).types.len = (*src_p1).types.len; (*dest_p0).types.p = (*src_p1).types.p;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZOOZbrokersZinternalZapi95cbor95descriptor_u874)(tySequence__tJlMjm9cU6lRR9cy1OOInnuw* dest_p0, tySequence__tJlMjm9cU6lRR9cy1OOInnuw src_p1) {
	if ((*dest_p0).p != src_p1.p) {	eqdestroy___OOZOOZbrokersZinternalZapi95cbor95descriptor_u865((*dest_p0));
	}
(*dest_p0).len = src_p1.len; (*dest_p0).p = src_p1.p;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZOOZbrokersZinternalZapi95cbor95descriptor_u1045)(tySequence__2SBu9aV86IFAxsC5ppelRjw* dest_p0, tySequence__2SBu9aV86IFAxsC5ppelRjw src_p1) {
	if ((*dest_p0).p != src_p1.p) {	eqdestroy___OOZOOZbrokersZinternalZapi95cbor95descriptor_u1036((*dest_p0));
	}
(*dest_p0).len = src_p1.len; (*dest_p0).p = src_p1.p;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZOOZbrokersZinternalZapi95cbor95descriptor_u1212)(tySequence__FIas0Yj0j3UPajfxGZPIIQ* dest_p0, tySequence__FIas0Yj0j3UPajfxGZPIIQ src_p1) {
	if ((*dest_p0).p != src_p1.p) {	eqdestroy___OOZOOZbrokersZinternalZapi95cbor95descriptor_u1203((*dest_p0));
	}
(*dest_p0).len = src_p1.len; (*dest_p0).p = src_p1.p;
}
static N_INLINE(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw*, X5BX5D___pureZjson_u3473)(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* node_p0, NimStringV2 name_p1) {
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* result;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw** T9_;
NIM_BOOL* nimErr_;
	nimfr_("[]", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/json.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimlf_(521, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/json.nim");	{
		if (!!(!((node_p0 == 0)))) goto LA3_;
		failedAssertImpl__stdZassertions_u234(TM__yzRo69c2o9bstRNsREZJujPQ_16);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	nimln_(522);	{
		if (!!(((*node_p0).kind == ((tyEnum_JsonNodeKind__Fnu9aJYjpd15z1gCnQKswxA)5)))) goto LA7_;
		failedAssertImpl__stdZassertions_u234(TM__yzRo69c2o9bstRNsREZJujPQ_18);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA7_: ;
	nimlf_(934, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	nimlf_(525, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/json.nim");	if (!(((32 &((NU8)1<<((NU)(((*node_p0).kind))&7U)))!=0))) 	{ raiseFieldErrorStr(TM__yzRo69c2o9bstRNsREZJujPQ_20, dollar___pureZjson_u20((*node_p0).kind)); goto BeforeRet_;
	}
	T9_ = (tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw**)0;
	T9_ = X5BX5D___pureZjson_u3043((&(*node_p0)._kind_6.fields), name_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(934, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	eqcopy___pureZjson_u324(&result, (*T9_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw*, toJson__OOZOOZbrokersZinternalZapi95cbor95descriptor_u34)(tyObject_ApiFieldInfo__zZUT3CKatIAo9cOD0Bx0KxA* f_p0) {
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* result;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD_;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__2;
	tyArray__i9afe3LVVNlXrk60VmgiJZQ T1_;
NIM_BOOL* nimErr_;
	nimfr_("toJson", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	nimlf_(64, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");	nimZeroMem((void*)T1_, sizeof(tyArray__i9afe3LVVNlXrk60VmgiJZQ));
	T1_[0].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_32;
	colontmpD_ = percent___pureZjson_u2149((*f_p0).name);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_[0].Field1 = colontmpD_;
	T1_[1].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_34;
	colontmpD__2 = percent___pureZjson_u2149((*f_p0).nimType);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_[1].Field1 = colontmpD__2;
	result = percent___pureZjson_u2178(T1_, 2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(934, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	eqdestroy___pureZjson_u321(colontmpD__2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___pureZjson_u321(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw*, toJson__OOZOOZbrokersZinternalZapi95cbor95descriptor_u591)(tyObject_ApiRequestInfo__ehCYMbx4h5K2onwe9bfcUFQ* r_p0) {
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* result;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD_;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__2;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__3;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__4;
	tyArray__5atYQrfpRKpGPven8cNr1g T2_;
NIM_BOOL oldNimErrFin7_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("toJson", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	colontmpD__3 = NIM_NIL;
	colontmpD__4 = NIM_NIL;
	nimlf_(83, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");	nimZeroMem((void*)T2_, sizeof(tyArray__5atYQrfpRKpGPven8cNr1g));
	T2_[0].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_23;
	nimln_(84);	colontmpD_ = percent___pureZjson_u2149((*r_p0).apiName);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[0].Field1 = colontmpD_;
	T2_[1].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_25;
	nimln_(85);	colontmpD__2 = percent___pureZjson_u2149((*r_p0).argsType);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[1].Field1 = colontmpD__2;
	T2_[2].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_27;
	nimlf_(423, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/json.nim");	colontmpD__3 = newJArray__pureZjson_u503();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[2].Field1 = colontmpD__3;
	T2_[3].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_29;
	nimlf_(87, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");	colontmpD__4 = percent___pureZjson_u2149((*r_p0).responseType);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[3].Field1 = colontmpD__4;
	nimln_(83);	result = percent___pureZjson_u2178(T2_, 4);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		tyObject_ApiFieldInfo__zZUT3CKatIAo9cOD0Bx0KxA* f_1;
		NI i_1;
		NI L_1;
		NI T4_;
		f_1 = (tyObject_ApiFieldInfo__zZUT3CKatIAo9cOD0Bx0KxA*)0;
		nimlf_(249, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T4_ = (*r_p0).argFields.len;
		L_1 = T4_;
		{
			nimln_(251);			while (1) {
				tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__5;
				tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__6;
				if (!(i_1 < L_1)) goto LA6;
				colontmpD__5 = NIM_NIL;
				colontmpD__6 = NIM_NIL;
				nimlf_(89, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");				if (i_1 < 0 || i_1 >= (*r_p0).argFields.len){ raiseIndexError2(i_1,(*r_p0).argFields.len-1); goto LA7_;
				}
				f_1 = (&(*r_p0).argFields.p->data[i_1]);
				nimln_(90);				colontmpD__5 = X5BX5D___pureZjson_u3473(result, TM__yzRo69c2o9bstRNsREZJujPQ_30);
				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				colontmpD__6 = toJson__OOZOOZbrokersZinternalZapi95cbor95descriptor_u34((&(*f_1)));
				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				add__pureZjson_u647(colontmpD__5, colontmpD__6);
				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				nimlf_(13, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T10_;
					T10_ = (*r_p0).argFields.len;
					if (!!((T10_ == L_1))) goto LA11_;
					failedAssertImpl__stdZassertions_u234(TM__yzRo69c2o9bstRNsREZJujPQ_36);
					if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				}
LA11_: ;
				{
					LA7_:;
				}
				{
					oldNimErrFin7_ = *nimErr_; *nimErr_ = NIM_FALSE;
					nimlf_(934, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");					eqdestroy___pureZjson_u321(colontmpD__6);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					eqdestroy___pureZjson_u321(colontmpD__5);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					*nimErr_ = oldNimErrFin7_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			} LA6: ;
		}
	}
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___pureZjson_u321(colontmpD__4);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw*, toJson__OOZOOZbrokersZinternalZapi95cbor95descriptor_u659)(tyObject_ApiEventInfo__9b7mI9aFH6Y7VBlPwkLzaJEA* e_p0) {
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* result;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD_;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__2;
	tyArray__i9afe3LVVNlXrk60VmgiJZQ T1_;
NIM_BOOL* nimErr_;
	nimfr_("toJson", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	nimlf_(93, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");	nimZeroMem((void*)T1_, sizeof(tyArray__i9afe3LVVNlXrk60VmgiJZQ));
	T1_[0].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_39;
	colontmpD_ = percent___pureZjson_u2149((*e_p0).apiName);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_[0].Field1 = colontmpD_;
	T1_[1].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_41;
	colontmpD__2 = percent___pureZjson_u2149((*e_p0).payloadType);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_[1].Field1 = colontmpD__2;
	result = percent___pureZjson_u2178(T1_, 2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(934, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	eqdestroy___pureZjson_u321(colontmpD__2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___pureZjson_u321(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw*, toJson__OOZOOZbrokersZinternalZapi95cbor95descriptor_u128)(tyObject_ApiEnumValueInfo__UtUmVKLQogO7tmILqu6HaA v_p0) {
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* result;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD_;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__2;
	tyArray__i9afe3LVVNlXrk60VmgiJZQ T1_;
NIM_BOOL* nimErr_;
	nimfr_("toJson", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	nimlf_(67, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");	nimZeroMem((void*)T1_, sizeof(tyArray__i9afe3LVVNlXrk60VmgiJZQ));
	T1_[0].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_56;
	colontmpD_ = percent___pureZjson_u2149(v_p0.name);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_[0].Field1 = colontmpD_;
	T1_[1].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_58;
	colontmpD__2 = percent___pureZjson_u2159(v_p0.ordinal);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_[1].Field1 = colontmpD__2;
	result = percent___pureZjson_u2178(T1_, 2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(934, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	eqdestroy___pureZjson_u321(colontmpD__2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___pureZjson_u321(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw*, toJson__OOZOOZbrokersZinternalZapi95cbor95descriptor_u148)(tyObject_ApiTypeInfo__GhTFYIpPViKs4WGR6UUHhQ* t_p0) {
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* result;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD_;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__2;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__3;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__4;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__5;
	tyArray__BC49ca8niQgi69aOLyubTa8Q T2_;
NIM_BOOL oldNimErrFin7_;
NIM_BOOL oldNimErrFin19_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("toJson", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	colontmpD__3 = NIM_NIL;
	colontmpD__4 = NIM_NIL;
	colontmpD__5 = NIM_NIL;
	nimlf_(70, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");	nimZeroMem((void*)T2_, sizeof(tyArray__BC49ca8niQgi69aOLyubTa8Q));
	T2_[0].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_44;
	nimln_(71);	colontmpD_ = percent___pureZjson_u2149((*t_p0).name);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[0].Field1 = colontmpD_;
	T2_[1].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_46;
	nimln_(72);	colontmpD__2 = percent___pureZjson_u2149((*t_p0).kind);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[1].Field1 = colontmpD__2;
	T2_[2].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_48;
	nimlf_(423, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/json.nim");	colontmpD__3 = newJArray__pureZjson_u503();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[2].Field1 = colontmpD__3;
	T2_[3].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_50;
	colontmpD__4 = newJArray__pureZjson_u503();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[3].Field1 = colontmpD__4;
	T2_[4].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_52;
	nimlf_(75, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");	colontmpD__5 = percent___pureZjson_u2149((*t_p0).underlyingType);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[4].Field1 = colontmpD__5;
	nimln_(70);	result = percent___pureZjson_u2178(T2_, 5);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		tyObject_ApiFieldInfo__zZUT3CKatIAo9cOD0Bx0KxA* f_1;
		NI i_1;
		NI L_1;
		NI T4_;
		f_1 = (tyObject_ApiFieldInfo__zZUT3CKatIAo9cOD0Bx0KxA*)0;
		nimlf_(249, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T4_ = (*t_p0).fields.len;
		L_1 = T4_;
		{
			nimln_(251);			while (1) {
				tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__6;
				tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__7;
				if (!(i_1 < L_1)) goto LA6;
				colontmpD__6 = NIM_NIL;
				colontmpD__7 = NIM_NIL;
				nimlf_(77, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");				if (i_1 < 0 || i_1 >= (*t_p0).fields.len){ raiseIndexError2(i_1,(*t_p0).fields.len-1); goto LA7_;
				}
				f_1 = (&(*t_p0).fields.p->data[i_1]);
				nimln_(78);				colontmpD__6 = X5BX5D___pureZjson_u3473(result, TM__yzRo69c2o9bstRNsREZJujPQ_53);
				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				colontmpD__7 = toJson__OOZOOZbrokersZinternalZapi95cbor95descriptor_u34((&(*f_1)));
				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				add__pureZjson_u647(colontmpD__6, colontmpD__7);
				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				nimlf_(13, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T10_;
					T10_ = (*t_p0).fields.len;
					if (!!((T10_ == L_1))) goto LA11_;
					failedAssertImpl__stdZassertions_u234(TM__yzRo69c2o9bstRNsREZJujPQ_54);
					if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				}
LA11_: ;
				{
					LA7_:;
				}
				{
					oldNimErrFin7_ = *nimErr_; *nimErr_ = NIM_FALSE;
					nimlf_(934, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");					eqdestroy___pureZjson_u321(colontmpD__7);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					eqdestroy___pureZjson_u321(colontmpD__6);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					*nimErr_ = oldNimErrFin7_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			} LA6: ;
		}
	}
	{
		tyObject_ApiEnumValueInfo__UtUmVKLQogO7tmILqu6HaA* v_1;
		NI i_2;
		NI L_2;
		NI T16_;
		v_1 = (tyObject_ApiEnumValueInfo__UtUmVKLQogO7tmILqu6HaA*)0;
		nimlf_(249, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");		i_2 = ((NI)0);
		nimln_(250);		T16_ = (*t_p0).enumValues.len;
		L_2 = T16_;
		{
			nimln_(251);			while (1) {
				tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__8;
				tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__9;
				if (!(i_2 < L_2)) goto LA18;
				colontmpD__8 = NIM_NIL;
				colontmpD__9 = NIM_NIL;
				nimlf_(79, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");				if (i_2 < 0 || i_2 >= (*t_p0).enumValues.len){ raiseIndexError2(i_2,(*t_p0).enumValues.len-1); goto LA19_;
				}
				v_1 = (&(*t_p0).enumValues.p->data[i_2]);
				nimln_(80);				colontmpD__8 = X5BX5D___pureZjson_u3473(result, TM__yzRo69c2o9bstRNsREZJujPQ_55);
				if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
				colontmpD__9 = toJson__OOZOOZbrokersZinternalZapi95cbor95descriptor_u128((*v_1));
				if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
				add__pureZjson_u647(colontmpD__8, colontmpD__9);
				if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
				nimlf_(13, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");				i_2 += ((NI)1);
				nimln_(254);				{
					NI T22_;
					T22_ = (*t_p0).enumValues.len;
					if (!!((T22_ == L_2))) goto LA23_;
					failedAssertImpl__stdZassertions_u234(TM__yzRo69c2o9bstRNsREZJujPQ_59);
					if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
				}
LA23_: ;
				{
					LA19_:;
				}
				{
					oldNimErrFin19_ = *nimErr_; *nimErr_ = NIM_FALSE;
					nimlf_(934, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");					eqdestroy___pureZjson_u321(colontmpD__9);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					eqdestroy___pureZjson_u321(colontmpD__8);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					*nimErr_ = oldNimErrFin19_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			} LA18: ;
		}
	}
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___pureZjson_u321(colontmpD__5);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__4);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw*, toJson__OOZOOZbrokersZinternalZapi95cbor95descriptor_u754)(tyObject_LibraryDescriptor__QvDjwGu3delxSFSwZO5eMA* d_p0) {
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* result;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD_;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__2;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__3;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__4;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__5;
	tyArray__BC49ca8niQgi69aOLyubTa8Q T2_;
NIM_BOOL oldNimErrFin7_;
NIM_BOOL oldNimErrFin19_;
NIM_BOOL oldNimErrFin31_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("toJson", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	colontmpD__3 = NIM_NIL;
	colontmpD__4 = NIM_NIL;
	colontmpD__5 = NIM_NIL;
	nimlf_(99, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");	nimZeroMem((void*)T2_, sizeof(tyArray__BC49ca8niQgi69aOLyubTa8Q));
	T2_[0].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_8;
	nimln_(100);	colontmpD_ = percent___pureZjson_u2149((*d_p0).libName);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[0].Field1 = colontmpD_;
	T2_[1].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_10;
	nimln_(101);	colontmpD__2 = percent___pureZjson_u2149((*d_p0).cddl);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[1].Field1 = colontmpD__2;
	T2_[2].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_11;
	nimlf_(423, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/json.nim");	colontmpD__3 = newJArray__pureZjson_u503();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[2].Field1 = colontmpD__3;
	T2_[3].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_12;
	colontmpD__4 = newJArray__pureZjson_u503();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[3].Field1 = colontmpD__4;
	T2_[4].Field0 = TM__yzRo69c2o9bstRNsREZJujPQ_14;
	colontmpD__5 = newJArray__pureZjson_u503();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[4].Field1 = colontmpD__5;
	nimlf_(99, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");	result = percent___pureZjson_u2178(T2_, 5);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		tyObject_ApiRequestInfo__ehCYMbx4h5K2onwe9bfcUFQ* r_1;
		NI i_1;
		NI L_1;
		NI T4_;
		r_1 = (tyObject_ApiRequestInfo__ehCYMbx4h5K2onwe9bfcUFQ*)0;
		nimlf_(249, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T4_ = (*d_p0).requests.len;
		L_1 = T4_;
		{
			nimln_(251);			while (1) {
				tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__6;
				tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__7;
				if (!(i_1 < L_1)) goto LA6;
				colontmpD__6 = NIM_NIL;
				colontmpD__7 = NIM_NIL;
				nimlf_(106, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");				if (i_1 < 0 || i_1 >= (*d_p0).requests.len){ raiseIndexError2(i_1,(*d_p0).requests.len-1); goto LA7_;
				}
				r_1 = (&(*d_p0).requests.p->data[i_1]);
				nimln_(107);				colontmpD__6 = X5BX5D___pureZjson_u3473(result, TM__yzRo69c2o9bstRNsREZJujPQ_21);
				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				colontmpD__7 = toJson__OOZOOZbrokersZinternalZapi95cbor95descriptor_u591((&(*r_1)));
				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				add__pureZjson_u647(colontmpD__6, colontmpD__7);
				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				nimlf_(13, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T10_;
					T10_ = (*d_p0).requests.len;
					if (!!((T10_ == L_1))) goto LA11_;
					failedAssertImpl__stdZassertions_u234(TM__yzRo69c2o9bstRNsREZJujPQ_37);
					if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				}
LA11_: ;
				{
					LA7_:;
				}
				{
					oldNimErrFin7_ = *nimErr_; *nimErr_ = NIM_FALSE;
					nimlf_(934, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");					eqdestroy___pureZjson_u321(colontmpD__7);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					eqdestroy___pureZjson_u321(colontmpD__6);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					*nimErr_ = oldNimErrFin7_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			} LA6: ;
		}
	}
	{
		tyObject_ApiEventInfo__9b7mI9aFH6Y7VBlPwkLzaJEA* e_1;
		NI i_2;
		NI L_2;
		NI T16_;
		e_1 = (tyObject_ApiEventInfo__9b7mI9aFH6Y7VBlPwkLzaJEA*)0;
		nimlf_(249, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");		i_2 = ((NI)0);
		nimln_(250);		T16_ = (*d_p0).events.len;
		L_2 = T16_;
		{
			nimln_(251);			while (1) {
				tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__8;
				tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__9;
				if (!(i_2 < L_2)) goto LA18;
				colontmpD__8 = NIM_NIL;
				colontmpD__9 = NIM_NIL;
				nimlf_(108, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");				if (i_2 < 0 || i_2 >= (*d_p0).events.len){ raiseIndexError2(i_2,(*d_p0).events.len-1); goto LA19_;
				}
				e_1 = (&(*d_p0).events.p->data[i_2]);
				nimln_(109);				colontmpD__8 = X5BX5D___pureZjson_u3473(result, TM__yzRo69c2o9bstRNsREZJujPQ_38);
				if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
				colontmpD__9 = toJson__OOZOOZbrokersZinternalZapi95cbor95descriptor_u659((&(*e_1)));
				if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
				add__pureZjson_u647(colontmpD__8, colontmpD__9);
				if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
				nimlf_(13, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");				i_2 += ((NI)1);
				nimln_(254);				{
					NI T22_;
					T22_ = (*d_p0).events.len;
					if (!!((T22_ == L_2))) goto LA23_;
					failedAssertImpl__stdZassertions_u234(TM__yzRo69c2o9bstRNsREZJujPQ_42);
					if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
				}
LA23_: ;
				{
					LA19_:;
				}
				{
					oldNimErrFin19_ = *nimErr_; *nimErr_ = NIM_FALSE;
					nimlf_(934, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");					eqdestroy___pureZjson_u321(colontmpD__9);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					eqdestroy___pureZjson_u321(colontmpD__8);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					*nimErr_ = oldNimErrFin19_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			} LA18: ;
		}
	}
	{
		tyObject_ApiTypeInfo__GhTFYIpPViKs4WGR6UUHhQ* t_1;
		NI i_3;
		NI L_3;
		NI T28_;
		t_1 = (tyObject_ApiTypeInfo__GhTFYIpPViKs4WGR6UUHhQ*)0;
		nimlf_(249, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");		i_3 = ((NI)0);
		nimln_(250);		T28_ = (*d_p0).types.len;
		L_3 = T28_;
		{
			nimln_(251);			while (1) {
				tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__10;
				tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD__11;
				if (!(i_3 < L_3)) goto LA30;
				colontmpD__10 = NIM_NIL;
				colontmpD__11 = NIM_NIL;
				nimlf_(110, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");				if (i_3 < 0 || i_3 >= (*d_p0).types.len){ raiseIndexError2(i_3,(*d_p0).types.len-1); goto LA31_;
				}
				t_1 = (&(*d_p0).types.p->data[i_3]);
				nimln_(111);				colontmpD__10 = X5BX5D___pureZjson_u3473(result, TM__yzRo69c2o9bstRNsREZJujPQ_43);
				if (NIM_UNLIKELY(*nimErr_)) goto LA31_;
				colontmpD__11 = toJson__OOZOOZbrokersZinternalZapi95cbor95descriptor_u148((&(*t_1)));
				if (NIM_UNLIKELY(*nimErr_)) goto LA31_;
				add__pureZjson_u647(colontmpD__10, colontmpD__11);
				if (NIM_UNLIKELY(*nimErr_)) goto LA31_;
				nimlf_(13, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");				i_3 += ((NI)1);
				nimln_(254);				{
					NI T34_;
					T34_ = (*d_p0).types.len;
					if (!!((T34_ == L_3))) goto LA35_;
					failedAssertImpl__stdZassertions_u234(TM__yzRo69c2o9bstRNsREZJujPQ_60);
					if (NIM_UNLIKELY(*nimErr_)) goto LA31_;
				}
LA35_: ;
				{
					LA31_:;
				}
				{
					oldNimErrFin31_ = *nimErr_; *nimErr_ = NIM_FALSE;
					nimlf_(934, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");					eqdestroy___pureZjson_u321(colontmpD__11);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					eqdestroy___pureZjson_u321(colontmpD__10);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					*nimErr_ = oldNimErrFin31_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			} LA30: ;
		}
	}
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___pureZjson_u321(colontmpD__5);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__4);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toJsonString__OOZOOZbrokersZinternalZapi95cbor95descriptor_u1357)(tyObject_LibraryDescriptor__QvDjwGu3delxSFSwZO5eMA* d_p0) {
	NimStringV2 result;
	tyObject_JsonNodeObj__jCnc0wNDBsK57oLi44x0kw* colontmpD_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("toJsonString", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_ = NIM_NIL;
	nimlf_(117, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/api_cbor_descriptor.nim");	colontmpD_ = toJson__OOZOOZbrokersZinternalZapi95cbor95descriptor_u754(d_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	result = dollar___pureZjson_u4844(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		nimlf_(934, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");		eqdestroy___pureZjson_u321(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___typemappingtestlib_u386606)(tyObject_ApiList__N00lzPe3dwihCpxBcKgV0A* dest_p0) {
	if ((*dest_p0).libName.p && !((*dest_p0).libName.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).libName.p);
}
	eqdestroy___system_u3851((*dest_p0).requests);
	eqdestroy___system_u3851((*dest_p0).events);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___typemappingtestlib_u386577)(tyObject_LibraryDescriptor__QvDjwGu3delxSFSwZO5eMA* dest_p0) {
	if ((*dest_p0).libName.p && !((*dest_p0).libName.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).libName.p);
}
	if ((*dest_p0).cddl.p && !((*dest_p0).cddl.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).cddl.p);
}
	eqdestroy___OOZOOZbrokersZinternalZapi95cbor95descriptor_u865((*dest_p0).requests);
	eqdestroy___OOZOOZbrokersZinternalZapi95cbor95descriptor_u1036((*dest_p0).events);
	eqdestroy___OOZOOZbrokersZinternalZapi95cbor95descriptor_u1203((*dest_p0).types);
}
