/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c -w -ferror-limit=3 -pthread --coverage -O0 -g   -I/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib -I/Users/schwarzy/dev/status/nim-brokers/test/typemappingtestlib -o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_typemappingtestlib/@m..@s..@s..@s..@s..@s.choosenim@stoolchains@snim-2.2.4@slib@ssystem@sdollars.nim.c.o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_typemappingtestlib/@m..@s..@s..@s..@s..@s.choosenim@stoolchains@snim-2.2.4@slib@ssystem@sdollars.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tySequence__IHUFRsFxZNv7YydiUO2esQ tySequence__IHUFRsFxZNv7YydiUO2esQ;
typedef struct tySequence__IHUFRsFxZNv7YydiUO2esQ_Content tySequence__IHUFRsFxZNv7YydiUO2esQ_Content;
typedef struct tySequence__0s2kWTBf1M8Pje8cHr0qtA tySequence__0s2kWTBf1M8Pje8cHr0qtA;
typedef struct tySequence__0s2kWTBf1M8Pje8cHr0qtA_Content tySequence__0s2kWTBf1M8Pje8cHr0qtA_Content;
typedef struct tyObject_Tag__DL3W89bOfOkK14xV67LCrog tyObject_Tag__DL3W89bOfOkK14xV67LCrog;
typedef struct tySequence__4eQHGndY6XBYpFOH09apV8Q tySequence__4eQHGndY6XBYpFOH09apV8Q;
typedef struct tySequence__4eQHGndY6XBYpFOH09apV8Q_Content tySequence__4eQHGndY6XBYpFOH09apV8Q_Content;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
typedef struct tySequence__H8X9cWYQfMAZrLe79b7JNPrA tySequence__H8X9cWYQfMAZrLe79b7JNPrA;
typedef struct tySequence__H8X9cWYQfMAZrLe79b7JNPrA_Content tySequence__H8X9cWYQfMAZrLe79b7JNPrA_Content;
typedef struct tyObject_Inner__19bcVqla9cEhDUaCPb6ABKzg tyObject_Inner__19bcVqla9cEhDUaCPb6ABKzg;
typedef struct tyObject_Slot__MGNwRgf3rnJeBHvV3ZG4Ew tyObject_Slot__MGNwRgf3rnJeBHvV3ZG4Ew;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tySequence__IHUFRsFxZNv7YydiUO2esQ {
  NI len; tySequence__IHUFRsFxZNv7YydiUO2esQ_Content* p;
};
typedef NI32 tyArray__7pxmxukJp9aDJpjDIdzM2gw[4];
typedef NI32 tyArray__wK0DdaLVk4sRdSCiB2iZnQ[6];
struct tySequence__0s2kWTBf1M8Pje8cHr0qtA {
  NI len; tySequence__0s2kWTBf1M8Pje8cHr0qtA_Content* p;
};
struct tyObject_Tag__DL3W89bOfOkK14xV67LCrog {
	NimStringV2 key;
	NimStringV2 value;
};
struct tySequence__4eQHGndY6XBYpFOH09apV8Q {
  NI len; tySequence__4eQHGndY6XBYpFOH09apV8Q_Content* p;
};
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
	NimStringV2 Field0;
	NimStringV2 Field1;
};
struct tySequence__H8X9cWYQfMAZrLe79b7JNPrA {
  NI len; tySequence__H8X9cWYQfMAZrLe79b7JNPrA_Content* p;
};
struct tyObject_Inner__19bcVqla9cEhDUaCPb6ABKzg {
	NI32 id;
	NimStringV2 tag;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ bytes;
};
typedef NimStringV2 tyArray__sMpvt1sOxOJ3LFGulnbeMQ[4];
struct tyObject_Slot__MGNwRgf3rnJeBHvV3ZG4Ew {
	NI32 idx;
	NimStringV2 name;
};
typedef tyObject_Slot__MGNwRgf3rnJeBHvV3ZG4Ew tyArray__AD3pyqDtyjQC8FAANmU6YA[4];
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tySequence__IHUFRsFxZNv7YydiUO2esQ_Content { NI cap; NI64 data[SEQ_DECL_SIZE]; };
struct tySequence__0s2kWTBf1M8Pje8cHr0qtA_Content { NI cap; tyObject_Tag__DL3W89bOfOkK14xV67LCrog data[SEQ_DECL_SIZE]; };
struct tySequence__4eQHGndY6XBYpFOH09apV8Q_Content { NI cap; tyTuple__UV3llMMYFckfui8YMBuUZA data[SEQ_DECL_SIZE]; };
struct tySequence__H8X9cWYQfMAZrLe79b7JNPrA_Content { NI cap; tyObject_Inner__19bcVqla9cEhDUaCPb6ABKzg data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_u187)(NimStringV2* result_p0, NI64 x_p1);
static N_INLINE(void, addInt__stdZprivateZdigitsutils_u204)(NimStringV2* result_p0, NI x_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4709)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_u184)(NimStringV2* result_p0, NU64 x_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__typemappingtestlib_u9532)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ x_p0, NimStringV2 prefix_p1, NimStringV2 separator_p2, NimStringV2 suffix_p3);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2690)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__typemappingtestlib_u9565)(NimStringV2* s_p0, NU8 x_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__typemappingtestlib_u81657)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ x_p0, NimStringV2 prefix_p1, NimStringV2 separator_p2, NimStringV2 suffix_p3);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__stdZprivateZoscommon_u119)(NimStringV2* s_p0, NimStringV2 x_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__typemappingtestlib_u89301)(tySequence__IHUFRsFxZNv7YydiUO2esQ x_p0, NimStringV2 prefix_p1, NimStringV2 separator_p2, NimStringV2 suffix_p3);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__typemappingtestlib_u37384)(NimStringV2* s_p0, NI64 x_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__typemappingtestlib_u96893)(tyArray__7pxmxukJp9aDJpjDIdzM2gw x_p0, NimStringV2 prefix_p1, NimStringV2 separator_p2, NimStringV2 suffix_p3);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__typemappingtestlib_u11040)(NimStringV2* s_p0, NI32 x_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__typemappingtestlib_u104590)(tyArray__wK0DdaLVk4sRdSCiB2iZnQ x_p0, NimStringV2 prefix_p1, NimStringV2 separator_p2, NimStringV2 suffix_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__typemappingtestlib_u118040)(tySequence__0s2kWTBf1M8Pje8cHr0qtA x_p0, NimStringV2 prefix_p1, NimStringV2 separator_p2, NimStringV2 suffix_p3);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__typemappingtestlib_u118073)(NimStringV2* s_p0, tyObject_Tag__DL3W89bOfOkK14xV67LCrog* x_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__typemappingtestlib_u162473)(tySequence__4eQHGndY6XBYpFOH09apV8Q x_p0, NimStringV2 prefix_p1, NimStringV2 separator_p2, NimStringV2 suffix_p3);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__typemappingtestlib_u162507)(NimStringV2* s_p0, tyTuple__UV3llMMYFckfui8YMBuUZA* x_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__typemappingtestlib_u210202)(tySequence__H8X9cWYQfMAZrLe79b7JNPrA x_p0, NimStringV2 prefix_p1, NimStringV2 separator_p2, NimStringV2 suffix_p3);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__typemappingtestlib_u210235)(NimStringV2* s_p0, tyObject_Inner__19bcVqla9cEhDUaCPb6ABKzg* x_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__typemappingtestlib_u240077)(tyArray__sMpvt1sOxOJ3LFGulnbeMQ x_p0, NimStringV2 prefix_p1, NimStringV2 separator_p2, NimStringV2 suffix_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__typemappingtestlib_u290392)(tyArray__AD3pyqDtyjQC8FAANmU6YA x_p0, NimStringV2 prefix_p1, NimStringV2 separator_p2, NimStringV2 suffix_p3);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__typemappingtestlib_u290475)(NimStringV2* s_p0, tyObject_Slot__MGNwRgf3rnJeBHvV3ZG4Ew x_p1);
static N_INLINE(void, addFloat__system_u5022)(NimStringV2* result_p0, NF x_p1);
N_LIB_PRIVATE N_NIMCALL(void, addFloatRoundtrip__system_u5027)(NimStringV2* result_p0, NF x_p1);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_3 = {0, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_4 = {0, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_5 = {0, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_6 = {0, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_7 = {0, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
static const struct {
  NI cap; NIM_CHAR data[149+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_9 = { 149 | NIM_STRLIT_FLAG, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_10 = {149, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_9};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_11 = { 2 | NIM_STRLIT_FLAG, "@[" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_12 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_11};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_13 = { 2 | NIM_STRLIT_FLAG, ", " };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_14 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_13};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_15 = { 1 | NIM_STRLIT_FLAG, "]" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_16 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_15};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_17 = {149, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_9};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_18 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_11};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_19 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_13};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_20 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_15};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_21 = {149, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_9};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_22 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_11};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_23 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_13};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_24 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_15};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_25 = { 1 | NIM_STRLIT_FLAG, "[" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_26 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_25};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_27 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_13};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_28 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_15};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_29 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_25};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_30 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_13};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_31 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_15};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_32 = {149, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_9};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_33 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_11};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_34 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_13};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_35 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_15};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_36 = { 1 | NIM_STRLIT_FLAG, "(" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_37 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_36};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_38 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_13};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_39 = { 3 | NIM_STRLIT_FLAG, "key" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_40 = {3, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_39};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_41 = { 2 | NIM_STRLIT_FLAG, ": " };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_42 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_41};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_43 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_13};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_44 = { 7 | NIM_STRLIT_FLAG, "payload" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_45 = {7, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_44};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_46 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_41};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_47 = { 1 | NIM_STRLIT_FLAG, ")" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_48 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_47};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_49 = {149, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_9};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_50 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_11};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_51 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_13};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_52 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_15};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_53 = {149, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_9};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_54 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_11};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_55 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_13};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_56 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_15};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_57 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_25};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_58 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_13};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_59 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_15};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_60 = {0, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_61 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_25};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_62 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_13};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_63 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_15};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_64 = {0, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_65 = {0, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
extern NIM_THREADVAR TFrame* framePtr__system_u2723;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4491;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2723;
	framePtr__system_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2723 = (*framePtr__system_u2723).prev;
}
static N_INLINE(void, addInt__stdZprivateZdigitsutils_u204)(NimStringV2* result_p0, NI x_p1) {
	nimfr_("addInt", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/std/private/digitsutils.nim");
	nimlf_(116, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/std/private/digitsutils.nim");	addInt__stdZprivateZdigitsutils_u187(result_p0, ((NI64) (x_p1)));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0) {
	NimStringV2 result;
	nimfr_("$", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
	nimlf_(20, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_4;
	nimln_(21);	addInt__stdZprivateZdigitsutils_u204((&result), xX60gensym0__p0);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u34)(NI64 xX60gensym4__p0) {
	NimStringV2 result;
	nimfr_("$", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
	nimln_(20);	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_3;
	nimln_(21);	addInt__stdZprivateZdigitsutils_u187((&result), xX60gensym4__p0);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u29)(NI32 xX60gensym3__p0) {
	NimStringV2 result;
	nimfr_("$", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
	nimln_(20);	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_5;
	nimln_(21);	addInt__stdZprivateZdigitsutils_u204((&result), ((NI) (xX60gensym3__p0)));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u59)(NU64 xX60gensym9__p0) {
	NimStringV2 result;
	nimfr_("$", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
	nimln_(20);	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_6;
	nimln_(21);	addInt__stdZprivateZdigitsutils_u184((&result), xX60gensym9__p0);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u24)(NI16 xX60gensym2__p0) {
	NimStringV2 result;
	nimfr_("$", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
	nimln_(20);	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_7;
	nimln_(21);	addInt__stdZprivateZdigitsutils_u204((&result), ((NI) (xX60gensym2__p0)));
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__n49a9aYp5BrbXv9a6OCpJYm0g_8;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1731(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__n49a9aYp5BrbXv9a6OCpJYm0g_8)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__n49a9aYp5BrbXv9a6OCpJYm0g_8);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4491);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__typemappingtestlib_u9532)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ x_p0, NimStringV2 prefix_p1, NimStringV2 separator_p2, NimStringV2 suffix_p3) {
	NimStringV2 result;
	NIM_BOOL firstElement_1;
NIM_BOOL* nimErr_;
	nimfr_("collectionToString", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(1694, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	eqcopy___system_u2690((&result), prefix_p1);
	nimlf_(102, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");	firstElement_1 = NIM_TRUE;
	{
		NU8* value_1;
		NI i_1;
		NI L_1;
		NI T2_;
		value_1 = (NU8*)0;
		nimlf_(249, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T2_ = x_p0.len;
		L_1 = T2_;
		{
			nimln_(251);			while (1) {
				if (!(i_1 < L_1)) goto LA4;
				nimlf_(103, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");				value_1 = (&x_p0.p->data[i_1]);
				nimln_(104);				{
					if (!firstElement_1) goto LA7_;
					nimln_(105);					firstElement_1 = NIM_FALSE;
				}
				goto LA5_;
LA7_: ;
				{
					nimln_(107);					prepareAdd((&result), separator_p2.len + 0);
appendString((&result), separator_p2);
				}
LA5_: ;
				nimln_(116);				addQuoted__typemappingtestlib_u9565((&result), (*value_1));
				nimlf_(13, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T12_;
					T12_ = x_p0.len;
					if (!!((T12_ == L_1))) goto LA13_;
					failedAssertImpl__stdZassertions_u234(TM__n49a9aYp5BrbXv9a6OCpJYm0g_10);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA13_: ;
			} LA4: ;
		}
	}
	nimlf_(117, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");	prepareAdd((&result), suffix_p3.len + 0);
appendString((&result), suffix_p3);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___typemappingtestlib_u9528)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ x_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("$", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(133);	result = collectionToString__typemappingtestlib_u9532(x_p0, TM__n49a9aYp5BrbXv9a6OCpJYm0g_12, TM__n49a9aYp5BrbXv9a6OCpJYm0g_14, TM__n49a9aYp5BrbXv9a6OCpJYm0g_16);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__typemappingtestlib_u81657)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ x_p0, NimStringV2 prefix_p1, NimStringV2 separator_p2, NimStringV2 suffix_p3) {
	NimStringV2 result;
	NIM_BOOL firstElement_1;
NIM_BOOL* nimErr_;
	nimfr_("collectionToString", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(1694, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	eqcopy___system_u2690((&result), prefix_p1);
	nimlf_(102, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");	firstElement_1 = NIM_TRUE;
	{
		NimStringV2* value_1;
		NI i_1;
		NI L_1;
		NI T2_;
		value_1 = (NimStringV2*)0;
		nimlf_(249, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T2_ = x_p0.len;
		L_1 = T2_;
		{
			nimln_(251);			while (1) {
				if (!(i_1 < L_1)) goto LA4;
				nimlf_(103, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");				value_1 = (&x_p0.p->data[i_1]);
				nimln_(104);				{
					if (!firstElement_1) goto LA7_;
					nimln_(105);					firstElement_1 = NIM_FALSE;
				}
				goto LA5_;
LA7_: ;
				{
					nimln_(107);					prepareAdd((&result), separator_p2.len + 0);
appendString((&result), separator_p2);
				}
LA5_: ;
				nimln_(116);				addQuoted__stdZprivateZoscommon_u119((&result), (*value_1));
				nimlf_(13, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T12_;
					T12_ = x_p0.len;
					if (!!((T12_ == L_1))) goto LA13_;
					failedAssertImpl__stdZassertions_u234(TM__n49a9aYp5BrbXv9a6OCpJYm0g_17);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA13_: ;
			} LA4: ;
		}
	}
	nimlf_(117, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");	prepareAdd((&result), suffix_p3.len + 0);
appendString((&result), suffix_p3);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___typemappingtestlib_u81653)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ x_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("$", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(133);	result = collectionToString__typemappingtestlib_u81657(x_p0, TM__n49a9aYp5BrbXv9a6OCpJYm0g_18, TM__n49a9aYp5BrbXv9a6OCpJYm0g_19, TM__n49a9aYp5BrbXv9a6OCpJYm0g_20);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__typemappingtestlib_u89301)(tySequence__IHUFRsFxZNv7YydiUO2esQ x_p0, NimStringV2 prefix_p1, NimStringV2 separator_p2, NimStringV2 suffix_p3) {
	NimStringV2 result;
	NIM_BOOL firstElement_1;
NIM_BOOL* nimErr_;
	nimfr_("collectionToString", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(1694, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	eqcopy___system_u2690((&result), prefix_p1);
	nimlf_(102, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");	firstElement_1 = NIM_TRUE;
	{
		NI64* value_1;
		NI i_1;
		NI L_1;
		NI T2_;
		value_1 = (NI64*)0;
		nimlf_(249, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T2_ = x_p0.len;
		L_1 = T2_;
		{
			nimln_(251);			while (1) {
				if (!(i_1 < L_1)) goto LA4;
				nimlf_(103, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");				value_1 = (&x_p0.p->data[i_1]);
				nimln_(104);				{
					if (!firstElement_1) goto LA7_;
					nimln_(105);					firstElement_1 = NIM_FALSE;
				}
				goto LA5_;
LA7_: ;
				{
					nimln_(107);					prepareAdd((&result), separator_p2.len + 0);
appendString((&result), separator_p2);
				}
LA5_: ;
				nimln_(116);				addQuoted__typemappingtestlib_u37384((&result), (*value_1));
				nimlf_(13, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T12_;
					T12_ = x_p0.len;
					if (!!((T12_ == L_1))) goto LA13_;
					failedAssertImpl__stdZassertions_u234(TM__n49a9aYp5BrbXv9a6OCpJYm0g_21);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA13_: ;
			} LA4: ;
		}
	}
	nimlf_(117, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");	prepareAdd((&result), suffix_p3.len + 0);
appendString((&result), suffix_p3);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___typemappingtestlib_u89297)(tySequence__IHUFRsFxZNv7YydiUO2esQ x_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("$", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(133);	result = collectionToString__typemappingtestlib_u89301(x_p0, TM__n49a9aYp5BrbXv9a6OCpJYm0g_22, TM__n49a9aYp5BrbXv9a6OCpJYm0g_23, TM__n49a9aYp5BrbXv9a6OCpJYm0g_24);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__typemappingtestlib_u96893)(tyArray__7pxmxukJp9aDJpjDIdzM2gw x_p0, NimStringV2 prefix_p1, NimStringV2 separator_p2, NimStringV2 suffix_p3) {
	NimStringV2 result;
	NIM_BOOL firstElement_1;
	nimfr_("collectionToString", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
	result.len = 0; result.p = NIM_NIL;
	nimlf_(1694, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	eqcopy___system_u2690((&result), prefix_p1);
	nimlf_(102, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");	firstElement_1 = NIM_TRUE;
	{
		NI32 value_1;
		NI i_1;
		value_1 = (NI32)0;
		nimlf_(43, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");		i_1 = ((NI)0);
		{
			nimln_(44);			while (1) {
				nimlf_(103, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");				value_1 = x_p0[(i_1)- 0];
				nimln_(104);				{
					if (!firstElement_1) goto LA6_;
					nimln_(105);					firstElement_1 = NIM_FALSE;
				}
				goto LA4_;
LA6_: ;
				{
					nimln_(107);					prepareAdd((&result), separator_p2.len + 0);
appendString((&result), separator_p2);
				}
LA4_: ;
				nimln_(116);				addQuoted__typemappingtestlib_u11040((&result), value_1);
				nimlf_(46, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");				{
					if (!(((NI)3) <= i_1)) goto LA11_;
					goto LA2;
				}
LA11_: ;
				nimln_(13);				i_1 += ((NI)1);
			}
		} LA2: ;
	}
	nimlf_(117, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");	prepareAdd((&result), suffix_p3.len + 0);
appendString((&result), suffix_p3);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___typemappingtestlib_u96888)(tyArray__7pxmxukJp9aDJpjDIdzM2gw x_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("$", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(149);	result = collectionToString__typemappingtestlib_u96893(x_p0, TM__n49a9aYp5BrbXv9a6OCpJYm0g_26, TM__n49a9aYp5BrbXv9a6OCpJYm0g_27, TM__n49a9aYp5BrbXv9a6OCpJYm0g_28);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__typemappingtestlib_u104590)(tyArray__wK0DdaLVk4sRdSCiB2iZnQ x_p0, NimStringV2 prefix_p1, NimStringV2 separator_p2, NimStringV2 suffix_p3) {
	NimStringV2 result;
	NIM_BOOL firstElement_1;
	nimfr_("collectionToString", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
	result.len = 0; result.p = NIM_NIL;
	nimlf_(1694, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	eqcopy___system_u2690((&result), prefix_p1);
	nimlf_(102, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");	firstElement_1 = NIM_TRUE;
	{
		NI32 value_1;
		NI i_1;
		value_1 = (NI32)0;
		nimlf_(43, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");		i_1 = ((NI)0);
		{
			nimln_(44);			while (1) {
				nimlf_(103, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");				value_1 = x_p0[(i_1)- 0];
				nimln_(104);				{
					if (!firstElement_1) goto LA6_;
					nimln_(105);					firstElement_1 = NIM_FALSE;
				}
				goto LA4_;
LA6_: ;
				{
					nimln_(107);					prepareAdd((&result), separator_p2.len + 0);
appendString((&result), separator_p2);
				}
LA4_: ;
				nimln_(116);				addQuoted__typemappingtestlib_u11040((&result), value_1);
				nimlf_(46, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");				{
					if (!(((NI)5) <= i_1)) goto LA11_;
					goto LA2;
				}
LA11_: ;
				nimln_(13);				i_1 += ((NI)1);
			}
		} LA2: ;
	}
	nimlf_(117, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");	prepareAdd((&result), suffix_p3.len + 0);
appendString((&result), suffix_p3);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___typemappingtestlib_u104585)(tyArray__wK0DdaLVk4sRdSCiB2iZnQ x_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("$", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(149);	result = collectionToString__typemappingtestlib_u104590(x_p0, TM__n49a9aYp5BrbXv9a6OCpJYm0g_29, TM__n49a9aYp5BrbXv9a6OCpJYm0g_30, TM__n49a9aYp5BrbXv9a6OCpJYm0g_31);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__typemappingtestlib_u118040)(tySequence__0s2kWTBf1M8Pje8cHr0qtA x_p0, NimStringV2 prefix_p1, NimStringV2 separator_p2, NimStringV2 suffix_p3) {
	NimStringV2 result;
	NIM_BOOL firstElement_1;
NIM_BOOL* nimErr_;
	nimfr_("collectionToString", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(1694, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	eqcopy___system_u2690((&result), prefix_p1);
	nimlf_(102, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");	firstElement_1 = NIM_TRUE;
	{
		tyObject_Tag__DL3W89bOfOkK14xV67LCrog* value_1;
		NI i_1;
		NI L_1;
		NI T2_;
		value_1 = (tyObject_Tag__DL3W89bOfOkK14xV67LCrog*)0;
		nimlf_(249, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T2_ = x_p0.len;
		L_1 = T2_;
		{
			nimln_(251);			while (1) {
				if (!(i_1 < L_1)) goto LA4;
				nimlf_(103, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");				value_1 = (&x_p0.p->data[i_1]);
				nimln_(104);				{
					if (!firstElement_1) goto LA7_;
					nimln_(105);					firstElement_1 = NIM_FALSE;
				}
				goto LA5_;
LA7_: ;
				{
					nimln_(107);					prepareAdd((&result), separator_p2.len + 0);
appendString((&result), separator_p2);
				}
LA5_: ;
				nimln_(116);				addQuoted__typemappingtestlib_u118073((&result), (&(*value_1)));
				nimlf_(13, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T12_;
					T12_ = x_p0.len;
					if (!!((T12_ == L_1))) goto LA13_;
					failedAssertImpl__stdZassertions_u234(TM__n49a9aYp5BrbXv9a6OCpJYm0g_32);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA13_: ;
			} LA4: ;
		}
	}
	nimlf_(117, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");	prepareAdd((&result), suffix_p3.len + 0);
appendString((&result), suffix_p3);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___typemappingtestlib_u118036)(tySequence__0s2kWTBf1M8Pje8cHr0qtA x_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("$", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(133);	result = collectionToString__typemappingtestlib_u118040(x_p0, TM__n49a9aYp5BrbXv9a6OCpJYm0g_33, TM__n49a9aYp5BrbXv9a6OCpJYm0g_34, TM__n49a9aYp5BrbXv9a6OCpJYm0g_35);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___typemappingtestlib_u162513)(tyTuple__UV3llMMYFckfui8YMBuUZA* x_p0) {
	NimStringV2 result;
	NI countX60gensym13886__1;
	nimfr_("$", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
	nimln_(94);	nimlf_(19, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/std/private/miscdollars.nim");	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_37;
	nimln_(21);	countX60gensym13886__1 = ((NI)0);
	{
		if (!NIM_TRUE) goto LA3_;
		nimln_(23);		{
			if (!(((NI)0) < countX60gensym13886__1)) goto LA7_;
			prepareAdd((&result), 2);
appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_38);
		}
LA7_: ;
		nimln_(25);		prepareAdd((&result), 3);
appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_40);
		nimln_(26);		prepareAdd((&result), 2);
appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_42);
		nimln_(27);		countX60gensym13886__1 += ((NI)1);
		nimln_(33);		addQuoted__stdZprivateZoscommon_u119((&result), (*x_p0).Field0);
	}
LA3_: ;
	{
		if (!NIM_TRUE) goto LA11_;
		nimln_(23);		{
			if (!(((NI)0) < countX60gensym13886__1)) goto LA15_;
			prepareAdd((&result), 2);
appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_43);
		}
LA15_: ;
		nimln_(25);		prepareAdd((&result), 7);
appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_45);
		nimln_(26);		prepareAdd((&result), 2);
appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_46);
		nimln_(27);		countX60gensym13886__1 += ((NI)1);
		nimln_(33);		addQuoted__stdZprivateZoscommon_u119((&result), (*x_p0).Field1);
	}
LA11_: ;
	nimln_(39);	prepareAdd((&result), 1);
appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_48);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__typemappingtestlib_u162473)(tySequence__4eQHGndY6XBYpFOH09apV8Q x_p0, NimStringV2 prefix_p1, NimStringV2 separator_p2, NimStringV2 suffix_p3) {
	NimStringV2 result;
	NIM_BOOL firstElement_1;
NIM_BOOL* nimErr_;
	nimfr_("collectionToString", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(1694, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	eqcopy___system_u2690((&result), prefix_p1);
	nimlf_(102, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");	firstElement_1 = NIM_TRUE;
	{
		tyTuple__UV3llMMYFckfui8YMBuUZA* value_1;
		NI i_1;
		NI L_1;
		NI T2_;
		value_1 = (tyTuple__UV3llMMYFckfui8YMBuUZA*)0;
		nimlf_(249, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T2_ = x_p0.len;
		L_1 = T2_;
		{
			nimln_(251);			while (1) {
				if (!(i_1 < L_1)) goto LA4;
				nimlf_(103, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");				value_1 = (&x_p0.p->data[i_1]);
				nimln_(104);				{
					if (!firstElement_1) goto LA7_;
					nimln_(105);					firstElement_1 = NIM_FALSE;
				}
				goto LA5_;
LA7_: ;
				{
					nimln_(107);					prepareAdd((&result), separator_p2.len + 0);
appendString((&result), separator_p2);
				}
LA5_: ;
				nimln_(116);				addQuoted__typemappingtestlib_u162507((&result), (&(*value_1)));
				nimlf_(13, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T12_;
					T12_ = x_p0.len;
					if (!!((T12_ == L_1))) goto LA13_;
					failedAssertImpl__stdZassertions_u234(TM__n49a9aYp5BrbXv9a6OCpJYm0g_49);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA13_: ;
			} LA4: ;
		}
	}
	nimlf_(117, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");	prepareAdd((&result), suffix_p3.len + 0);
appendString((&result), suffix_p3);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___typemappingtestlib_u162469)(tySequence__4eQHGndY6XBYpFOH09apV8Q x_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("$", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(133);	result = collectionToString__typemappingtestlib_u162473(x_p0, TM__n49a9aYp5BrbXv9a6OCpJYm0g_50, TM__n49a9aYp5BrbXv9a6OCpJYm0g_51, TM__n49a9aYp5BrbXv9a6OCpJYm0g_52);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__typemappingtestlib_u210202)(tySequence__H8X9cWYQfMAZrLe79b7JNPrA x_p0, NimStringV2 prefix_p1, NimStringV2 separator_p2, NimStringV2 suffix_p3) {
	NimStringV2 result;
	NIM_BOOL firstElement_1;
NIM_BOOL* nimErr_;
	nimfr_("collectionToString", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(1694, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	eqcopy___system_u2690((&result), prefix_p1);
	nimlf_(102, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");	firstElement_1 = NIM_TRUE;
	{
		tyObject_Inner__19bcVqla9cEhDUaCPb6ABKzg* value_1;
		NI i_1;
		NI L_1;
		NI T2_;
		value_1 = (tyObject_Inner__19bcVqla9cEhDUaCPb6ABKzg*)0;
		nimlf_(249, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T2_ = x_p0.len;
		L_1 = T2_;
		{
			nimln_(251);			while (1) {
				if (!(i_1 < L_1)) goto LA4;
				nimlf_(103, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");				value_1 = (&x_p0.p->data[i_1]);
				nimln_(104);				{
					if (!firstElement_1) goto LA7_;
					nimln_(105);					firstElement_1 = NIM_FALSE;
				}
				goto LA5_;
LA7_: ;
				{
					nimln_(107);					prepareAdd((&result), separator_p2.len + 0);
appendString((&result), separator_p2);
				}
LA5_: ;
				nimln_(116);				addQuoted__typemappingtestlib_u210235((&result), (&(*value_1)));
				nimlf_(13, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T12_;
					T12_ = x_p0.len;
					if (!!((T12_ == L_1))) goto LA13_;
					failedAssertImpl__stdZassertions_u234(TM__n49a9aYp5BrbXv9a6OCpJYm0g_53);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA13_: ;
			} LA4: ;
		}
	}
	nimlf_(117, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");	prepareAdd((&result), suffix_p3.len + 0);
appendString((&result), suffix_p3);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___typemappingtestlib_u210198)(tySequence__H8X9cWYQfMAZrLe79b7JNPrA x_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("$", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(133);	result = collectionToString__typemappingtestlib_u210202(x_p0, TM__n49a9aYp5BrbXv9a6OCpJYm0g_54, TM__n49a9aYp5BrbXv9a6OCpJYm0g_55, TM__n49a9aYp5BrbXv9a6OCpJYm0g_56);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__typemappingtestlib_u240077)(tyArray__sMpvt1sOxOJ3LFGulnbeMQ x_p0, NimStringV2 prefix_p1, NimStringV2 separator_p2, NimStringV2 suffix_p3) {
	NimStringV2 result;
	NIM_BOOL firstElement_1;
	nimfr_("collectionToString", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
	result.len = 0; result.p = NIM_NIL;
	nimlf_(1694, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	eqcopy___system_u2690((&result), prefix_p1);
	nimlf_(102, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");	firstElement_1 = NIM_TRUE;
	{
		NimStringV2 value_1;
		NI i_1;
		value_1.len = 0; value_1.p = NIM_NIL;
		nimlf_(43, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");		i_1 = ((NI)0);
		{
			nimln_(44);			while (1) {
				nimlf_(103, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");				value_1 = x_p0[(i_1)- 0];
				nimln_(104);				{
					if (!firstElement_1) goto LA6_;
					nimln_(105);					firstElement_1 = NIM_FALSE;
				}
				goto LA4_;
LA6_: ;
				{
					nimln_(107);					prepareAdd((&result), separator_p2.len + 0);
appendString((&result), separator_p2);
				}
LA4_: ;
				nimln_(116);				addQuoted__stdZprivateZoscommon_u119((&result), value_1);
				nimlf_(46, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");				{
					if (!(((NI)3) <= i_1)) goto LA11_;
					goto LA2;
				}
LA11_: ;
				nimln_(13);				i_1 += ((NI)1);
			}
		} LA2: ;
	}
	nimlf_(117, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");	prepareAdd((&result), suffix_p3.len + 0);
appendString((&result), suffix_p3);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___typemappingtestlib_u240072)(tyArray__sMpvt1sOxOJ3LFGulnbeMQ x_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("$", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(149);	result = collectionToString__typemappingtestlib_u240077(x_p0, TM__n49a9aYp5BrbXv9a6OCpJYm0g_57, TM__n49a9aYp5BrbXv9a6OCpJYm0g_58, TM__n49a9aYp5BrbXv9a6OCpJYm0g_59);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u44)(NU8 xX60gensym6__p0) {
	NimStringV2 result;
	nimfr_("$", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
	nimln_(20);	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_60;
	nimln_(21);	addInt__stdZprivateZdigitsutils_u184((&result), ((NU64) (xX60gensym6__p0)));
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__typemappingtestlib_u290392)(tyArray__AD3pyqDtyjQC8FAANmU6YA x_p0, NimStringV2 prefix_p1, NimStringV2 separator_p2, NimStringV2 suffix_p3) {
	NimStringV2 result;
	NIM_BOOL firstElement_1;
	nimfr_("collectionToString", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
	result.len = 0; result.p = NIM_NIL;
	nimlf_(1694, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	eqcopy___system_u2690((&result), prefix_p1);
	nimlf_(102, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");	firstElement_1 = NIM_TRUE;
	{
		tyObject_Slot__MGNwRgf3rnJeBHvV3ZG4Ew value_1;
		NI i_1;
		nimZeroMem((void*)(&value_1), sizeof(tyObject_Slot__MGNwRgf3rnJeBHvV3ZG4Ew));
		nimlf_(43, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");		i_1 = ((NI)0);
		{
			nimln_(44);			while (1) {
				nimlf_(103, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");				value_1 = x_p0[(i_1)- 0];
				nimln_(104);				{
					if (!firstElement_1) goto LA6_;
					nimln_(105);					firstElement_1 = NIM_FALSE;
				}
				goto LA4_;
LA6_: ;
				{
					nimln_(107);					prepareAdd((&result), separator_p2.len + 0);
appendString((&result), separator_p2);
				}
LA4_: ;
				nimln_(116);				addQuoted__typemappingtestlib_u290475((&result), value_1);
				nimlf_(46, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators.nim");				{
					if (!(((NI)3) <= i_1)) goto LA11_;
					goto LA2;
				}
LA11_: ;
				nimln_(13);				i_1 += ((NI)1);
			}
		} LA2: ;
	}
	nimlf_(117, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");	prepareAdd((&result), suffix_p3.len + 0);
appendString((&result), suffix_p3);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___typemappingtestlib_u290387)(tyArray__AD3pyqDtyjQC8FAANmU6YA x_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("$", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(149);	result = collectionToString__typemappingtestlib_u290392(x_p0, TM__n49a9aYp5BrbXv9a6OCpJYm0g_61, TM__n49a9aYp5BrbXv9a6OCpJYm0g_62, TM__n49a9aYp5BrbXv9a6OCpJYm0g_63);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u54)(NU32 xX60gensym8__p0) {
	NimStringV2 result;
	nimfr_("$", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
	nimln_(20);	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_64;
	nimln_(21);	addInt__stdZprivateZdigitsutils_u184((&result), ((NU64) (xX60gensym8__p0)));
	popFrame();
	return result;
}
static N_INLINE(void, addFloat__system_u5022)(NimStringV2* result_p0, NF x_p1) {
NIM_BOOL* nimErr_;
	nimfr_("addFloat", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/std/formatfloat.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(142, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/std/formatfloat.nim");	addFloatRoundtrip__system_u5027(result_p0, x_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___system_u5018)(NF x_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("$", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(14, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/dollars.nim");	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_65;
	nimln_(15);	addFloat__system_u5022((&result), x_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
