/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c -w -ferror-limit=3 -pthread --coverage -O0 -g   -I/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib -I/Users/schwarzy/dev/status/nim-brokers/test -o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_multi_thread_event_broker/@m..@snimbledeps@spkgs2@schronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0@schronos@stimer.nim.c.o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_multi_thread_event_broker/@m..@snimbledeps@spkgs2@schronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0@schronos@stimer.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <mach/mach_time.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_Duration__3dlH8Cls4pe581v9a0y69cfA tyObject_Duration__3dlH8Cls4pe581v9a0y69cfA;
struct tyObject_Duration__3dlH8Cls4pe581v9a0y69cfA {
	NI64 value;
};
N_LIB_PRIVATE N_NIMCALL(void, setupQueryFrequence__pkgZchronosZtimer_u6)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4709)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE NIM_CONST tyObject_Duration__3dlH8Cls4pe581v9a0y69cfA Millisecond__pkgZchronosZtimer_u189 = {IL64(1000000)}
;
N_LIB_PRIVATE NIM_CONST tyObject_Duration__3dlH8Cls4pe581v9a0y69cfA Second__pkgZchronosZtimer_u194 = {IL64(1000000000)}
;
N_LIB_PRIVATE NIM_CONST tyObject_Duration__3dlH8Cls4pe581v9a0y69cfA Microsecond__pkgZchronosZtimer_u184 = {IL64(1000)}
;
N_LIB_PRIVATE NIM_CONST tyObject_Duration__3dlH8Cls4pe581v9a0y69cfA InfiniteDuration__pkgZchronosZtimer_u220 = {IL64(9223372036854775807)}
;
N_LIB_PRIVATE NU64 queryFrequencyN__pkgZchronosZtimer_u4;
N_LIB_PRIVATE NU64 queryFrequencyD__pkgZchronosZtimer_u5;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4491;
extern NIM_THREADVAR TFrame* framePtr__system_u2723;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4491);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2723;
	framePtr__system_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2723 = (*framePtr__system_u2723).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, setupQueryFrequence__pkgZchronosZtimer_u6)(void) {
	struct mach_timebase_info info_1;
	nimfr_("setupQueryFrequence", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/timer.nim");
	nimZeroMem((void*)(&info_1), sizeof(struct mach_timebase_info));
	nimlf_(95, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/timer.nim");	mach_timebase_info((&info_1));
	nimln_(96);	queryFrequencyN__pkgZchronosZtimer_u4 = ((NU64) (info_1.numer));
	nimln_(97);	queryFrequencyD__pkgZchronosZtimer_u5 = ((NU64) (info_1.denom));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsnimbledepsatspkgs2atschronosminus4dot2dot2minus3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0atschronosatstimerdotnim_Init000)(void) {
{
NIM_BOOL* nimErr_;
	nimfr_("timer", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/timer.nim");
nimErr_ = nimErrorFlag();
	nimln_(108);	setupQueryFrequence__pkgZchronosZtimer_u6();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

