/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c -w -ferror-limit=3 -pthread --coverage -O0 -g   -I/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib -I/Users/schwarzy/dev/status/nim-brokers/test -o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_request_broker/@m..@snimbledeps@spkgs2@schronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0@schronos@sinternal@sraisesfutures.nim.c.o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_request_broker/@m..@snimbledeps@spkgs2@schronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0@schronos@sinternal@sraisesfutures.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_InternalRaisesFuturecolonObjectType___SQDbLGzTGOijuPWYJz138A tyObject_InternalRaisesFuturecolonObjectType___SQDbLGzTGOijuPWYJz138A;
typedef struct tyObject_RefHeader__NAPDH7sACblsOTVcfakTnQ tyObject_RefHeader__NAPDH7sACblsOTVcfakTnQ;
typedef struct tyObject_FuturecolonObjectType___CSw8mqrd1b1cLPwv9ccfRsg tyObject_FuturecolonObjectType___CSw8mqrd1b1cLPwv9ccfRsg;
typedef struct tyObject_FutureBasecolonObjectType___9cdiQNqls2MBAt6EhmH3avg tyObject_FutureBasecolonObjectType___9cdiQNqls2MBAt6EhmH3avg;
typedef struct tyObject_InternalFutureBase__ax9axwVWW6lk9bWWFxAHZKtw tyObject_InternalFutureBase__ax9axwVWW6lk9bWWFxAHZKtw;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w;
typedef struct tyObject_InternalAsyncCallback__cLwUl9b3ZR9aIil1o2Lx10uA tyObject_InternalAsyncCallback__cLwUl9b3ZR9aIil1o2Lx10uA;
typedef struct tySequence__Lgv3OlQYuBdvLg8T4gJQNQ tySequence__Lgv3OlQYuBdvLg8T4gJQNQ;
typedef struct tySequence__Lgv3OlQYuBdvLg8T4gJQNQ_Content tySequence__Lgv3OlQYuBdvLg8T4gJQNQ_Content;
typedef struct tyObject_CatchableError__XA9bz7HZj2bi11i9ceCxY6zA tyObject_CatchableError__XA9bz7HZj2bi11i9ceCxY6zA;
typedef struct tyObject_Result__w3u8qHJIT9ctOENJRa82CxA tyObject_Result__w3u8qHJIT9ctOENJRa82CxA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_SimpleResponse__EqgnHVED2eEzIifA6fT9awg tyObject_SimpleResponse__EqgnHVED2eEzIifA6fT9awg;
typedef struct tyObject_GcEnv__xUe1WjS3VG2s19bBTOaluLQ tyObject_GcEnv__xUe1WjS3VG2s19bBTOaluLQ;
typedef struct tyObject_CellSeq__Sktzxr2TNnrfnmWar1s4Sw tyObject_CellSeq__Sktzxr2TNnrfnmWar1s4Sw;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__VLzWpdA4OEcvumuc6DSwjw tyObject_CellSeq__VLzWpdA4OEcvumuc6DSwjw;
typedef struct tyTuple__ZiSL9aqBTKXK9b9buyxeDR9b6Q tyTuple__ZiSL9aqBTKXK9b9buyxeDR9b6Q;
typedef struct tyObject_InternalRaisesFuturecolonObjectType___12qbKBz0CeEkhm8GvJKkXw tyObject_InternalRaisesFuturecolonObjectType___12qbKBz0CeEkhm8GvJKkXw;
typedef struct tyObject_FuturecolonObjectType___vl8bCzBEmojiPGrZA9bGwUQ tyObject_FuturecolonObjectType___vl8bCzBEmojiPGrZA9bGwUQ;
typedef struct tyObject_Result__UeTGBXHHeCiXCz0CdmzTmA tyObject_Result__UeTGBXHHeCiXCz0CdmzTmA;
typedef struct tyObject_KeyedResponse__eR44qwOrQdz79bAv79cGTB7w tyObject_KeyedResponse__eR44qwOrQdz79bAv79cGTB7w;
typedef struct tyObject_InternalRaisesFuturecolonObjectType___4lMeq9c9cU7r4quQUnw4gyNg tyObject_InternalRaisesFuturecolonObjectType___4lMeq9c9cU7r4quQUnw4gyNg;
typedef struct tyObject_FuturecolonObjectType___mW2FJ1U1d0zIyl9cGkOKwrg tyObject_FuturecolonObjectType___mW2FJ1U1d0zIyl9cGkOKwrg;
typedef struct tyObject_Result__LPMxxgP8qNproVSdwrFqFQ tyObject_Result__LPMxxgP8qNproVSdwrFqFQ;
typedef struct tyObject_DualResponse__PUuzjtNe1wlkrPwNh51SlQ tyObject_DualResponse__PUuzjtNe1wlkrPwNh51SlQ;
typedef struct tyObject_InternalRaisesFuturecolonObjectType___tMvhnBXZ682BZdr1U7YI8Q tyObject_InternalRaisesFuturecolonObjectType___tMvhnBXZ682BZdr1U7YI8Q;
typedef struct tyObject_FuturecolonObjectType___Y9brXoUcNJTNs89aBWpuTcFg tyObject_FuturecolonObjectType___Y9brXoUcNJTNs89aBWpuTcFg;
typedef struct tyObject_Result__0q5g6879c6SWwHqR3Dyne8Q tyObject_Result__0q5g6879c6SWwHqR3Dyne8Q;
typedef struct tyObject_ImplicitResponsecolonObjectType___X69ax9cviUZqoMkl4Ja79cF8A tyObject_ImplicitResponsecolonObjectType___X69ax9cviUZqoMkl4Ja79cF8A;
typedef struct tyObject_InternalRaisesFuturecolonObjectType___iJhZ65KYq3ODiWYDi6IbdQ tyObject_InternalRaisesFuturecolonObjectType___iJhZ65KYq3ODiWYDi6IbdQ;
typedef struct tyObject_FuturecolonObjectType___89aYlWpPpO2dsOTz9bdyu9btQ tyObject_FuturecolonObjectType___89aYlWpPpO2dsOTz9bdyu9btQ;
typedef struct tyObject_Result__3r7fRfu6dvlxWqMK5SU7Bw tyObject_Result__3r7fRfu6dvlxWqMK5SU7Bw;
typedef struct tyObject_InternalRaisesFuturecolonObjectType___Nar6R6CjP79aWOhy58WVmHQ tyObject_InternalRaisesFuturecolonObjectType___Nar6R6CjP79aWOhy58WVmHQ;
typedef struct tyObject_FuturecolonObjectType___vUgc7BE19bNQCJ8IVHASDZA tyObject_FuturecolonObjectType___vUgc7BE19bNQCJ8IVHASDZA;
typedef struct tyObject_Result__sO5H5JX3RGqq2GhpWqp4wQ tyObject_Result__sO5H5JX3RGqq2GhpWqp4wQ;
typedef struct tyObject_ExternalDefinedTypeAsync__CpneHmlk4o8oC9b2kO2hf0Q tyObject_ExternalDefinedTypeAsync__CpneHmlk4o8oC9b2kO2hf0Q;
typedef struct tyObject_InternalRaisesFuturecolonObjectType___Z9ajIPm3KTYwBZB77zhL2NQ tyObject_InternalRaisesFuturecolonObjectType___Z9ajIPm3KTYwBZB77zhL2NQ;
typedef struct tyObject_FuturecolonObjectType___34FMB88dEGt8PxUDGKmk0w tyObject_FuturecolonObjectType___34FMB88dEGt8PxUDGKmk0w;
typedef struct tyObject_Result__dQRs9bwm0pMINz9aZvbQt9beg tyObject_Result__dQRs9bwm0pMINz9aZvbQt9beg;
typedef struct tyObject_VoidActionAsync__0cQWU8hVccWl8BUEV3HjuQ tyObject_VoidActionAsync__0cQWU8hVccWl8BUEV3HjuQ;
typedef struct tyObject_InternalRaisesFuturecolonObjectType___7uNr9aylZIyEHIrSmujm5Uw tyObject_InternalRaisesFuturecolonObjectType___7uNr9aylZIyEHIrSmujm5Uw;
typedef struct tyObject_FuturecolonObjectType___o5ddCmvgMRBth1G9bO9b65GQ tyObject_FuturecolonObjectType___o5ddCmvgMRBth1G9bO9b65GQ;
typedef struct tyObject_Result__vw6lsycvvuBMqo9cyVwe9cTw tyObject_Result__vw6lsycvvuBMqo9cyVwe9cTw;
typedef struct tyObject_VoidActionZeroArg__E9c9bJkseRBx9cSrRVwjHzerw tyObject_VoidActionZeroArg__E9c9bJkseRBx9cSrRVwjHzerw;
typedef struct tyObject_InternalRaisesFuturecolonObjectType___ssVEhm1bgZLDdWg4Kq9cdtg tyObject_InternalRaisesFuturecolonObjectType___ssVEhm1bgZLDdWg4Kq9cdtg;
typedef struct tyObject_FuturecolonObjectType___JE6lxXorB3I5p9cwd9bmOkpw tyObject_FuturecolonObjectType___JE6lxXorB3I5p9cwd9bmOkpw;
typedef struct tyObject_Result__lRIJHt83bu8ekc73M9cJVdQ tyObject_Result__lRIJHt83bu8ekc73M9cJVdQ;
struct tyObject_RefHeader__NAPDH7sACblsOTVcfakTnQ {
	NI rc;
	NI rootIdx;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
typedef tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* tyArray__A3Z4ps6fKwEa8vMDLmwVYw[2];
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* arg_p0, void* ClE_0);
void* ClE_0;
} tyProc__uMUlmGrxGbyKfim0kpddgQ;
struct tyObject_InternalAsyncCallback__cLwUl9b3ZR9aIil1o2Lx10uA {
	tyProc__uMUlmGrxGbyKfim0kpddgQ function;
	void* udata;
};
struct tySequence__Lgv3OlQYuBdvLg8T4gJQNQ {
  NI len; tySequence__Lgv3OlQYuBdvLg8T4gJQNQ_Content* p;
};
typedef NU8 tyEnum_FutureState__NICieFPj9c4S1oLMBQwd5HA;
typedef NU8 tySet_tyEnum_FutureFlag__qyrQJF9bT7DpWbFLs4DFeIw;
typedef struct {
N_NIMCALL_PTR(tyObject_FutureBasecolonObjectType___9cdiQNqls2MBAt6EhmH3avg*, ClP_0) (tyObject_FutureBasecolonObjectType___9cdiQNqls2MBAt6EhmH3avg* f_p0, void* ClE_0);
void* ClE_0;
} tyProc__SGDcBedoNCKAkvnXC69cY3A;
struct tyObject_InternalFutureBase__ax9axwVWW6lk9bWWFxAHZKtw {
	RootObj Sup;
	tyArray__A3Z4ps6fKwEa8vMDLmwVYw internalLocation;
	tyObject_InternalAsyncCallback__cLwUl9b3ZR9aIil1o2Lx10uA internalCallback;
	tySequence__Lgv3OlQYuBdvLg8T4gJQNQ internalCallbacks;
	tyProc__uMUlmGrxGbyKfim0kpddgQ internalCancelcb;
	tyObject_FutureBasecolonObjectType___9cdiQNqls2MBAt6EhmH3avg* internalChild;
	tyEnum_FutureState__NICieFPj9c4S1oLMBQwd5HA internalState;
	tySet_tyEnum_FutureFlag__qyrQJF9bT7DpWbFLs4DFeIw internalFlags;
	tyObject_CatchableError__XA9bz7HZj2bi11i9ceCxY6zA* internalError;
	tyProc__SGDcBedoNCKAkvnXC69cY3A internalClosure;
};
struct tyObject_FutureBasecolonObjectType___9cdiQNqls2MBAt6EhmH3avg {
	tyObject_InternalFutureBase__ax9axwVWW6lk9bWWFxAHZKtw Sup;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_SimpleResponse__EqgnHVED2eEzIifA6fT9awg {
	NimStringV2 value;
};
struct tyObject_Result__w3u8qHJIT9ctOENJRa82CxA {
	NIM_BOOL oResultPrivate;
union{
	struct {
	NimStringV2 eResultPrivate;
} _oResultPrivate_1;
	struct {
	tyObject_SimpleResponse__EqgnHVED2eEzIifA6fT9awg vResultPrivate;
} _oResultPrivate_2;
};
};
struct tyObject_FuturecolonObjectType___CSw8mqrd1b1cLPwv9ccfRsg {
	tyObject_FutureBasecolonObjectType___9cdiQNqls2MBAt6EhmH3avg Sup;
	tyObject_Result__w3u8qHJIT9ctOENJRa82CxA internalValue;
};
struct tyObject_InternalRaisesFuturecolonObjectType___SQDbLGzTGOijuPWYJz138A {
	tyObject_FuturecolonObjectType___CSw8mqrd1b1cLPwv9ccfRsg Sup;
};
struct tyObject_CellSeq__Sktzxr2TNnrfnmWar1s4Sw {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__VLzWpdA4OEcvumuc6DSwjw {
	NI len;
	NI cap;
	tyTuple__ZiSL9aqBTKXK9b9buyxeDR9b6Q* d;
};
struct tyObject_GcEnv__xUe1WjS3VG2s19bBTOaluLQ {
	tyObject_CellSeq__Sktzxr2TNnrfnmWar1s4Sw traceStack;
	tyObject_CellSeq__VLzWpdA4OEcvumuc6DSwjw toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
struct tyObject_KeyedResponse__eR44qwOrQdz79bAv79cGTB7w {
	NimStringV2 key;
	NimStringV2 payload;
};
struct tyObject_Result__UeTGBXHHeCiXCz0CdmzTmA {
	NIM_BOOL oResultPrivate;
union{
	struct {
	NimStringV2 eResultPrivate;
} _oResultPrivate_1;
	struct {
	tyObject_KeyedResponse__eR44qwOrQdz79bAv79cGTB7w vResultPrivate;
} _oResultPrivate_2;
};
};
struct tyObject_FuturecolonObjectType___vl8bCzBEmojiPGrZA9bGwUQ {
	tyObject_FutureBasecolonObjectType___9cdiQNqls2MBAt6EhmH3avg Sup;
	tyObject_Result__UeTGBXHHeCiXCz0CdmzTmA internalValue;
};
struct tyObject_InternalRaisesFuturecolonObjectType___12qbKBz0CeEkhm8GvJKkXw {
	tyObject_FuturecolonObjectType___vl8bCzBEmojiPGrZA9bGwUQ Sup;
};
struct tyObject_DualResponse__PUuzjtNe1wlkrPwNh51SlQ {
	NimStringV2 note;
	NI count;
};
struct tyObject_Result__LPMxxgP8qNproVSdwrFqFQ {
	NIM_BOOL oResultPrivate;
union{
	struct {
	NimStringV2 eResultPrivate;
} _oResultPrivate_1;
	struct {
	tyObject_DualResponse__PUuzjtNe1wlkrPwNh51SlQ vResultPrivate;
} _oResultPrivate_2;
};
};
struct tyObject_FuturecolonObjectType___mW2FJ1U1d0zIyl9cGkOKwrg {
	tyObject_FutureBasecolonObjectType___9cdiQNqls2MBAt6EhmH3avg Sup;
	tyObject_Result__LPMxxgP8qNproVSdwrFqFQ internalValue;
};
struct tyObject_InternalRaisesFuturecolonObjectType___4lMeq9c9cU7r4quQUnw4gyNg {
	tyObject_FuturecolonObjectType___mW2FJ1U1d0zIyl9cGkOKwrg Sup;
};
struct tyObject_Result__0q5g6879c6SWwHqR3Dyne8Q {
	NIM_BOOL oResultPrivate;
union{
	struct {
	NimStringV2 eResultPrivate;
} _oResultPrivate_1;
	struct {
	tyObject_ImplicitResponsecolonObjectType___X69ax9cviUZqoMkl4Ja79cF8A* vResultPrivate;
} _oResultPrivate_2;
};
};
struct tyObject_FuturecolonObjectType___Y9brXoUcNJTNs89aBWpuTcFg {
	tyObject_FutureBasecolonObjectType___9cdiQNqls2MBAt6EhmH3avg Sup;
	tyObject_Result__0q5g6879c6SWwHqR3Dyne8Q internalValue;
};
struct tyObject_InternalRaisesFuturecolonObjectType___tMvhnBXZ682BZdr1U7YI8Q {
	tyObject_FuturecolonObjectType___Y9brXoUcNJTNs89aBWpuTcFg Sup;
};
struct tyObject_Result__3r7fRfu6dvlxWqMK5SU7Bw {
	NIM_BOOL oResultPrivate;
union{
	struct {
	NimStringV2 eResultPrivate;
} _oResultPrivate_1;
	struct {
	NI vResultPrivate;
} _oResultPrivate_2;
};
};
struct tyObject_FuturecolonObjectType___89aYlWpPpO2dsOTz9bdyu9btQ {
	tyObject_FutureBasecolonObjectType___9cdiQNqls2MBAt6EhmH3avg Sup;
	tyObject_Result__3r7fRfu6dvlxWqMK5SU7Bw internalValue;
};
struct tyObject_InternalRaisesFuturecolonObjectType___iJhZ65KYq3ODiWYDi6IbdQ {
	tyObject_FuturecolonObjectType___89aYlWpPpO2dsOTz9bdyu9btQ Sup;
};
struct tyObject_ExternalDefinedTypeAsync__CpneHmlk4o8oC9b2kO2hf0Q {
	NimStringV2 label;
};
struct tyObject_Result__sO5H5JX3RGqq2GhpWqp4wQ {
	NIM_BOOL oResultPrivate;
union{
	struct {
	NimStringV2 eResultPrivate;
} _oResultPrivate_1;
	struct {
	tyObject_ExternalDefinedTypeAsync__CpneHmlk4o8oC9b2kO2hf0Q vResultPrivate;
} _oResultPrivate_2;
};
};
struct tyObject_FuturecolonObjectType___vUgc7BE19bNQCJ8IVHASDZA {
	tyObject_FutureBasecolonObjectType___9cdiQNqls2MBAt6EhmH3avg Sup;
	tyObject_Result__sO5H5JX3RGqq2GhpWqp4wQ internalValue;
};
struct tyObject_InternalRaisesFuturecolonObjectType___Nar6R6CjP79aWOhy58WVmHQ {
	tyObject_FuturecolonObjectType___vUgc7BE19bNQCJ8IVHASDZA Sup;
};
struct tyObject_VoidActionAsync__0cQWU8hVccWl8BUEV3HjuQ {
	char dummy;
};
struct tyObject_Result__dQRs9bwm0pMINz9aZvbQt9beg {
	NIM_BOOL oResultPrivate;
union{
	struct {
	NimStringV2 eResultPrivate;
} _oResultPrivate_1;
	struct {
	tyObject_VoidActionAsync__0cQWU8hVccWl8BUEV3HjuQ vResultPrivate;
} _oResultPrivate_2;
};
};
struct tyObject_FuturecolonObjectType___34FMB88dEGt8PxUDGKmk0w {
	tyObject_FutureBasecolonObjectType___9cdiQNqls2MBAt6EhmH3avg Sup;
	tyObject_Result__dQRs9bwm0pMINz9aZvbQt9beg internalValue;
};
struct tyObject_InternalRaisesFuturecolonObjectType___Z9ajIPm3KTYwBZB77zhL2NQ {
	tyObject_FuturecolonObjectType___34FMB88dEGt8PxUDGKmk0w Sup;
};
struct tyObject_VoidActionZeroArg__E9c9bJkseRBx9cSrRVwjHzerw {
	char dummy;
};
struct tyObject_Result__vw6lsycvvuBMqo9cyVwe9cTw {
	NIM_BOOL oResultPrivate;
union{
	struct {
	NimStringV2 eResultPrivate;
} _oResultPrivate_1;
	struct {
	tyObject_VoidActionZeroArg__E9c9bJkseRBx9cSrRVwjHzerw vResultPrivate;
} _oResultPrivate_2;
};
};
struct tyObject_FuturecolonObjectType___o5ddCmvgMRBth1G9bO9b65GQ {
	tyObject_FutureBasecolonObjectType___9cdiQNqls2MBAt6EhmH3avg Sup;
	tyObject_Result__vw6lsycvvuBMqo9cyVwe9cTw internalValue;
};
struct tyObject_InternalRaisesFuturecolonObjectType___7uNr9aylZIyEHIrSmujm5Uw {
	tyObject_FuturecolonObjectType___o5ddCmvgMRBth1G9bO9b65GQ Sup;
};
struct tyObject_Result__lRIJHt83bu8ekc73M9cJVdQ {
	NIM_BOOL oResultPrivate;
union{
	struct {
	NimStringV2 eResultPrivate;
} _oResultPrivate_1;
};
};
struct tyObject_FuturecolonObjectType___JE6lxXorB3I5p9cwd9bmOkpw {
	tyObject_FutureBasecolonObjectType___9cdiQNqls2MBAt6EhmH3avg Sup;
	tyObject_Result__lRIJHt83bu8ekc73M9cJVdQ internalValue;
};
struct tyObject_InternalRaisesFuturecolonObjectType___ssVEhm1bgZLDdWg4Kq9cdtg {
	tyObject_FuturecolonObjectType___JE6lxXorB3I5p9cwd9bmOkpw Sup;
};
struct tySequence__Lgv3OlQYuBdvLg8T4gJQNQ_Content { NI cap; tyObject_InternalAsyncCallback__cLwUl9b3ZR9aIil1o2Lx10uA data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4709)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3528)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__NAPDH7sACblsOTVcfakTnQ* s_p1, TNimTypeV2* desc_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u3279)(tyObject_InternalRaisesFuturecolonObjectType___SQDbLGzTGOijuPWYJz138A* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZchronosZinternalZasyncengine_u1488)(tySequence__Lgv3OlQYuBdvLg8T4gJQNQ dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u3011)(tyObject_CellSeq__Sktzxr2TNnrfnmWar1s4Sw* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u3019)(tyObject_CellSeq__Sktzxr2TNnrfnmWar1s4Sw* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pkgZchronosZinternalZasyncengine_u1500)(tySequence__Lgv3OlQYuBdvLg8T4gJQNQ* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u5950)(tyObject_InternalRaisesFuturecolonObjectType___12qbKBz0CeEkhm8GvJKkXw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u9179)(tyObject_InternalRaisesFuturecolonObjectType___4lMeq9c9cU7r4quQUnw4gyNg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u13757)(tyObject_InternalRaisesFuturecolonObjectType___tMvhnBXZ682BZdr1U7YI8Q* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u12640)(tyObject_ImplicitResponsecolonObjectType___X69ax9cviUZqoMkl4Ja79cF8A* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u32254)(tyObject_InternalRaisesFuturecolonObjectType___iJhZ65KYq3ODiWYDi6IbdQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u34073)(tyObject_InternalRaisesFuturecolonObjectType___Nar6R6CjP79aWOhy58WVmHQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u39835)(tyObject_InternalRaisesFuturecolonObjectType___Z9ajIPm3KTYwBZB77zhL2NQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u42637)(tyObject_InternalRaisesFuturecolonObjectType___7uNr9aylZIyEHIrSmujm5Uw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u46028)(tyObject_InternalRaisesFuturecolonObjectType___ssVEhm1bgZLDdWg4Kq9cdtg* dest_p0);
extern NIM_THREADVAR TFrame* framePtr__system_u2723;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4491;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2723;
	framePtr__system_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2723 = (*framePtr__system_u2723).prev;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/arithmetics.nim");
	nimlf_(364, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/arithmetics.nim");	nimln_(368);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimIncRefCyclic)(void* p_p0, NIM_BOOL cyclic_p1) {
	tyObject_RefHeader__NAPDH7sACblsOTVcfakTnQ* h_1;
	NI T1_;
	NI TM__nQWC85g4VEu62NqZPR4r0g_2;
	nimfr_("nimIncRefCyclic", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/orc.nim");
{	nimlf_(45, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/orc.nim");	nimlf_(58, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/arc.nim");	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	h_1 = ((tyObject_RefHeader__NAPDH7sACblsOTVcfakTnQ*) (T1_));
	nimlf_(46, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/orc.nim");	if (nimAddInt((*h_1).rc, ((NI)16), &TM__nQWC85g4VEu62NqZPR4r0g_2)) { raiseOverflow(); goto BeforeRet_;
	};
	(*h_1).rc = (NI)(TM__nQWC85g4VEu62NqZPR4r0g_2);
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4491);
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("nimDecRefIsLastCyclicDyn", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/orc.nim");
{nimErr_ = nimErrorFlag();
	nimln_(512);	result = NIM_FALSE;
	nimln_(513);	{
		tyObject_RefHeader__NAPDH7sACblsOTVcfakTnQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(514);		nimlf_(58, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__NAPDH7sACblsOTVcfakTnQ*) (T5_));
		nimlf_(515, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(516);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			NI TM__nQWC85g4VEu62NqZPR4r0g_3;
			nimln_(519);			if (nimSubInt((*cell_1).rc, ((NI)16), &TM__nQWC85g4VEu62NqZPR4r0g_3)) { raiseOverflow(); goto BeforeRet_;
			};
			(*cell_1).rc = (NI)(TM__nQWC85g4VEu62NqZPR4r0g_3);
		}
LA6_: ;
		nimln_(521);		rememberCycle__system_u3528(result, cell_1, (*((TNimTypeV2**) (p_p0))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___test95request95broker_u3262)(tyObject_InternalRaisesFuturecolonObjectType___SQDbLGzTGOijuPWYJz138A** dest_p0, tyObject_InternalRaisesFuturecolonObjectType___SQDbLGzTGOijuPWYJz138A* src_p1, NIM_BOOL cyclic_p2) {
	tyObject_InternalRaisesFuturecolonObjectType___SQDbLGzTGOijuPWYJz138A* colontmp_;
	colontmp_ = (*dest_p0);
	{
		if (!src_p1) goto LA3_;
		nimIncRefCyclic(src_p1, cyclic_p2);
	}
LA3_: ;
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose(colontmp_);
	}
LA8_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u3259)(tyObject_InternalRaisesFuturecolonObjectType___SQDbLGzTGOijuPWYJz138A* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(dest_p0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(dest_p0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u3279)(tyObject_InternalRaisesFuturecolonObjectType___SQDbLGzTGOijuPWYJz138A* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0);
	}
LA4_: ;
	eqdestroy___pkgZchronosZinternalZasyncengine_u1488((*dest_p0).Sup.Sup.Sup.internalCallbacks);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0);
	}
LA9_: ;
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalChild);
		if (!T13_) goto LA14_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalChild);
	}
LA14_: ;
	{
		NIM_BOOL T18_;
		T18_ = (NIM_BOOL)0;
		T18_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalError);
		if (!T18_) goto LA19_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalError);
	}
LA19_: ;
	{
		NIM_BOOL T23_;
		T23_ = (NIM_BOOL)0;
		T23_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0);
		if (!T23_) goto LA24_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0);
	}
LA24_: ;
	switch ((*dest_p0).Sup.internalValue.oResultPrivate) {
	case NIM_FALSE:
	{
		if ((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p && !((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p);
}
	}
	break;
	case NIM_TRUE:
	{
		if ((*dest_p0).Sup.internalValue._oResultPrivate_2.vResultPrivate.value.p && !((*dest_p0).Sup.internalValue._oResultPrivate_2.vResultPrivate.value.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.internalValue._oResultPrivate_2.vResultPrivate.value.p);
}
	}
	break;
	default:
	{
	}
	break;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__test95request95broker_u48105)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___test95request95broker_u3279(((tyObject_InternalRaisesFuturecolonObjectType___SQDbLGzTGOijuPWYJz138A*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, add__system_u3011)(tyObject_CellSeq__Sktzxr2TNnrfnmWar1s4Sw* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	NI TM__nQWC85g4VEu62NqZPR4r0g_4;
	nimfr_("add", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/cellseqs_v2.nim");
{	nimlf_(28, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/cellseqs_v2.nim");	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		nimln_(29);		resize__system_u3019(s_p0);
	}
LA3_: ;
	nimln_(30);	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	nimln_(31);	if (nimAddInt((*s_p0).len, ((NI)1), &TM__nQWC85g4VEu62NqZPR4r0g_4)) { raiseOverflow(); goto BeforeRet_;
	};
	(*s_p0).len = (NI)(TM__nQWC85g4VEu62NqZPR4r0g_4);
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	nimfr_("nimTraceRefDyn", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/orc.nim");
	nimlf_(136, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/orc.nim");	p_1 = ((void**) (q_p0));
	nimln_(137);	{
		tyObject_GcEnv__xUe1WjS3VG2s19bBTOaluLQ* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		nimln_(138);		j_1 = ((tyObject_GcEnv__xUe1WjS3VG2s19bBTOaluLQ*) (env_p1));
		nimln_(139);		add__system_u3011((&(*j_1).traceStack), p_1, (*((TNimTypeV2**) ((*p_1)))));
	}
LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___test95request95broker_u3291)(tyObject_InternalRaisesFuturecolonObjectType___SQDbLGzTGOijuPWYJz138A* dest_p0, void* env_p1) {
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0), env_p1);
	eqtrace___pkgZchronosZinternalZasyncengine_u1500((&(*dest_p0).Sup.Sup.Sup.internalCallbacks), env_p1);
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0), env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.internalChild, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.internalError, env_p1);
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0), env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___test95request95broker_u3256)(tyObject_InternalRaisesFuturecolonObjectType___SQDbLGzTGOijuPWYJz138A** dest_p0) {
	(*dest_p0) = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___test95request95broker_u5933)(tyObject_InternalRaisesFuturecolonObjectType___12qbKBz0CeEkhm8GvJKkXw** dest_p0, tyObject_InternalRaisesFuturecolonObjectType___12qbKBz0CeEkhm8GvJKkXw* src_p1, NIM_BOOL cyclic_p2) {
	tyObject_InternalRaisesFuturecolonObjectType___12qbKBz0CeEkhm8GvJKkXw* colontmp_;
	colontmp_ = (*dest_p0);
	{
		if (!src_p1) goto LA3_;
		nimIncRefCyclic(src_p1, cyclic_p2);
	}
LA3_: ;
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose(colontmp_);
	}
LA8_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u5930)(tyObject_InternalRaisesFuturecolonObjectType___12qbKBz0CeEkhm8GvJKkXw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(dest_p0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(dest_p0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u5950)(tyObject_InternalRaisesFuturecolonObjectType___12qbKBz0CeEkhm8GvJKkXw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0);
	}
LA4_: ;
	eqdestroy___pkgZchronosZinternalZasyncengine_u1488((*dest_p0).Sup.Sup.Sup.internalCallbacks);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0);
	}
LA9_: ;
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalChild);
		if (!T13_) goto LA14_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalChild);
	}
LA14_: ;
	{
		NIM_BOOL T18_;
		T18_ = (NIM_BOOL)0;
		T18_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalError);
		if (!T18_) goto LA19_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalError);
	}
LA19_: ;
	{
		NIM_BOOL T23_;
		T23_ = (NIM_BOOL)0;
		T23_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0);
		if (!T23_) goto LA24_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0);
	}
LA24_: ;
	switch ((*dest_p0).Sup.internalValue.oResultPrivate) {
	case NIM_FALSE:
	{
		if ((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p && !((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p);
}
	}
	break;
	case NIM_TRUE:
	{
		if ((*dest_p0).Sup.internalValue._oResultPrivate_2.vResultPrivate.key.p && !((*dest_p0).Sup.internalValue._oResultPrivate_2.vResultPrivate.key.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.internalValue._oResultPrivate_2.vResultPrivate.key.p);
}
		if ((*dest_p0).Sup.internalValue._oResultPrivate_2.vResultPrivate.payload.p && !((*dest_p0).Sup.internalValue._oResultPrivate_2.vResultPrivate.payload.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.internalValue._oResultPrivate_2.vResultPrivate.payload.p);
}
	}
	break;
	default:
	{
	}
	break;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__test95request95broker_u48919)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___test95request95broker_u5950(((tyObject_InternalRaisesFuturecolonObjectType___12qbKBz0CeEkhm8GvJKkXw*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___test95request95broker_u5962)(tyObject_InternalRaisesFuturecolonObjectType___12qbKBz0CeEkhm8GvJKkXw* dest_p0, void* env_p1) {
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0), env_p1);
	eqtrace___pkgZchronosZinternalZasyncengine_u1500((&(*dest_p0).Sup.Sup.Sup.internalCallbacks), env_p1);
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0), env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.internalChild, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.internalError, env_p1);
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0), env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___test95request95broker_u5927)(tyObject_InternalRaisesFuturecolonObjectType___12qbKBz0CeEkhm8GvJKkXw** dest_p0) {
	(*dest_p0) = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___test95request95broker_u9162)(tyObject_InternalRaisesFuturecolonObjectType___4lMeq9c9cU7r4quQUnw4gyNg** dest_p0, tyObject_InternalRaisesFuturecolonObjectType___4lMeq9c9cU7r4quQUnw4gyNg* src_p1, NIM_BOOL cyclic_p2) {
	tyObject_InternalRaisesFuturecolonObjectType___4lMeq9c9cU7r4quQUnw4gyNg* colontmp_;
	colontmp_ = (*dest_p0);
	{
		if (!src_p1) goto LA3_;
		nimIncRefCyclic(src_p1, cyclic_p2);
	}
LA3_: ;
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose(colontmp_);
	}
LA8_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u9159)(tyObject_InternalRaisesFuturecolonObjectType___4lMeq9c9cU7r4quQUnw4gyNg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(dest_p0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(dest_p0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u9179)(tyObject_InternalRaisesFuturecolonObjectType___4lMeq9c9cU7r4quQUnw4gyNg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0);
	}
LA4_: ;
	eqdestroy___pkgZchronosZinternalZasyncengine_u1488((*dest_p0).Sup.Sup.Sup.internalCallbacks);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0);
	}
LA9_: ;
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalChild);
		if (!T13_) goto LA14_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalChild);
	}
LA14_: ;
	{
		NIM_BOOL T18_;
		T18_ = (NIM_BOOL)0;
		T18_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalError);
		if (!T18_) goto LA19_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalError);
	}
LA19_: ;
	{
		NIM_BOOL T23_;
		T23_ = (NIM_BOOL)0;
		T23_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0);
		if (!T23_) goto LA24_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0);
	}
LA24_: ;
	switch ((*dest_p0).Sup.internalValue.oResultPrivate) {
	case NIM_FALSE:
	{
		if ((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p && !((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p);
}
	}
	break;
	case NIM_TRUE:
	{
		if ((*dest_p0).Sup.internalValue._oResultPrivate_2.vResultPrivate.note.p && !((*dest_p0).Sup.internalValue._oResultPrivate_2.vResultPrivate.note.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.internalValue._oResultPrivate_2.vResultPrivate.note.p);
}
	}
	break;
	default:
	{
	}
	break;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__test95request95broker_u49867)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___test95request95broker_u9179(((tyObject_InternalRaisesFuturecolonObjectType___4lMeq9c9cU7r4quQUnw4gyNg*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___test95request95broker_u9191)(tyObject_InternalRaisesFuturecolonObjectType___4lMeq9c9cU7r4quQUnw4gyNg* dest_p0, void* env_p1) {
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0), env_p1);
	eqtrace___pkgZchronosZinternalZasyncengine_u1500((&(*dest_p0).Sup.Sup.Sup.internalCallbacks), env_p1);
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0), env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.internalChild, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.internalError, env_p1);
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0), env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___test95request95broker_u9156)(tyObject_InternalRaisesFuturecolonObjectType___4lMeq9c9cU7r4quQUnw4gyNg** dest_p0) {
	(*dest_p0) = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___test95request95broker_u13740)(tyObject_InternalRaisesFuturecolonObjectType___tMvhnBXZ682BZdr1U7YI8Q** dest_p0, tyObject_InternalRaisesFuturecolonObjectType___tMvhnBXZ682BZdr1U7YI8Q* src_p1, NIM_BOOL cyclic_p2) {
	tyObject_InternalRaisesFuturecolonObjectType___tMvhnBXZ682BZdr1U7YI8Q* colontmp_;
	colontmp_ = (*dest_p0);
	{
		if (!src_p1) goto LA3_;
		nimIncRefCyclic(src_p1, cyclic_p2);
	}
LA3_: ;
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose(colontmp_);
	}
LA8_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u13737)(tyObject_InternalRaisesFuturecolonObjectType___tMvhnBXZ682BZdr1U7YI8Q* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(dest_p0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(dest_p0);
	}
LA4_: ;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLast", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/arc.nim");
{	nimlf_(217, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/arc.nim");	result = NIM_FALSE;
	nimln_(218);	{
		tyObject_RefHeader__NAPDH7sACblsOTVcfakTnQ* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(219);		nimln_(58);		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__NAPDH7sACblsOTVcfakTnQ*) (T5_));
		nimln_(233);		{
			if (!((NI)((NI64)((*cell_1).rc) >> (NU64)(((NI)4))) == ((NI)0))) goto LA8_;
			nimln_(234);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			NI TM__nQWC85g4VEu62NqZPR4r0g_5;
			nimln_(238);			if (nimSubInt((*cell_1).rc, ((NI)16), &TM__nQWC85g4VEu62NqZPR4r0g_5)) { raiseOverflow(); goto BeforeRet_;
			};
			(*cell_1).rc = (NI)(TM__nQWC85g4VEu62NqZPR4r0g_5);
		}
LA6_: ;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u13757)(tyObject_InternalRaisesFuturecolonObjectType___tMvhnBXZ682BZdr1U7YI8Q* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0);
	}
LA4_: ;
	eqdestroy___pkgZchronosZinternalZasyncengine_u1488((*dest_p0).Sup.Sup.Sup.internalCallbacks);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0);
	}
LA9_: ;
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalChild);
		if (!T13_) goto LA14_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalChild);
	}
LA14_: ;
	{
		NIM_BOOL T18_;
		T18_ = (NIM_BOOL)0;
		T18_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalError);
		if (!T18_) goto LA19_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalError);
	}
LA19_: ;
	{
		NIM_BOOL T23_;
		T23_ = (NIM_BOOL)0;
		T23_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0);
		if (!T23_) goto LA24_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0);
	}
LA24_: ;
	switch ((*dest_p0).Sup.internalValue.oResultPrivate) {
	case NIM_FALSE:
	{
		if ((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p && !((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p);
}
	}
	break;
	case NIM_TRUE:
	{
		{
			NIM_BOOL T30_;
			T30_ = (NIM_BOOL)0;
			T30_ = nimDecRefIsLast((*dest_p0).Sup.internalValue._oResultPrivate_2.vResultPrivate);
			if (!T30_) goto LA31_;
			eqdestroy___test95request95broker_u12640((*dest_p0).Sup.internalValue._oResultPrivate_2.vResultPrivate);
			nimRawDispose((*dest_p0).Sup.internalValue._oResultPrivate_2.vResultPrivate, ((NI)8));
		}
LA31_: ;
	}
	break;
	default:
	{
	}
	break;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__test95request95broker_u51319)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___test95request95broker_u13757(((tyObject_InternalRaisesFuturecolonObjectType___tMvhnBXZ682BZdr1U7YI8Q*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___test95request95broker_u13769)(tyObject_InternalRaisesFuturecolonObjectType___tMvhnBXZ682BZdr1U7YI8Q* dest_p0, void* env_p1) {
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0), env_p1);
	eqtrace___pkgZchronosZinternalZasyncengine_u1500((&(*dest_p0).Sup.Sup.Sup.internalCallbacks), env_p1);
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0), env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.internalChild, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.internalError, env_p1);
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0), env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___test95request95broker_u13734)(tyObject_InternalRaisesFuturecolonObjectType___tMvhnBXZ682BZdr1U7YI8Q** dest_p0) {
	(*dest_p0) = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___test95request95broker_u32237)(tyObject_InternalRaisesFuturecolonObjectType___iJhZ65KYq3ODiWYDi6IbdQ** dest_p0, tyObject_InternalRaisesFuturecolonObjectType___iJhZ65KYq3ODiWYDi6IbdQ* src_p1, NIM_BOOL cyclic_p2) {
	tyObject_InternalRaisesFuturecolonObjectType___iJhZ65KYq3ODiWYDi6IbdQ* colontmp_;
	colontmp_ = (*dest_p0);
	{
		if (!src_p1) goto LA3_;
		nimIncRefCyclic(src_p1, cyclic_p2);
	}
LA3_: ;
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose(colontmp_);
	}
LA8_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u32234)(tyObject_InternalRaisesFuturecolonObjectType___iJhZ65KYq3ODiWYDi6IbdQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(dest_p0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(dest_p0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u32254)(tyObject_InternalRaisesFuturecolonObjectType___iJhZ65KYq3ODiWYDi6IbdQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0);
	}
LA4_: ;
	eqdestroy___pkgZchronosZinternalZasyncengine_u1488((*dest_p0).Sup.Sup.Sup.internalCallbacks);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0);
	}
LA9_: ;
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalChild);
		if (!T13_) goto LA14_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalChild);
	}
LA14_: ;
	{
		NIM_BOOL T18_;
		T18_ = (NIM_BOOL)0;
		T18_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalError);
		if (!T18_) goto LA19_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalError);
	}
LA19_: ;
	{
		NIM_BOOL T23_;
		T23_ = (NIM_BOOL)0;
		T23_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0);
		if (!T23_) goto LA24_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0);
	}
LA24_: ;
	switch ((*dest_p0).Sup.internalValue.oResultPrivate) {
	case NIM_FALSE:
	{
		if ((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p && !((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p);
}
	}
	break;
	case NIM_TRUE:
	{
	}
	break;
	default:
	{
	}
	break;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__test95request95broker_u55077)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___test95request95broker_u32254(((tyObject_InternalRaisesFuturecolonObjectType___iJhZ65KYq3ODiWYDi6IbdQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___test95request95broker_u32266)(tyObject_InternalRaisesFuturecolonObjectType___iJhZ65KYq3ODiWYDi6IbdQ* dest_p0, void* env_p1) {
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0), env_p1);
	eqtrace___pkgZchronosZinternalZasyncengine_u1500((&(*dest_p0).Sup.Sup.Sup.internalCallbacks), env_p1);
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0), env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.internalChild, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.internalError, env_p1);
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0), env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___test95request95broker_u32231)(tyObject_InternalRaisesFuturecolonObjectType___iJhZ65KYq3ODiWYDi6IbdQ** dest_p0) {
	(*dest_p0) = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___test95request95broker_u34056)(tyObject_InternalRaisesFuturecolonObjectType___Nar6R6CjP79aWOhy58WVmHQ** dest_p0, tyObject_InternalRaisesFuturecolonObjectType___Nar6R6CjP79aWOhy58WVmHQ* src_p1, NIM_BOOL cyclic_p2) {
	tyObject_InternalRaisesFuturecolonObjectType___Nar6R6CjP79aWOhy58WVmHQ* colontmp_;
	colontmp_ = (*dest_p0);
	{
		if (!src_p1) goto LA3_;
		nimIncRefCyclic(src_p1, cyclic_p2);
	}
LA3_: ;
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose(colontmp_);
	}
LA8_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u34053)(tyObject_InternalRaisesFuturecolonObjectType___Nar6R6CjP79aWOhy58WVmHQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(dest_p0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(dest_p0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u34073)(tyObject_InternalRaisesFuturecolonObjectType___Nar6R6CjP79aWOhy58WVmHQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0);
	}
LA4_: ;
	eqdestroy___pkgZchronosZinternalZasyncengine_u1488((*dest_p0).Sup.Sup.Sup.internalCallbacks);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0);
	}
LA9_: ;
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalChild);
		if (!T13_) goto LA14_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalChild);
	}
LA14_: ;
	{
		NIM_BOOL T18_;
		T18_ = (NIM_BOOL)0;
		T18_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalError);
		if (!T18_) goto LA19_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalError);
	}
LA19_: ;
	{
		NIM_BOOL T23_;
		T23_ = (NIM_BOOL)0;
		T23_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0);
		if (!T23_) goto LA24_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0);
	}
LA24_: ;
	switch ((*dest_p0).Sup.internalValue.oResultPrivate) {
	case NIM_FALSE:
	{
		if ((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p && !((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p);
}
	}
	break;
	case NIM_TRUE:
	{
		if ((*dest_p0).Sup.internalValue._oResultPrivate_2.vResultPrivate.label.p && !((*dest_p0).Sup.internalValue._oResultPrivate_2.vResultPrivate.label.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.internalValue._oResultPrivate_2.vResultPrivate.label.p);
}
	}
	break;
	default:
	{
	}
	break;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__test95request95broker_u55572)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___test95request95broker_u34073(((tyObject_InternalRaisesFuturecolonObjectType___Nar6R6CjP79aWOhy58WVmHQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___test95request95broker_u34085)(tyObject_InternalRaisesFuturecolonObjectType___Nar6R6CjP79aWOhy58WVmHQ* dest_p0, void* env_p1) {
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0), env_p1);
	eqtrace___pkgZchronosZinternalZasyncengine_u1500((&(*dest_p0).Sup.Sup.Sup.internalCallbacks), env_p1);
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0), env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.internalChild, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.internalError, env_p1);
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0), env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___test95request95broker_u34050)(tyObject_InternalRaisesFuturecolonObjectType___Nar6R6CjP79aWOhy58WVmHQ** dest_p0) {
	(*dest_p0) = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___test95request95broker_u39818)(tyObject_InternalRaisesFuturecolonObjectType___Z9ajIPm3KTYwBZB77zhL2NQ** dest_p0, tyObject_InternalRaisesFuturecolonObjectType___Z9ajIPm3KTYwBZB77zhL2NQ* src_p1, NIM_BOOL cyclic_p2) {
	tyObject_InternalRaisesFuturecolonObjectType___Z9ajIPm3KTYwBZB77zhL2NQ* colontmp_;
	colontmp_ = (*dest_p0);
	{
		if (!src_p1) goto LA3_;
		nimIncRefCyclic(src_p1, cyclic_p2);
	}
LA3_: ;
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose(colontmp_);
	}
LA8_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u39815)(tyObject_InternalRaisesFuturecolonObjectType___Z9ajIPm3KTYwBZB77zhL2NQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(dest_p0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(dest_p0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u39835)(tyObject_InternalRaisesFuturecolonObjectType___Z9ajIPm3KTYwBZB77zhL2NQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0);
	}
LA4_: ;
	eqdestroy___pkgZchronosZinternalZasyncengine_u1488((*dest_p0).Sup.Sup.Sup.internalCallbacks);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0);
	}
LA9_: ;
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalChild);
		if (!T13_) goto LA14_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalChild);
	}
LA14_: ;
	{
		NIM_BOOL T18_;
		T18_ = (NIM_BOOL)0;
		T18_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalError);
		if (!T18_) goto LA19_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalError);
	}
LA19_: ;
	{
		NIM_BOOL T23_;
		T23_ = (NIM_BOOL)0;
		T23_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0);
		if (!T23_) goto LA24_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0);
	}
LA24_: ;
	switch ((*dest_p0).Sup.internalValue.oResultPrivate) {
	case NIM_FALSE:
	{
		if ((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p && !((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p);
}
	}
	break;
	case NIM_TRUE:
	{
	}
	break;
	default:
	{
	}
	break;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__test95request95broker_u56631)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___test95request95broker_u39835(((tyObject_InternalRaisesFuturecolonObjectType___Z9ajIPm3KTYwBZB77zhL2NQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___test95request95broker_u39847)(tyObject_InternalRaisesFuturecolonObjectType___Z9ajIPm3KTYwBZB77zhL2NQ* dest_p0, void* env_p1) {
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0), env_p1);
	eqtrace___pkgZchronosZinternalZasyncengine_u1500((&(*dest_p0).Sup.Sup.Sup.internalCallbacks), env_p1);
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0), env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.internalChild, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.internalError, env_p1);
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0), env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___test95request95broker_u39812)(tyObject_InternalRaisesFuturecolonObjectType___Z9ajIPm3KTYwBZB77zhL2NQ** dest_p0) {
	(*dest_p0) = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___test95request95broker_u42620)(tyObject_InternalRaisesFuturecolonObjectType___7uNr9aylZIyEHIrSmujm5Uw** dest_p0, tyObject_InternalRaisesFuturecolonObjectType___7uNr9aylZIyEHIrSmujm5Uw* src_p1, NIM_BOOL cyclic_p2) {
	tyObject_InternalRaisesFuturecolonObjectType___7uNr9aylZIyEHIrSmujm5Uw* colontmp_;
	colontmp_ = (*dest_p0);
	{
		if (!src_p1) goto LA3_;
		nimIncRefCyclic(src_p1, cyclic_p2);
	}
LA3_: ;
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose(colontmp_);
	}
LA8_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u42617)(tyObject_InternalRaisesFuturecolonObjectType___7uNr9aylZIyEHIrSmujm5Uw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(dest_p0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(dest_p0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u42637)(tyObject_InternalRaisesFuturecolonObjectType___7uNr9aylZIyEHIrSmujm5Uw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0);
	}
LA4_: ;
	eqdestroy___pkgZchronosZinternalZasyncengine_u1488((*dest_p0).Sup.Sup.Sup.internalCallbacks);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0);
	}
LA9_: ;
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalChild);
		if (!T13_) goto LA14_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalChild);
	}
LA14_: ;
	{
		NIM_BOOL T18_;
		T18_ = (NIM_BOOL)0;
		T18_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalError);
		if (!T18_) goto LA19_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalError);
	}
LA19_: ;
	{
		NIM_BOOL T23_;
		T23_ = (NIM_BOOL)0;
		T23_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0);
		if (!T23_) goto LA24_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0);
	}
LA24_: ;
	switch ((*dest_p0).Sup.internalValue.oResultPrivate) {
	case NIM_FALSE:
	{
		if ((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p && !((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p);
}
	}
	break;
	case NIM_TRUE:
	{
	}
	break;
	default:
	{
	}
	break;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__test95request95broker_u57276)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___test95request95broker_u42637(((tyObject_InternalRaisesFuturecolonObjectType___7uNr9aylZIyEHIrSmujm5Uw*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___test95request95broker_u42649)(tyObject_InternalRaisesFuturecolonObjectType___7uNr9aylZIyEHIrSmujm5Uw* dest_p0, void* env_p1) {
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0), env_p1);
	eqtrace___pkgZchronosZinternalZasyncengine_u1500((&(*dest_p0).Sup.Sup.Sup.internalCallbacks), env_p1);
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0), env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.internalChild, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.internalError, env_p1);
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0), env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___test95request95broker_u42614)(tyObject_InternalRaisesFuturecolonObjectType___7uNr9aylZIyEHIrSmujm5Uw** dest_p0) {
	(*dest_p0) = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___test95request95broker_u46011)(tyObject_InternalRaisesFuturecolonObjectType___ssVEhm1bgZLDdWg4Kq9cdtg** dest_p0, tyObject_InternalRaisesFuturecolonObjectType___ssVEhm1bgZLDdWg4Kq9cdtg* src_p1, NIM_BOOL cyclic_p2) {
	tyObject_InternalRaisesFuturecolonObjectType___ssVEhm1bgZLDdWg4Kq9cdtg* colontmp_;
	colontmp_ = (*dest_p0);
	{
		if (!src_p1) goto LA3_;
		nimIncRefCyclic(src_p1, cyclic_p2);
	}
LA3_: ;
	(*dest_p0) = src_p1;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose(colontmp_);
	}
LA8_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u46008)(tyObject_InternalRaisesFuturecolonObjectType___ssVEhm1bgZLDdWg4Kq9cdtg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(dest_p0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(dest_p0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95request95broker_u46028)(tyObject_InternalRaisesFuturecolonObjectType___ssVEhm1bgZLDdWg4Kq9cdtg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0);
	}
LA4_: ;
	eqdestroy___pkgZchronosZinternalZasyncengine_u1488((*dest_p0).Sup.Sup.Sup.internalCallbacks);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0);
	}
LA9_: ;
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalChild);
		if (!T13_) goto LA14_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalChild);
	}
LA14_: ;
	{
		NIM_BOOL T18_;
		T18_ = (NIM_BOOL)0;
		T18_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalError);
		if (!T18_) goto LA19_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalError);
	}
LA19_: ;
	{
		NIM_BOOL T23_;
		T23_ = (NIM_BOOL)0;
		T23_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0);
		if (!T23_) goto LA24_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0);
	}
LA24_: ;
	switch ((*dest_p0).Sup.internalValue.oResultPrivate) {
	case NIM_FALSE:
	{
		if ((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p && !((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.internalValue._oResultPrivate_1.eResultPrivate.p);
}
	}
	break;
	case NIM_TRUE:
	{
	}
	break;
	default:
	{
	}
	break;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__test95request95broker_u58195)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___test95request95broker_u46028(((tyObject_InternalRaisesFuturecolonObjectType___ssVEhm1bgZLDdWg4Kq9cdtg*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___test95request95broker_u46040)(tyObject_InternalRaisesFuturecolonObjectType___ssVEhm1bgZLDdWg4Kq9cdtg* dest_p0, void* env_p1) {
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalCallback.function.ClE_0), env_p1);
	eqtrace___pkgZchronosZinternalZasyncengine_u1500((&(*dest_p0).Sup.Sup.Sup.internalCallbacks), env_p1);
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalCancelcb.ClE_0), env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.internalChild, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.internalError, env_p1);
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.internalClosure.ClE_0), env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___test95request95broker_u46005)(tyObject_InternalRaisesFuturecolonObjectType___ssVEhm1bgZLDdWg4Kq9cdtg** dest_p0) {
	(*dest_p0) = 0;
}
