/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c -w -ferror-limit=3 -pthread --coverage -O0 -g   -I/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib -I/Users/schwarzy/dev/status/nim-brokers/test -o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_api_discovery/@m..@snimbledeps@spkgs2@sserialization-0.5.2-fa35c1bb76a0a02a2379fe86eaae0957c7527cb8@sserialization@sobject_serialization.nim.c.o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_api_discovery/@m..@snimbledeps@spkgs2@sserialization-0.5.2-fa35c1bb76a0a02a2379fe86eaae0957c7527cb8@sserialization@sobject_serialization.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyTuple__wotk9bQEspeIleLw4GVAG9aA tyTuple__wotk9bQEspeIleLw4GVAG9aA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_EchoCborArgs__3RboOJKrNzgGjkRHH6swWQ tyObject_EchoCborArgs__3RboOJKrNzgGjkRHH6swWQ;
typedef struct tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef N_NIMCALL_PTR(void, tyProc__XFQTEeFahZtuOYyiEZ474g) (tyObject_EchoCborArgs__3RboOJKrNzgGjkRHH6swWQ* rec_p0, tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw* reader_p1);
struct tyTuple__wotk9bQEspeIleLw4GVAG9aA {
	NimStringV2 Field0;
	tyProc__XFQTEeFahZtuOYyiEZ474g Field1;
};
typedef tyTuple__wotk9bQEspeIleLw4GVAG9aA tyArray__UfxSCMxmLoQn89aUlA0a2KQ[1];
struct tyObject_EchoCborArgs__3RboOJKrNzgGjkRHH6swWQ {
	NI32 value;
};
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1739)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4709)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NI32, readValue__test95api95discovery_u16476)(tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw* reader_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
extern NIM_THREADVAR TFrame* framePtr__system_u2723;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4491;
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1739)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2723;
	framePtr__system_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2723 = (*framePtr__system_u2723).prev;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
	nimfr_("eqStrings", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/strmantle.nim");
{	nimlf_(35, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/strmantle.nim");	result = NIM_FALSE;
	nimln_(36);	alen_1 = a_p0.len;
	nimln_(37);	blen_1 = b_p1.len;
	nimln_(38);	{
		if (!(alen_1 == blen_1)) goto LA3_;
		nimln_(39);		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			nimln_(34);			nimln_(39);			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		nimln_(40);		nimln_(34);		nimln_(40);		result = equalMem__system_u1739(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, findFieldIdx__test95api95discovery_u17071)(tyArray__UfxSCMxmLoQn89aUlA0a2KQ fieldsTable_p0, NimStringV2 fieldName_p1, NI* expectedFieldPos_p2) {
	NI result;
	nimfr_("findFieldIdx", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/serialization-0.5.2-fa35c1bb76a0a02a2379fe86eaae0957c7527cb8/serialization/object_serialization.nim");
{	{
		NI i_1;
		NI i_2;
		i_1 = (NI)0;
		nimlf_(128, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators_1.nim");		i_2 = (*expectedFieldPos_p2);
		{
			nimln_(129);			while (1) {
				NI TM__1650mCTumCXiIP5VP01SuA_3;
				if (!(i_2 < ((NI)1))) goto LA3;
				nimlf_(257, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/serialization-0.5.2-fa35c1bb76a0a02a2379fe86eaae0957c7527cb8/serialization/object_serialization.nim");				i_1 = i_2;
				nimln_(258);				{
					NI TM__1650mCTumCXiIP5VP01SuA_2;
					if ((NU)(i_1) > (NU)(0)){ raiseIndexError2(i_1, 0); goto BeforeRet_;
					}
					if (!eqStrings(fieldsTable_p0[(i_1)- 0].Field0, fieldName_p1)) goto LA6_;
					nimln_(259);					if (nimAddInt(i_1, ((NI)1), &TM__1650mCTumCXiIP5VP01SuA_2)) { raiseOverflow(); goto BeforeRet_;
					};
					(*expectedFieldPos_p2) = (NI)(TM__1650mCTumCXiIP5VP01SuA_2);
					nimln_(260);					nimln_(254);					nimln_(260);					result = i_1;
					goto BeforeRet_;
				}
LA6_: ;
				nimlf_(131, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators_1.nim");				if (nimAddInt(i_2, ((NI)1), &TM__1650mCTumCXiIP5VP01SuA_3)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__1650mCTumCXiIP5VP01SuA_3);
			} LA3: ;
		}
	}
	{
		NI i_3;
		NI i_4;
		i_3 = (NI)0;
		nimln_(128);		i_4 = ((NI)0);
		{
			nimln_(129);			while (1) {
				NI TM__1650mCTumCXiIP5VP01SuA_4;
				if (!(i_4 < (*expectedFieldPos_p2))) goto LA10;
				nimlf_(262, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/serialization-0.5.2-fa35c1bb76a0a02a2379fe86eaae0957c7527cb8/serialization/object_serialization.nim");				i_3 = i_4;
				nimln_(263);				{
					if ((NU)(i_3) > (NU)(0)){ raiseIndexError2(i_3, 0); goto BeforeRet_;
					}
					if (!eqStrings(fieldsTable_p0[(i_3)- 0].Field0, fieldName_p1)) goto LA13_;
					nimln_(264);					nimln_(254);					nimln_(264);					result = i_3;
					goto BeforeRet_;
				}
LA13_: ;
				nimlf_(131, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators_1.nim");				if (nimAddInt(i_4, ((NI)1), &TM__1650mCTumCXiIP5VP01SuA_4)) { raiseOverflow(); goto BeforeRet_;
				};
				i_4 = (NI)(TM__1650mCTumCXiIP5VP01SuA_4);
			} LA10: ;
		}
	}
	nimlf_(266, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/serialization-0.5.2-fa35c1bb76a0a02a2379fe86eaae0957c7527cb8/serialization/object_serialization.nim");	nimln_(254);	nimln_(266);	result = ((NI)-1);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4491);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, readField__test95api95discovery_u16389)(tyObject_EchoCborArgs__3RboOJKrNzgGjkRHH6swWQ* obj_p0, tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw* reader_p1) {
	NI32 T1_;
NIM_BOOL* nimErr_;
	nimfr_("readField", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/serialization-0.5.2-fa35c1bb76a0a02a2379fe86eaae0957c7527cb8/serialization/object_serialization.nim");
{nimErr_ = nimErrorFlag();
	nimln_(241);	nimln_(208);	T1_ = (NI32)0;
	T1_ = readValue__test95api95discovery_u16476(reader_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*obj_p0).value = T1_;
	}BeforeRet_: ;
	popFrame();
}
