/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c -w -ferror-limit=3 -pthread --coverage -O0 -g   -I/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib -I/Users/schwarzy/dev/status/nim-brokers/test -o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_api_discovery/@m..@snimbledeps@spkgs2@schronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0@schronos@ssrcloc.nim.c.o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_api_discovery/@m..@snimbledeps@spkgs2@schronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0@schronos@ssrcloc.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w {
	NCSTRING procedure;
	NCSTRING file;
	NI line;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4709)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toString__pkgZchronosZsrcloc_u10)(NU64 value_p1);
static N_INLINE(NI, nimCStrLen)(NCSTRING a_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_2 = { 1 | NIM_STRLIT_FLAG, "(" };
static const NimStringV2 TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_3 = {1, (NimStrPayload*)&TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_2};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_5 = { 1 | NIM_STRLIT_FLAG, ")" };
static const NimStringV2 TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_6 = {1, (NimStrPayload*)&TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_5};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_7 = { 4 | NIM_STRLIT_FLAG, "    " };
static const NimStringV2 TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_8 = {4, (NimStrPayload*)&TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_7};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_9 = { 13 | NIM_STRLIT_FLAG, "[unspecified]" };
static const NimStringV2 TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_10 = {13, (NimStrPayload*)&TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_9};
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u24815 = {"eventBroker.Heartbeat.shutdown", "mt_event_broker.nim", ((NI)458)}
;
extern NIM_THREADVAR TFrame* framePtr__system_u2723;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4491;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u22318 = {"", "mt_event_broker.nim", ((NI)357)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u21288 = {"notifyHeartbeatListener", "mt_event_broker.nim", ((NI)303)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u21260 = {"", "mt_event_broker.nim", ((NI)309)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__OOZbrokersZinternalZmt95broker95common_u942 = {"brokerDispatchLoop", "mt_broker_common.nim", ((NI)175)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__OOZbrokersZinternalZmt95broker95common_u885 = {"", "mt_broker_common.nim", ((NI)175)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__pkgZchronosZthreadsync_u812 = {"asyncthreadsignal.wait", "threadsync.nim", ((NI)369)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__pkgZchronosZthreadsync_u954 = {"", "threadsync.nim", ((NI)413)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__pkgZchronosZthreadsync_u841 = {"", "threadsync.nim", ((NI)393)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__pkgZchronosZthreadsync_u861 = {"", "threadsync.nim", ((NI)396)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__pkgZchronosZthreadsync_u900 = {"", "threadsync.nim", ((NI)400)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__pkgZchronosZthreadsync_u912 = {"", "threadsync.nim", ((NI)402)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__pkgZchronosZthreadsync_u993 = {"", "threadsync.nim", ((NI)417)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u30906 = {"handler", "api_library.nim", ((NI)785)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u30859 = {"", "api_library.nim", ((NI)843)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u31377 = {"awaitShutdown", "api_library.nim", ((NI)1047)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u31349 = {"", "api_library.nim", ((NI)1046)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__pkgZchronosZinternalZasyncfutures_u3635 = {"chronos.sleepAsync(Duration)", "asyncfutures.nim", ((NI)1423)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__pkgZchronosZinternalZasyncfutures_u3667 = {"", "asyncfutures.nim", ((NI)1429)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__OOZbrokersZinternalZmt95broker95common_u1361 = {"awaitLoopExit", "mt_broker_common.nim", ((NI)316)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__OOZbrokersZinternalZmt95broker95common_u1333 = {"", "mt_broker_common.nim", ((NI)315)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u1749 = {"handleMsgInitializeRequest", "mt_request_broker.nim", ((NI)705)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u1540 = {"", "mt_request_broker.nim", ((NI)635)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u27722 = {"initProv", "test_api_discovery.nim", ((NI)47)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u27659 = {"", "test_api_discovery.nim", ((NI)47)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u9366 = {"handleMsgShutdownRequest", "mt_request_broker.nim", ((NI)705)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u28028 = {"shutProv", "test_api_discovery.nim", ((NI)52)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u27965 = {"", "test_api_discovery.nim", ((NI)52)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u14400 = {"handleMsgEcho", "mt_request_broker.nim", ((NI)705)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u14191 = {"", "mt_request_broker.nim", ((NI)700)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u28335 = {"echoProv", "test_api_discovery.nim", ((NI)57)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u28272 = {"", "test_api_discovery.nim", ((NI)57)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u32142 = {"handleCourierMsg", "api_library.nim", ((NI)1127)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u32083 = {"", "api_library.nim", ((NI)1172)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u29823 = {"cbdiscCborDispatch", "test_api_discovery.nim", ((NI)71)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u7812 = {"InitializeRequestCborAdapter", "api_request_broker_cbor.nim", ((NI)247)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u5651 = {"request", "mt_request_broker.nim", ((NI)1149)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u5616 = {"", "mt_request_broker.nim", ((NI)1192)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u4690 = {"sendAndAwaitInitializeRequest", "mt_request_broker.nim", ((NI)926)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u3286 = {"request.InitializeRequest", "mt_request_broker.nim", ((NI)989)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u3326 = {"", "mt_request_broker.nim", ((NI)1016)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u4626 = {"", "mt_request_broker.nim", ((NI)1042)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u3377 = {"chronos.withTimeout", "asyncfutures.nim", ((NI)1502)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u3831 = {"", "asyncfutures.nim", ((NI)1554)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u3851 = {"", "asyncfutures.nim", ((NI)1557)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u3768 = {"", "asyncfutures.nim", ((NI)1548)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u3550 = {"", "asyncfutures.nim", ((NI)1512)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u3677 = {"", "asyncfutures.nim", ((NI)1515)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u3692 = {"", "asyncfutures.nim", ((NI)1517)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u3702 = {"", "asyncfutures.nim", ((NI)1534)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u3917 = {"", "mt_request_broker.nim", ((NI)1023)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u4032 = {"", "mt_request_broker.nim", ((NI)1030)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u7689 = {"", "api_request_broker_cbor.nim", ((NI)257)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u12923 = {"ShutdownRequestCborAdapter", "api_request_broker_cbor.nim", ((NI)247)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u10794 = {"sendAndAwaitShutdownRequest", "mt_request_broker.nim", ((NI)926)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u9710 = {"request.ShutdownRequest", "mt_request_broker.nim", ((NI)989)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u20494 = {"EchoCborAdapter", "", ((NI)4)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u19499 = {"request", "mt_request_broker.nim", ((NI)1313)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u19464 = {"", "mt_request_broker.nim", ((NI)1357)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u15829 = {"sendAndAwaitEcho", "mt_request_broker.nim", ((NI)926)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u14745 = {"request.Echo", "mt_request_broker.nim", ((NI)989)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u20413 = {"", "", ((NI)22)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u29790 = {"", "test_api_discovery.nim", ((NI)71)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u32269 = {"awaitShutdown", "api_library.nim", ((NI)1198)}
;
N_LIB_PRIVATE tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w loc__test95api95discovery_u32241 = {"", "api_library.nim", ((NI)1197)}
;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2723;
	framePtr__system_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2723 = (*framePtr__system_u2723).prev;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u24807)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimlf_(37, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u24815);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_4;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1731(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_4)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_4);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
static N_INLINE(NI, nimCStrLen)(NCSTRING a_p0) {
	NI result;
	size_t T5_;
{	result = (NI)0;
	{
		if (!(a_p0 == 0)) goto LA3_;
		result = ((NI)0);
		goto BeforeRet_;
	}
LA3_: ;
	T5_ = (size_t)0;
	T5_ = strlen(a_p0);
	result = ((NI) (T5_));
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4491);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pkgZchronosZsrcloc_u6)(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* loc_p0) {
	NimStringV2 result;
	NimStringV2 res_1;
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("$", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	res_1.len = 0; res_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimln_(21);	res_1 = cstrToNimstr((*loc_p0).file);
	nimln_(22);	prepareAdd((&res_1), 1);
appendString((&res_1), TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_3);
	nimln_(23);	colontmpD_ = toString__pkgZchronosZsrcloc_u10(((NU64) ((*loc_p0).line)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	prepareAdd((&res_1), colontmpD_.len + 0);
appendString((&res_1), colontmpD_);
	nimln_(24);	prepareAdd((&res_1), 1);
appendString((&res_1), TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_6);
	nimln_(25);	prepareAdd((&res_1), 4);
appendString((&res_1), TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_8);
	nimln_(26);	{
		if (!(nimCStrLen((*loc_p0).procedure) == ((NI)0))) goto LA3_;
		nimln_(27);		prepareAdd((&res_1), 13);
appendString((&res_1), TM__9aDT9biGY9cBB5p9cXFWGxhsSQ_10);
	}
	goto LA1_;
LA3_: ;
	{
		NimStringV2 colontmpD__2;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		nimln_(29);		colontmpD__2 = cstrToNimstr((*loc_p0).procedure);
		prepareAdd((&res_1), colontmpD__2.len + 0);
appendString((&res_1), colontmpD__2);
		nimlf_(394, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
	}
LA1_: ;
	nimlf_(20, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");	nimln_(30);	result = res_1;
	nimlf_(394, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u22310)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimlf_(37, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u22318);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u21280)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u21288);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u21252)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u21260);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__OOZbrokersZinternalZmt95broker95common_u934)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__OOZbrokersZinternalZmt95broker95common_u942);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__OOZbrokersZinternalZmt95broker95common_u877)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__OOZbrokersZinternalZmt95broker95common_u885);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__pkgZchronosZthreadsync_u804)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__pkgZchronosZthreadsync_u812);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__pkgZchronosZthreadsync_u946)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__pkgZchronosZthreadsync_u954);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__pkgZchronosZthreadsync_u833)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__pkgZchronosZthreadsync_u841);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__pkgZchronosZthreadsync_u853)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__pkgZchronosZthreadsync_u861);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__pkgZchronosZthreadsync_u892)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__pkgZchronosZthreadsync_u900);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__pkgZchronosZthreadsync_u904)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__pkgZchronosZthreadsync_u912);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__pkgZchronosZthreadsync_u985)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__pkgZchronosZthreadsync_u993);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u30898)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u30906);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u30851)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u30859);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u31369)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u31377);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u31341)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u31349);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__pkgZchronosZinternalZasyncfutures_u3627)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__pkgZchronosZinternalZasyncfutures_u3635);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__pkgZchronosZinternalZasyncfutures_u3659)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__pkgZchronosZinternalZasyncfutures_u3667);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__OOZbrokersZinternalZmt95broker95common_u1353)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__OOZbrokersZinternalZmt95broker95common_u1361);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__OOZbrokersZinternalZmt95broker95common_u1325)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__OOZbrokersZinternalZmt95broker95common_u1333);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u1741)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u1749);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u1532)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u1540);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u27714)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u27722);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u27651)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u27659);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u9358)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u9366);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u28020)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u28028);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u27957)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u27965);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u14392)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u14400);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u14183)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u14191);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u28327)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u28335);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u28264)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u28272);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u32134)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u32142);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u32075)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u32083);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u29815)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u29823);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u7804)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u7812);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u5643)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u5651);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u5608)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u5616);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u4682)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u4690);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u3278)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u3286);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u3318)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u3326);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u4618)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u4626);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u3369)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u3377);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u3823)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u3831);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u3843)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u3851);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u3760)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u3768);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u3542)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u3550);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u3669)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u3677);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u3684)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u3692);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u3694)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u3702);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u3909)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u3917);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u4024)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u4032);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u7681)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u7689);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u12915)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u12923);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u10786)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u10794);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u9702)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u9710);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u20486)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u20494);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u19491)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u19499);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u19456)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u19464);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u15821)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u15829);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u14737)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u14745);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u20405)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u20413);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u29782)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u29790);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u32261)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u32269);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w*, srcLocImpl__test95api95discovery_u32233)(void) {
	tyObject_SrcLoc__9cVWLBsKJ11sLUdbzDYi34w* result;
	nimfr_("srcLocImpl", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronos-4.2.2-3a4c9477df8cef20a04e4f1b54a2d74fdfc2a3d0/chronos/srcloc.nim");
{	nimln_(37);	nimln_(32);	nimln_(37);	result = (&loc__test95api95discovery_u32241);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
