/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c -w -ferror-limit=3 -pthread --coverage -O0 -g   -I/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib -I/Users/schwarzy/dev/status/nim-brokers/test -o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_multi_thread_request_broker/@m..@sbrokers@sinternal@smt_codec.nim.c.o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_multi_thread_request_broker/@m..@sbrokers@sinternal@smt_codec.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_MTReqMtRequestMsg__Jr5le9cACMNSqErDTdY9ckdg tyObject_MTReqMtRequestMsg__Jr5le9cACMNSqErDTdY9ckdg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA;
typedef struct tyObject_MTReq__D9bGD4LS6l9aexvOD6DK7DnQ tyObject_MTReq__D9bGD4LS6l9aexvOD6DK7DnQ;
typedef struct tyObject_MtVoidReqMtRequestMsg__emjMGmY31bA062xiU38zpQ tyObject_MtVoidReqMtRequestMsg__emjMGmY31bA062xiU38zpQ;
typedef struct tyObject_MtVoidReq__8CJNW2loTYKn0f0dxv0TmQ tyObject_MtVoidReq__8CJNW2loTYKn0f0dxv0TmQ;
typedef struct tyObject_SugarVoidMtRequestMsg__Gn9c8m2r9aICzncdczGNQ76g tyObject_SugarVoidMtRequestMsg__Gn9c8m2r9aICzncdczGNQ76g;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_MTReqMtRequestMsg__Jr5le9cACMNSqErDTdY9ckdg {
	NI requestKind;
	NimStringV2 input;
	NU32 responseSlotIdx;
	tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA* requesterSignal;
};
struct tyObject_MTReq__D9bGD4LS6l9aexvOD6DK7DnQ {
	NimStringV2 textValue;
	NI numValue;
	NIM_BOOL boolValue;
};
struct tyObject_MtVoidReqMtRequestMsg__emjMGmY31bA062xiU38zpQ {
	NI requestKind;
	NimStringV2 label;
	NU32 responseSlotIdx;
	tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA* requesterSignal;
};
struct tyObject_MtVoidReq__8CJNW2loTYKn0f0dxv0TmQ {
	char dummy;
};
struct tyObject_SugarVoidMtRequestMsg__Gn9c8m2r9aICzncdczGNQ76g {
	NI requestKind;
	NimStringV2 label;
	NU32 responseSlotIdx;
	tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA* requesterSignal;
};
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95multi95thread95request95broker_u505)(NU8* buf_p0, NI len_p1, NI* value_p2, NI* pos_p3);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4709)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95multi95thread95request95broker_u529)(NU8* buf_p0, NI len_p1, NimStringV2* value_p2, NI* pos_p3);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2696)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95multi95thread95request95broker_u549)(NU8* buf_p0, NI len_p1, NU32* value_p2, NI* pos_p3);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95multi95thread95request95broker_u573)(NU8* buf_p0, NI len_p1, tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA** value_p2, NI* pos_p3);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95multi95thread95request95broker_u396)(NU8* buf_p0, NI cap_p1, NimStringV2 value_p2, NI* pos_p3);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95multi95thread95request95broker_u372)(NU8* buf_p0, NI cap_p1, NI value_p2, NI* pos_p3);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95multi95thread95request95broker_u760)(NU8* buf_p0, NI cap_p1, NIM_BOOL value_p2, NI* pos_p3);
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95multi95thread95request95broker_u628)(NimStringV2 value_p0);
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95multi95thread95request95broker_u613)(NI value_p0);
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95multi95thread95request95broker_u1120)(NIM_BOOL value_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95multi95thread95request95broker_u416)(NU8* buf_p0, NI cap_p1, NU32 value_p2, NI* pos_p3);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95multi95thread95request95broker_u440)(NU8* buf_p0, NI cap_p1, tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA* value_p2, NI* pos_p3);
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95multi95thread95request95broker_u640)(NU32 value_p0);
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95multi95thread95request95broker_u655)(tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA* value_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95multi95thread95request95broker_u989)(NU8* buf_p0, NI len_p1, NIM_BOOL* value_p2, NI* pos_p3);
extern NIM_THREADVAR TFrame* framePtr__system_u2723;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4491;
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2723;
	framePtr__system_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2723 = (*framePtr__system_u2723).prev;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95multi95thread95request95broker_u505)(NU8* buf_p0, NI len_p1, NI* value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_3;
	nimfr_("mtUnmarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimlf_(175, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_2;
		if (nimAddInt((*pos_p3), ((NI)8), &TM__gSOrWU7W2lzpIJkvkwiA9bw_2)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(len_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_2))) goto LA3_;
		nimln_(176);		nimln_(153);		nimln_(176);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(177);	copyMem__system_u1731(((void*) (value_p2)), ((void*) ((&buf_p0[(*pos_p3)]))), ((NI)8));
	nimln_(178);	if (nimAddInt((*pos_p3), ((NI)8), &TM__gSOrWU7W2lzpIJkvkwiA9bw_3)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_3);
	nimln_(179);	nimln_(153);	nimln_(179);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95multi95thread95request95broker_u529)(NU8* buf_p0, NI len_p1, NimStringV2* value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NU32 sLen_1;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_5;
	NimStringV2 T9_;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_7;
	nimfr_("mtUnmarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	result = (NIM_BOOL)0;
	nimln_(181);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_4;
		if (nimAddInt((*pos_p3), ((NI)4), &TM__gSOrWU7W2lzpIJkvkwiA9bw_4)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(len_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_4))) goto LA3_;
		nimln_(182);		nimln_(153);		nimln_(182);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	sLen_1 = (NU32)0;
	nimln_(184);	copyMem__system_u1731(((void*) ((&sLen_1))), ((void*) ((&buf_p0[(*pos_p3)]))), ((NI)4));
	nimln_(185);	if (nimAddInt((*pos_p3), ((NI)4), &TM__gSOrWU7W2lzpIJkvkwiA9bw_5)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_5);
	nimln_(186);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_6;
		if (nimAddInt((*pos_p3), ((NI) (sLen_1)), &TM__gSOrWU7W2lzpIJkvkwiA9bw_6)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(len_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_6))) goto LA7_;
		nimln_(187);		nimln_(153);		nimln_(187);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA7_: ;
	nimlf_(1694, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	nimlf_(188, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");	if ((((NI) (sLen_1))) < ((NI)0) || (((NI) (sLen_1))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(((NI) (sLen_1)), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	T9_.len = 0; T9_.p = NIM_NIL;
	T9_ = mnewString((((NI) (sLen_1))));
	nimlf_(1694, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	eqsink___system_u2696((&(*value_p2)), T9_);
	nimlf_(189, "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");	{
		if (!((NU32)(((NU32)0)) < (NU32)(sLen_1))) goto LA12_;
		nimln_(190);		if (((NI)0) < 0 || ((NI)0) >= (*value_p2).len){ raiseIndexError2(((NI)0),(*value_p2).len-1); goto BeforeRet_;
		}
		if ((((NI) (sLen_1))) < ((NI)0) || (((NI) (sLen_1))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(((NI) (sLen_1)), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1731(((void*) ((&(*value_p2).p->data[((NI)0)]))), ((void*) ((&buf_p0[(*pos_p3)]))), (((NI) (sLen_1))));
	}
LA12_: ;
	nimln_(191);	if (nimAddInt((*pos_p3), ((NI) (sLen_1)), &TM__gSOrWU7W2lzpIJkvkwiA9bw_7)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_7);
	nimln_(192);	nimln_(153);	nimln_(192);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95multi95thread95request95broker_u549)(NU8* buf_p0, NI len_p1, NU32* value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_9;
	nimfr_("mtUnmarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(175);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_8;
		if (nimAddInt((*pos_p3), ((NI)4), &TM__gSOrWU7W2lzpIJkvkwiA9bw_8)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(len_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_8))) goto LA3_;
		nimln_(176);		nimln_(153);		nimln_(176);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(177);	copyMem__system_u1731(((void*) (value_p2)), ((void*) ((&buf_p0[(*pos_p3)]))), ((NI)4));
	nimln_(178);	if (nimAddInt((*pos_p3), ((NI)4), &TM__gSOrWU7W2lzpIJkvkwiA9bw_9)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_9);
	nimln_(179);	nimln_(153);	nimln_(179);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95multi95thread95request95broker_u573)(NU8* buf_p0, NI len_p1, tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA** value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_11;
	nimfr_("mtUnmarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(175);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_10;
		if (nimAddInt((*pos_p3), ((NI)8), &TM__gSOrWU7W2lzpIJkvkwiA9bw_10)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(len_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_10))) goto LA3_;
		nimln_(176);		nimln_(153);		nimln_(176);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(177);	copyMem__system_u1731(((void*) (value_p2)), ((void*) ((&buf_p0[(*pos_p3)]))), ((NI)8));
	nimln_(178);	if (nimAddInt((*pos_p3), ((NI)8), &TM__gSOrWU7W2lzpIJkvkwiA9bw_11)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_11);
	nimln_(179);	nimln_(153);	nimln_(179);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4491);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95multi95thread95request95broker_u489)(NU8* buf_p0, NI len_p1, tyObject_MTReqMtRequestMsg__Jr5le9cACMNSqErDTdY9ckdg* value_p2, NI* pos_p3) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("mtUnmarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{nimErr_ = nimErrorFlag();
	{
		if (!NIM_TRUE) goto LA3_;
		nimln_(202);		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = mtUnmarshalValue__test95multi95thread95request95broker_u505(buf_p0, len_p1, (&(*value_p2).requestKind), pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T7_)) goto LA8_;
			nimln_(203);			nimln_(153);			nimln_(203);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA8_: ;
	}
LA3_: ;
	{
		if (!NIM_TRUE) goto LA12_;
		nimln_(202);		{
			NIM_BOOL T16_;
			T16_ = (NIM_BOOL)0;
			T16_ = mtUnmarshalValue__test95multi95thread95request95broker_u529(buf_p0, len_p1, (&(*value_p2).input), pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T16_)) goto LA17_;
			nimln_(203);			nimln_(153);			nimln_(203);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA17_: ;
	}
LA12_: ;
	{
		if (!NIM_TRUE) goto LA21_;
		nimln_(202);		{
			NIM_BOOL T25_;
			T25_ = (NIM_BOOL)0;
			T25_ = mtUnmarshalValue__test95multi95thread95request95broker_u549(buf_p0, len_p1, (&(*value_p2).responseSlotIdx), pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T25_)) goto LA26_;
			nimln_(203);			nimln_(153);			nimln_(203);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA26_: ;
	}
LA21_: ;
	{
		if (!NIM_TRUE) goto LA30_;
		nimln_(202);		{
			NIM_BOOL T34_;
			T34_ = (NIM_BOOL)0;
			T34_ = mtUnmarshalValue__test95multi95thread95request95broker_u573(buf_p0, len_p1, &(*value_p2).requesterSignal, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T34_)) goto LA35_;
			nimln_(203);			nimln_(153);			nimln_(203);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA35_: ;
	}
LA30_: ;
	nimln_(204);	nimln_(153);	nimln_(204);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95multi95thread95request95broker_u396)(NU8* buf_p0, NI cap_p1, NimStringV2 value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NU32 sLen_1;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_14;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_15;
	nimfr_("mtMarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	result = (NIM_BOOL)0;
	nimln_(121);	sLen_1 = ((NU32) (value_p2.len));
	nimln_(122);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_12;
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_13;
		if (nimAddInt((*pos_p3), ((NI)4), &TM__gSOrWU7W2lzpIJkvkwiA9bw_12)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimAddInt((NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_12), ((NI) (sLen_1)), &TM__gSOrWU7W2lzpIJkvkwiA9bw_13)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(cap_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_13))) goto LA3_;
		nimln_(123);		nimln_(91);		nimln_(123);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(124);	copyMem__system_u1731(((void*) ((&buf_p0[(*pos_p3)]))), ((void*) ((&sLen_1))), ((NI)4));
	nimln_(125);	if (nimAddInt((*pos_p3), ((NI)4), &TM__gSOrWU7W2lzpIJkvkwiA9bw_14)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_14);
	nimln_(126);	{
		if (!((NU32)(((NU32)0)) < (NU32)(sLen_1))) goto LA7_;
		nimln_(127);		if (((NI)0) < 0 || ((NI)0) >= value_p2.len){ raiseIndexError2(((NI)0),value_p2.len-1); goto BeforeRet_;
		}
		if ((((NI) (sLen_1))) < ((NI)0) || (((NI) (sLen_1))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(((NI) (sLen_1)), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1731(((void*) ((&buf_p0[(*pos_p3)]))), ((void*) ((&value_p2.p->data[((NI)0)]))), (((NI) (sLen_1))));
	}
LA7_: ;
	nimln_(128);	if (nimAddInt((*pos_p3), ((NI) (sLen_1)), &TM__gSOrWU7W2lzpIJkvkwiA9bw_15)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_15);
	nimln_(129);	nimln_(91);	nimln_(129);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95multi95thread95request95broker_u372)(NU8* buf_p0, NI cap_p1, NI value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_17;
	nimfr_("mtMarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(115);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_16;
		if (nimAddInt((*pos_p3), ((NI)8), &TM__gSOrWU7W2lzpIJkvkwiA9bw_16)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(cap_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_16))) goto LA3_;
		nimln_(116);		nimln_(91);		nimln_(116);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(117);	copyMem__system_u1731(((void*) ((&buf_p0[(*pos_p3)]))), ((void*) ((&value_p2))), ((NI)8));
	nimln_(118);	if (nimAddInt((*pos_p3), ((NI)8), &TM__gSOrWU7W2lzpIJkvkwiA9bw_17)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_17);
	nimln_(119);	nimln_(91);	nimln_(119);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95multi95thread95request95broker_u760)(NU8* buf_p0, NI cap_p1, NIM_BOOL value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_19;
	nimfr_("mtMarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(115);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_18;
		if (nimAddInt((*pos_p3), ((NI)1), &TM__gSOrWU7W2lzpIJkvkwiA9bw_18)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(cap_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_18))) goto LA3_;
		nimln_(116);		nimln_(91);		nimln_(116);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(117);	copyMem__system_u1731(((void*) ((&buf_p0[(*pos_p3)]))), ((void*) ((&value_p2))), ((NI)1));
	nimln_(118);	if (nimAddInt((*pos_p3), ((NI)1), &TM__gSOrWU7W2lzpIJkvkwiA9bw_19)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_19);
	nimln_(119);	nimln_(91);	nimln_(119);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95multi95thread95request95broker_u732)(NU8* buf_p0, NI cap_p1, tyObject_MTReq__D9bGD4LS6l9aexvOD6DK7DnQ* value_p2, NI* pos_p3) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("mtMarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{nimErr_ = nimErrorFlag();
	{
		if (!NIM_TRUE) goto LA3_;
		nimln_(140);		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = mtMarshalValue__test95multi95thread95request95broker_u396(buf_p0, cap_p1, (*value_p2).textValue, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T7_)) goto LA8_;
			nimln_(141);			nimln_(91);			nimln_(141);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA8_: ;
	}
LA3_: ;
	{
		if (!NIM_TRUE) goto LA12_;
		nimln_(140);		{
			NIM_BOOL T16_;
			T16_ = (NIM_BOOL)0;
			T16_ = mtMarshalValue__test95multi95thread95request95broker_u372(buf_p0, cap_p1, (*value_p2).numValue, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T16_)) goto LA17_;
			nimln_(141);			nimln_(91);			nimln_(141);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA17_: ;
	}
LA12_: ;
	{
		if (!NIM_TRUE) goto LA21_;
		nimln_(140);		{
			NIM_BOOL T25_;
			T25_ = (NIM_BOOL)0;
			T25_ = mtMarshalValue__test95multi95thread95request95broker_u760(buf_p0, cap_p1, (*value_p2).boolValue, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T25_)) goto LA26_;
			nimln_(141);			nimln_(91);			nimln_(141);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA26_: ;
	}
LA21_: ;
	nimln_(142);	nimln_(91);	nimln_(142);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95multi95thread95request95broker_u628)(NimStringV2 value_p0) {
	NI result;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_20;
	nimfr_("mtMarshalSizeValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(246);	nimln_(236);	nimln_(246);	if (nimAddInt(((NI)4), value_p0.len, &TM__gSOrWU7W2lzpIJkvkwiA9bw_20)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_20);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95multi95thread95request95broker_u613)(NI value_p0) {
	NI result;
	nimfr_("mtMarshalSizeValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(244);	nimln_(236);	nimln_(244);	result = ((NI)8);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95multi95thread95request95broker_u1120)(NIM_BOOL value_p0) {
	NI result;
	nimfr_("mtMarshalSizeValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(244);	nimln_(236);	nimln_(244);	result = ((NI)1);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95multi95thread95request95broker_u1093)(tyObject_MTReq__D9bGD4LS6l9aexvOD6DK7DnQ* value_p0) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("mtMarshalSizeValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{nimErr_ = nimErrorFlag();
	nimln_(254);	result = ((NI)0);
	{
		NI T5_;
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_21;
		if (!NIM_TRUE) goto LA3_;
		nimln_(256);		T5_ = (NI)0;
		T5_ = mtMarshalSizeValue__test95multi95thread95request95broker_u628((*value_p0).textValue);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt(result, T5_, &TM__gSOrWU7W2lzpIJkvkwiA9bw_21)) { raiseOverflow(); goto BeforeRet_;
		};
		result = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_21);
	}
LA3_: ;
	{
		NI T10_;
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_22;
		if (!NIM_TRUE) goto LA8_;
		nimln_(256);		T10_ = (NI)0;
		T10_ = mtMarshalSizeValue__test95multi95thread95request95broker_u613((*value_p0).numValue);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt(result, T10_, &TM__gSOrWU7W2lzpIJkvkwiA9bw_22)) { raiseOverflow(); goto BeforeRet_;
		};
		result = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_22);
	}
LA8_: ;
	{
		NI T15_;
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_23;
		if (!NIM_TRUE) goto LA13_;
		nimln_(256);		T15_ = (NI)0;
		T15_ = mtMarshalSizeValue__test95multi95thread95request95broker_u1120((*value_p0).boolValue);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt(result, T15_, &TM__gSOrWU7W2lzpIJkvkwiA9bw_23)) { raiseOverflow(); goto BeforeRet_;
		};
		result = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_23);
	}
LA13_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95multi95thread95request95broker_u416)(NU8* buf_p0, NI cap_p1, NU32 value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_25;
	nimfr_("mtMarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(115);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_24;
		if (nimAddInt((*pos_p3), ((NI)4), &TM__gSOrWU7W2lzpIJkvkwiA9bw_24)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(cap_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_24))) goto LA3_;
		nimln_(116);		nimln_(91);		nimln_(116);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(117);	copyMem__system_u1731(((void*) ((&buf_p0[(*pos_p3)]))), ((void*) ((&value_p2))), ((NI)4));
	nimln_(118);	if (nimAddInt((*pos_p3), ((NI)4), &TM__gSOrWU7W2lzpIJkvkwiA9bw_25)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_25);
	nimln_(119);	nimln_(91);	nimln_(119);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95multi95thread95request95broker_u440)(NU8* buf_p0, NI cap_p1, tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA* value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_27;
	nimfr_("mtMarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(115);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_26;
		if (nimAddInt((*pos_p3), ((NI)8), &TM__gSOrWU7W2lzpIJkvkwiA9bw_26)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(cap_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_26))) goto LA3_;
		nimln_(116);		nimln_(91);		nimln_(116);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(117);	copyMem__system_u1731(((void*) ((&buf_p0[(*pos_p3)]))), ((void*) (&value_p2)), ((NI)8));
	nimln_(118);	if (nimAddInt((*pos_p3), ((NI)8), &TM__gSOrWU7W2lzpIJkvkwiA9bw_27)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_27);
	nimln_(119);	nimln_(91);	nimln_(119);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95multi95thread95request95broker_u356)(NU8* buf_p0, NI cap_p1, tyObject_MTReqMtRequestMsg__Jr5le9cACMNSqErDTdY9ckdg* value_p2, NI* pos_p3) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("mtMarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{nimErr_ = nimErrorFlag();
	{
		if (!NIM_TRUE) goto LA3_;
		nimln_(140);		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = mtMarshalValue__test95multi95thread95request95broker_u372(buf_p0, cap_p1, (*value_p2).requestKind, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T7_)) goto LA8_;
			nimln_(141);			nimln_(91);			nimln_(141);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA8_: ;
	}
LA3_: ;
	{
		if (!NIM_TRUE) goto LA12_;
		nimln_(140);		{
			NIM_BOOL T16_;
			T16_ = (NIM_BOOL)0;
			T16_ = mtMarshalValue__test95multi95thread95request95broker_u396(buf_p0, cap_p1, (*value_p2).input, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T16_)) goto LA17_;
			nimln_(141);			nimln_(91);			nimln_(141);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA17_: ;
	}
LA12_: ;
	{
		if (!NIM_TRUE) goto LA21_;
		nimln_(140);		{
			NIM_BOOL T25_;
			T25_ = (NIM_BOOL)0;
			T25_ = mtMarshalValue__test95multi95thread95request95broker_u416(buf_p0, cap_p1, (*value_p2).responseSlotIdx, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T25_)) goto LA26_;
			nimln_(141);			nimln_(91);			nimln_(141);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA26_: ;
	}
LA21_: ;
	{
		if (!NIM_TRUE) goto LA30_;
		nimln_(140);		{
			NIM_BOOL T34_;
			T34_ = (NIM_BOOL)0;
			T34_ = mtMarshalValue__test95multi95thread95request95broker_u440(buf_p0, cap_p1, (*value_p2).requesterSignal, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T34_)) goto LA35_;
			nimln_(141);			nimln_(91);			nimln_(141);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA35_: ;
	}
LA30_: ;
	nimln_(142);	nimln_(91);	nimln_(142);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95multi95thread95request95broker_u640)(NU32 value_p0) {
	NI result;
	nimfr_("mtMarshalSizeValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(244);	nimln_(236);	nimln_(244);	result = ((NI)4);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95multi95thread95request95broker_u655)(tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA* value_p0) {
	NI result;
	nimfr_("mtMarshalSizeValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(244);	nimln_(236);	nimln_(244);	result = ((NI)8);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95multi95thread95request95broker_u600)(tyObject_MTReqMtRequestMsg__Jr5le9cACMNSqErDTdY9ckdg* value_p0) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("mtMarshalSizeValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{nimErr_ = nimErrorFlag();
	nimln_(254);	result = ((NI)0);
	{
		NI T5_;
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_28;
		if (!NIM_TRUE) goto LA3_;
		nimln_(256);		T5_ = (NI)0;
		T5_ = mtMarshalSizeValue__test95multi95thread95request95broker_u613((*value_p0).requestKind);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt(result, T5_, &TM__gSOrWU7W2lzpIJkvkwiA9bw_28)) { raiseOverflow(); goto BeforeRet_;
		};
		result = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_28);
	}
LA3_: ;
	{
		NI T10_;
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_29;
		if (!NIM_TRUE) goto LA8_;
		nimln_(256);		T10_ = (NI)0;
		T10_ = mtMarshalSizeValue__test95multi95thread95request95broker_u628((*value_p0).input);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt(result, T10_, &TM__gSOrWU7W2lzpIJkvkwiA9bw_29)) { raiseOverflow(); goto BeforeRet_;
		};
		result = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_29);
	}
LA8_: ;
	{
		NI T15_;
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_30;
		if (!NIM_TRUE) goto LA13_;
		nimln_(256);		T15_ = (NI)0;
		T15_ = mtMarshalSizeValue__test95multi95thread95request95broker_u640((*value_p0).responseSlotIdx);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt(result, T15_, &TM__gSOrWU7W2lzpIJkvkwiA9bw_30)) { raiseOverflow(); goto BeforeRet_;
		};
		result = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_30);
	}
LA13_: ;
	{
		NI T20_;
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_31;
		if (!NIM_TRUE) goto LA18_;
		nimln_(256);		T20_ = (NI)0;
		T20_ = mtMarshalSizeValue__test95multi95thread95request95broker_u655((*value_p0).requesterSignal);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt(result, T20_, &TM__gSOrWU7W2lzpIJkvkwiA9bw_31)) { raiseOverflow(); goto BeforeRet_;
		};
		result = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_31);
	}
LA18_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95multi95thread95request95broker_u989)(NU8* buf_p0, NI len_p1, NIM_BOOL* value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_33;
	nimfr_("mtUnmarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(175);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_32;
		if (nimAddInt((*pos_p3), ((NI)1), &TM__gSOrWU7W2lzpIJkvkwiA9bw_32)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(len_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_32))) goto LA3_;
		nimln_(176);		nimln_(153);		nimln_(176);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(177);	copyMem__system_u1731(((void*) (value_p2)), ((void*) ((&buf_p0[(*pos_p3)]))), ((NI)1));
	nimln_(178);	if (nimAddInt((*pos_p3), ((NI)1), &TM__gSOrWU7W2lzpIJkvkwiA9bw_33)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_33);
	nimln_(179);	nimln_(153);	nimln_(179);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95multi95thread95request95broker_u961)(NU8* buf_p0, NI len_p1, tyObject_MTReq__D9bGD4LS6l9aexvOD6DK7DnQ* value_p2, NI* pos_p3) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("mtUnmarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{nimErr_ = nimErrorFlag();
	{
		if (!NIM_TRUE) goto LA3_;
		nimln_(202);		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = mtUnmarshalValue__test95multi95thread95request95broker_u529(buf_p0, len_p1, (&(*value_p2).textValue), pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T7_)) goto LA8_;
			nimln_(203);			nimln_(153);			nimln_(203);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA8_: ;
	}
LA3_: ;
	{
		if (!NIM_TRUE) goto LA12_;
		nimln_(202);		{
			NIM_BOOL T16_;
			T16_ = (NIM_BOOL)0;
			T16_ = mtUnmarshalValue__test95multi95thread95request95broker_u505(buf_p0, len_p1, (&(*value_p2).numValue), pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T16_)) goto LA17_;
			nimln_(203);			nimln_(153);			nimln_(203);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA17_: ;
	}
LA12_: ;
	{
		if (!NIM_TRUE) goto LA21_;
		nimln_(202);		{
			NIM_BOOL T25_;
			T25_ = (NIM_BOOL)0;
			T25_ = mtUnmarshalValue__test95multi95thread95request95broker_u989(buf_p0, len_p1, (&(*value_p2).boolValue), pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T25_)) goto LA26_;
			nimln_(203);			nimln_(153);			nimln_(203);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA26_: ;
	}
LA21_: ;
	nimln_(204);	nimln_(153);	nimln_(204);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95multi95thread95request95broker_u24092)(NU8* buf_p0, NI len_p1, tyObject_MtVoidReqMtRequestMsg__emjMGmY31bA062xiU38zpQ* value_p2, NI* pos_p3) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("mtUnmarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{nimErr_ = nimErrorFlag();
	{
		if (!NIM_TRUE) goto LA3_;
		nimln_(202);		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = mtUnmarshalValue__test95multi95thread95request95broker_u505(buf_p0, len_p1, (&(*value_p2).requestKind), pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T7_)) goto LA8_;
			nimln_(203);			nimln_(153);			nimln_(203);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA8_: ;
	}
LA3_: ;
	{
		if (!NIM_TRUE) goto LA12_;
		nimln_(202);		{
			NIM_BOOL T16_;
			T16_ = (NIM_BOOL)0;
			T16_ = mtUnmarshalValue__test95multi95thread95request95broker_u529(buf_p0, len_p1, (&(*value_p2).label), pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T16_)) goto LA17_;
			nimln_(203);			nimln_(153);			nimln_(203);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA17_: ;
	}
LA12_: ;
	{
		if (!NIM_TRUE) goto LA21_;
		nimln_(202);		{
			NIM_BOOL T25_;
			T25_ = (NIM_BOOL)0;
			T25_ = mtUnmarshalValue__test95multi95thread95request95broker_u549(buf_p0, len_p1, (&(*value_p2).responseSlotIdx), pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T25_)) goto LA26_;
			nimln_(203);			nimln_(153);			nimln_(203);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA26_: ;
	}
LA21_: ;
	{
		if (!NIM_TRUE) goto LA30_;
		nimln_(202);		{
			NIM_BOOL T34_;
			T34_ = (NIM_BOOL)0;
			T34_ = mtUnmarshalValue__test95multi95thread95request95broker_u573(buf_p0, len_p1, &(*value_p2).requesterSignal, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T34_)) goto LA35_;
			nimln_(203);			nimln_(153);			nimln_(203);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA35_: ;
	}
LA30_: ;
	nimln_(204);	nimln_(153);	nimln_(204);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95multi95thread95request95broker_u24238)(NU8* buf_p0, NI cap_p1, tyObject_MtVoidReq__8CJNW2loTYKn0f0dxv0TmQ value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_35;
	nimfr_("mtMarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(115);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_34;
		if (nimAddInt((*pos_p3), ((NI)1), &TM__gSOrWU7W2lzpIJkvkwiA9bw_34)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(cap_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_34))) goto LA3_;
		nimln_(116);		nimln_(91);		nimln_(116);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(117);	copyMem__system_u1731(((void*) ((&buf_p0[(*pos_p3)]))), ((void*) ((&value_p2))), ((NI)1));
	nimln_(118);	if (nimAddInt((*pos_p3), ((NI)1), &TM__gSOrWU7W2lzpIJkvkwiA9bw_35)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_35);
	nimln_(119);	nimln_(91);	nimln_(119);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95multi95thread95request95broker_u24476)(tyObject_MtVoidReq__8CJNW2loTYKn0f0dxv0TmQ value_p0) {
	NI result;
	nimfr_("mtMarshalSizeValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(244);	nimln_(236);	nimln_(244);	result = ((NI)1);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95multi95thread95request95broker_u24046)(NU8* buf_p0, NI cap_p1, tyObject_MtVoidReqMtRequestMsg__emjMGmY31bA062xiU38zpQ* value_p2, NI* pos_p3) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("mtMarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{nimErr_ = nimErrorFlag();
	{
		if (!NIM_TRUE) goto LA3_;
		nimln_(140);		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = mtMarshalValue__test95multi95thread95request95broker_u372(buf_p0, cap_p1, (*value_p2).requestKind, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T7_)) goto LA8_;
			nimln_(141);			nimln_(91);			nimln_(141);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA8_: ;
	}
LA3_: ;
	{
		if (!NIM_TRUE) goto LA12_;
		nimln_(140);		{
			NIM_BOOL T16_;
			T16_ = (NIM_BOOL)0;
			T16_ = mtMarshalValue__test95multi95thread95request95broker_u396(buf_p0, cap_p1, (*value_p2).label, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T16_)) goto LA17_;
			nimln_(141);			nimln_(91);			nimln_(141);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA17_: ;
	}
LA12_: ;
	{
		if (!NIM_TRUE) goto LA21_;
		nimln_(140);		{
			NIM_BOOL T25_;
			T25_ = (NIM_BOOL)0;
			T25_ = mtMarshalValue__test95multi95thread95request95broker_u416(buf_p0, cap_p1, (*value_p2).responseSlotIdx, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T25_)) goto LA26_;
			nimln_(141);			nimln_(91);			nimln_(141);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA26_: ;
	}
LA21_: ;
	{
		if (!NIM_TRUE) goto LA30_;
		nimln_(140);		{
			NIM_BOOL T34_;
			T34_ = (NIM_BOOL)0;
			T34_ = mtMarshalValue__test95multi95thread95request95broker_u440(buf_p0, cap_p1, (*value_p2).requesterSignal, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T34_)) goto LA35_;
			nimln_(141);			nimln_(91);			nimln_(141);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA35_: ;
	}
LA30_: ;
	nimln_(142);	nimln_(91);	nimln_(142);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95multi95thread95request95broker_u24135)(tyObject_MtVoidReqMtRequestMsg__emjMGmY31bA062xiU38zpQ* value_p0) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("mtMarshalSizeValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{nimErr_ = nimErrorFlag();
	nimln_(254);	result = ((NI)0);
	{
		NI T5_;
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_36;
		if (!NIM_TRUE) goto LA3_;
		nimln_(256);		T5_ = (NI)0;
		T5_ = mtMarshalSizeValue__test95multi95thread95request95broker_u613((*value_p0).requestKind);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt(result, T5_, &TM__gSOrWU7W2lzpIJkvkwiA9bw_36)) { raiseOverflow(); goto BeforeRet_;
		};
		result = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_36);
	}
LA3_: ;
	{
		NI T10_;
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_37;
		if (!NIM_TRUE) goto LA8_;
		nimln_(256);		T10_ = (NI)0;
		T10_ = mtMarshalSizeValue__test95multi95thread95request95broker_u628((*value_p0).label);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt(result, T10_, &TM__gSOrWU7W2lzpIJkvkwiA9bw_37)) { raiseOverflow(); goto BeforeRet_;
		};
		result = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_37);
	}
LA8_: ;
	{
		NI T15_;
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_38;
		if (!NIM_TRUE) goto LA13_;
		nimln_(256);		T15_ = (NI)0;
		T15_ = mtMarshalSizeValue__test95multi95thread95request95broker_u640((*value_p0).responseSlotIdx);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt(result, T15_, &TM__gSOrWU7W2lzpIJkvkwiA9bw_38)) { raiseOverflow(); goto BeforeRet_;
		};
		result = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_38);
	}
LA13_: ;
	{
		NI T20_;
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_39;
		if (!NIM_TRUE) goto LA18_;
		nimln_(256);		T20_ = (NI)0;
		T20_ = mtMarshalSizeValue__test95multi95thread95request95broker_u655((*value_p0).requesterSignal);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt(result, T20_, &TM__gSOrWU7W2lzpIJkvkwiA9bw_39)) { raiseOverflow(); goto BeforeRet_;
		};
		result = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_39);
	}
LA18_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95multi95thread95request95broker_u24378)(NU8* buf_p0, NI len_p1, tyObject_MtVoidReq__8CJNW2loTYKn0f0dxv0TmQ* value_p2, NI* pos_p3) {
	NIM_BOOL result;
	NI TM__gSOrWU7W2lzpIJkvkwiA9bw_41;
	nimfr_("mtUnmarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{	nimln_(175);	{
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_40;
		if (nimAddInt((*pos_p3), ((NI)1), &TM__gSOrWU7W2lzpIJkvkwiA9bw_40)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!(len_p1 < (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_40))) goto LA3_;
		nimln_(176);		nimln_(153);		nimln_(176);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(177);	copyMem__system_u1731(((void*) (value_p2)), ((void*) ((&buf_p0[(*pos_p3)]))), ((NI)1));
	nimln_(178);	if (nimAddInt((*pos_p3), ((NI)1), &TM__gSOrWU7W2lzpIJkvkwiA9bw_41)) { raiseOverflow(); goto BeforeRet_;
	};
	(*pos_p3) = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_41);
	nimln_(179);	nimln_(153);	nimln_(179);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtUnmarshalValue__test95multi95thread95request95broker_u29380)(NU8* buf_p0, NI len_p1, tyObject_SugarVoidMtRequestMsg__Gn9c8m2r9aICzncdczGNQ76g* value_p2, NI* pos_p3) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("mtUnmarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{nimErr_ = nimErrorFlag();
	{
		if (!NIM_TRUE) goto LA3_;
		nimln_(202);		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = mtUnmarshalValue__test95multi95thread95request95broker_u505(buf_p0, len_p1, (&(*value_p2).requestKind), pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T7_)) goto LA8_;
			nimln_(203);			nimln_(153);			nimln_(203);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA8_: ;
	}
LA3_: ;
	{
		if (!NIM_TRUE) goto LA12_;
		nimln_(202);		{
			NIM_BOOL T16_;
			T16_ = (NIM_BOOL)0;
			T16_ = mtUnmarshalValue__test95multi95thread95request95broker_u529(buf_p0, len_p1, (&(*value_p2).label), pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T16_)) goto LA17_;
			nimln_(203);			nimln_(153);			nimln_(203);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA17_: ;
	}
LA12_: ;
	{
		if (!NIM_TRUE) goto LA21_;
		nimln_(202);		{
			NIM_BOOL T25_;
			T25_ = (NIM_BOOL)0;
			T25_ = mtUnmarshalValue__test95multi95thread95request95broker_u549(buf_p0, len_p1, (&(*value_p2).responseSlotIdx), pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T25_)) goto LA26_;
			nimln_(203);			nimln_(153);			nimln_(203);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA26_: ;
	}
LA21_: ;
	{
		if (!NIM_TRUE) goto LA30_;
		nimln_(202);		{
			NIM_BOOL T34_;
			T34_ = (NIM_BOOL)0;
			T34_ = mtUnmarshalValue__test95multi95thread95request95broker_u573(buf_p0, len_p1, &(*value_p2).requesterSignal, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T34_)) goto LA35_;
			nimln_(203);			nimln_(153);			nimln_(203);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA35_: ;
	}
LA30_: ;
	nimln_(204);	nimln_(153);	nimln_(204);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mtMarshalValue__test95multi95thread95request95broker_u29334)(NU8* buf_p0, NI cap_p1, tyObject_SugarVoidMtRequestMsg__Gn9c8m2r9aICzncdczGNQ76g* value_p2, NI* pos_p3) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("mtMarshalValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{nimErr_ = nimErrorFlag();
	{
		if (!NIM_TRUE) goto LA3_;
		nimln_(140);		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = mtMarshalValue__test95multi95thread95request95broker_u372(buf_p0, cap_p1, (*value_p2).requestKind, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T7_)) goto LA8_;
			nimln_(141);			nimln_(91);			nimln_(141);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA8_: ;
	}
LA3_: ;
	{
		if (!NIM_TRUE) goto LA12_;
		nimln_(140);		{
			NIM_BOOL T16_;
			T16_ = (NIM_BOOL)0;
			T16_ = mtMarshalValue__test95multi95thread95request95broker_u396(buf_p0, cap_p1, (*value_p2).label, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T16_)) goto LA17_;
			nimln_(141);			nimln_(91);			nimln_(141);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA17_: ;
	}
LA12_: ;
	{
		if (!NIM_TRUE) goto LA21_;
		nimln_(140);		{
			NIM_BOOL T25_;
			T25_ = (NIM_BOOL)0;
			T25_ = mtMarshalValue__test95multi95thread95request95broker_u416(buf_p0, cap_p1, (*value_p2).responseSlotIdx, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T25_)) goto LA26_;
			nimln_(141);			nimln_(91);			nimln_(141);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA26_: ;
	}
LA21_: ;
	{
		if (!NIM_TRUE) goto LA30_;
		nimln_(140);		{
			NIM_BOOL T34_;
			T34_ = (NIM_BOOL)0;
			T34_ = mtMarshalValue__test95multi95thread95request95broker_u440(buf_p0, cap_p1, (*value_p2).requesterSignal, pos_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T34_)) goto LA35_;
			nimln_(141);			nimln_(91);			nimln_(141);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA35_: ;
	}
LA30_: ;
	nimln_(142);	nimln_(91);	nimln_(142);	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, mtMarshalSizeValue__test95multi95thread95request95broker_u29423)(tyObject_SugarVoidMtRequestMsg__Gn9c8m2r9aICzncdczGNQ76g* value_p0) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("mtMarshalSizeValue", "/Users/schwarzy/dev/status/nim-brokers/brokers/internal/mt_codec.nim");
{nimErr_ = nimErrorFlag();
	nimln_(254);	result = ((NI)0);
	{
		NI T5_;
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_42;
		if (!NIM_TRUE) goto LA3_;
		nimln_(256);		T5_ = (NI)0;
		T5_ = mtMarshalSizeValue__test95multi95thread95request95broker_u613((*value_p0).requestKind);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt(result, T5_, &TM__gSOrWU7W2lzpIJkvkwiA9bw_42)) { raiseOverflow(); goto BeforeRet_;
		};
		result = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_42);
	}
LA3_: ;
	{
		NI T10_;
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_43;
		if (!NIM_TRUE) goto LA8_;
		nimln_(256);		T10_ = (NI)0;
		T10_ = mtMarshalSizeValue__test95multi95thread95request95broker_u628((*value_p0).label);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt(result, T10_, &TM__gSOrWU7W2lzpIJkvkwiA9bw_43)) { raiseOverflow(); goto BeforeRet_;
		};
		result = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_43);
	}
LA8_: ;
	{
		NI T15_;
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_44;
		if (!NIM_TRUE) goto LA13_;
		nimln_(256);		T15_ = (NI)0;
		T15_ = mtMarshalSizeValue__test95multi95thread95request95broker_u640((*value_p0).responseSlotIdx);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt(result, T15_, &TM__gSOrWU7W2lzpIJkvkwiA9bw_44)) { raiseOverflow(); goto BeforeRet_;
		};
		result = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_44);
	}
LA13_: ;
	{
		NI T20_;
		NI TM__gSOrWU7W2lzpIJkvkwiA9bw_45;
		if (!NIM_TRUE) goto LA18_;
		nimln_(256);		T20_ = (NI)0;
		T20_ = mtMarshalSizeValue__test95multi95thread95request95broker_u655((*value_p0).requesterSignal);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt(result, T20_, &TM__gSOrWU7W2lzpIJkvkwiA9bw_45)) { raiseOverflow(); goto BeforeRet_;
		};
		result = (NI)(TM__gSOrWU7W2lzpIJkvkwiA9bw_45);
	}
LA18_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
