/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c -w -ferror-limit=3 -pthread --coverage -O0 -g   -I/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib -I/Users/schwarzy/dev/status/nim-brokers/test -o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_broker_oop/@m..@sbrokers@sinternal@smt_broker_common.nim.c.o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_broker_oop/@m..@sbrokers@sinternal@smt_broker_common.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <sys/types.h>
                          #include <pthread.h>
#include <stdatomic.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tySequence__Mx0p1ZaiROYzIPrPGooHBw tySequence__Mx0p1ZaiROYzIPrPGooHBw;
typedef struct tySequence__Mx0p1ZaiROYzIPrPGooHBw_Content tySequence__Mx0p1ZaiROYzIPrPGooHBw_Content;
typedef struct tySequence__H1e9bhqvuqHJfqjIpHMVFBw tySequence__H1e9bhqvuqHJfqjIpHMVFBw;
typedef struct tySequence__H1e9bhqvuqHJfqjIpHMVFBw_Content tySequence__H1e9bhqvuqHJfqjIpHMVFBw_Content;
typedef struct tyTuple__S3hkl0GBBZB9bYJWJW8ncdg tyTuple__S3hkl0GBBZB9bYJWJW8ncdg;
typedef struct tyObject_Result__lRIJHt83bu8ekc73M9cJVdQ tyObject_Result__lRIJHt83bu8ekc73M9cJVdQ;
typedef struct tyObject_Atomic__9cNev5PAybA2HSmjTw2bLWw tyObject_Atomic__9cNev5PAybA2HSmjTw2bLWw;
typedef struct tyObject_Atomic__7HvK9cyFE72PvbWunNuTqaA tyObject_Atomic__7HvK9cyFE72PvbWunNuTqaA;
typedef struct tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA;
typedef struct tyObject_PendingRingFree__JiJjOuD2t1NlpDr7ogTCoA tyObject_PendingRingFree__JiJjOuD2t1NlpDr7ogTCoA;
typedef struct tyObject_VyukovMpscRing__2hRU9cR27V9cKqsVXJJLUACg tyObject_VyukovMpscRing__2hRU9cR27V9cKqsVXJJLUACg;
typedef struct tyObject_PayloadSlab__i387b0oh8wCHdJIndXphqQ tyObject_PayloadSlab__i387b0oh8wCHdJIndXphqQ;
typedef struct tyObject_ResponseSlotPool__X65bQG4NXJgVbxwOX0m1MQ tyObject_ResponseSlotPool__X65bQG4NXJgVbxwOX0m1MQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct tySequence__Mx0p1ZaiROYzIPrPGooHBw {
  NI len; tySequence__Mx0p1ZaiROYzIPrPGooHBw_Content* p;
};
struct tySequence__H1e9bhqvuqHJfqjIpHMVFBw {
  NI len; tySequence__H1e9bhqvuqHJfqjIpHMVFBw_Content* p;
};
typedef N_NIMCALL_PTR(tyObject_Result__lRIJHt83bu8ekc73M9cJVdQ, tyProc__ciT0CF0vTVaueE5Dsp9caNA) (NU32 ctx_p0);
struct tyTuple__S3hkl0GBBZB9bYJWJW8ncdg {
	NU16 Field0;
	tyProc__ciT0CF0vTVaueE5Dsp9caNA Field1;
};
typedef tyTuple__S3hkl0GBBZB9bYJWJW8ncdg tyArray__MtzLOHeGagn6TGgk2X4NhQ[64];
struct tyObject_Atomic__9cNev5PAybA2HSmjTw2bLWw {
	_Atomic NI64 value;
};
struct tyObject_Atomic__7HvK9cyFE72PvbWunNuTqaA {
	_Atomic NI64 value;
};
typedef struct {
N_NIMCALL_PTR(NI, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__tgsNrU35ceaIgGiec9cpZng;
struct tySequence__Mx0p1ZaiROYzIPrPGooHBw_Content { NI cap; tyProc__tgsNrU35ceaIgGiec9cpZng data[SEQ_DECL_SIZE]; };
struct tyObject_PendingRingFree__JiJjOuD2t1NlpDr7ogTCoA {
	tyObject_VyukovMpscRing__2hRU9cR27V9cKqsVXJJLUACg* ring;
	tyObject_PayloadSlab__i387b0oh8wCHdJIndXphqQ* slab;
	tyObject_ResponseSlotPool__X65bQG4NXJgVbxwOX0m1MQ* pool;
};
struct tySequence__H1e9bhqvuqHJfqjIpHMVFBw_Content { NI cap; tyObject_PendingRingFree__JiJjOuD2t1NlpDr7ogTCoA data[SEQ_DECL_SIZE]; };
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_Result__lRIJHt83bu8ekc73M9cJVdQ {
	NIM_BOOL oResultPrivate;
union{
	struct {
	NimStringV2 eResultPrivate;
} _oResultPrivate_1;
};
};
N_LIB_PRIVATE NIM_THREADVAR tySequence__Mx0p1ZaiROYzIPrPGooHBw gBrokerThreadPollers__OOZbrokersZinternalZmt95broker95common_u235;
N_LIB_PRIVATE NIM_THREADVAR tySequence__H1e9bhqvuqHJfqjIpHMVFBw gPendingRingFrees__OOZbrokersZinternalZmt95broker95common_u965;
N_LIB_PRIVATE tyArray__MtzLOHeGagn6TGgk2X4NhQ gApiCtxInstallers__OOZbrokersZinternalZmt95broker95common_u20;
N_LIB_PRIVATE NI gApiCtxInstallerCount__OOZbrokersZinternalZmt95broker95common_u21;
N_LIB_PRIVATE pthread_mutex_t gApiCtxInstallerLock__OOZbrokersZinternalZmt95broker95common_u22;
N_LIB_PRIVATE tyObject_Atomic__9cNev5PAybA2HSmjTw2bLWw gApiCtxInstallerLockInit__OOZbrokersZinternalZmt95broker95common_u24;
N_LIB_PRIVATE NIM_THREADVAR NIM_BOOL mtThreadIdMarker__OOZbrokersZinternalZmt95broker95common_u189;
N_LIB_PRIVATE tyObject_Atomic__7HvK9cyFE72PvbWunNuTqaA gMtThreadGenCounter__OOZbrokersZinternalZmt95broker95common_u192;
N_LIB_PRIVATE NIM_THREADVAR NU64 mtThreadGen__OOZbrokersZinternalZmt95broker95common_u193;
N_LIB_PRIVATE NIM_THREADVAR NIM_BOOL mtThreadGenInitialized__OOZbrokersZinternalZmt95broker95common_u194;
N_LIB_PRIVATE NIM_THREADVAR tyObject_ThreadSignal__PJYS7jy6RbSkONg9c9aivCRA* gBrokerThreadSignal__OOZbrokersZinternalZmt95broker95common_u234;
N_LIB_PRIVATE NIM_THREADVAR NIM_BOOL gBrokerDispatchStarted__OOZbrokersZinternalZmt95broker95common_u236;
N_LIB_PRIVATE NIM_THREADVAR NIM_BOOL gBrokerDispatchStopRequested__OOZbrokersZinternalZmt95broker95common_u237;
