## Generated C++ header-only wrapper for the CBOR FFI surface.
##
## The wrapper lives entirely in headers — no separate translation
## unit — so foreign C++ projects only need to link the Nim-built
## shared library and `#include` the generated `<lib>.hpp`.
##
## Phase 4b deliverable: namespace + RAII `Lib` class wrapping context
## lifecycle, a `Result<T>` value type, and a `rawCall` helper that
## handles buffer ownership + status code interpretation. The typed
## per-request and per-event methods generated from the broker
## declarations land in Phase 4c / 4d.
##
## Phase 4c onward will append `JSONCONS_ALL_MEMBER_TRAITS_NAMED_DECL`
## macro calls and typed wrappers that go through `jsoncons::cbor`.

{.push raises: [].}

import std/[macros, os, strutils]
import ./api_codegen_c, ./api_common

{.pop.}

proc generateCborCppHeaderFile*(
    outDir: string,
    libName: string,
    requestApiNames: seq[string],
    eventApiNames: seq[string],
) {.compileTime, raises: [].} =
  ## Writes the C++ wrapper header (.hpp) for a CBOR-mode library.
  ##
  ## The skeleton-level deliverable: namespace, Result<T>, RAII Lib
  ## class with rawCall. Per-request and per-event typed methods are
  ## appended in later phases by re-running this with extended inputs.
  ensureGeneratedOutputDir(outDir)

  let guardName = libName.toUpperAscii().replace("-", "_") & "_HPP"
  let headerPath =
    if outDir.len > 0:
      outDir & "/" & libName & ".hpp"
    else:
      libName & ".hpp"
  let p = libName & "_"

  var h =
    "// Generated by nim-brokers CBOR FFI codegen — do not edit.\n" & "//\n" &
    "// Header-only C++ wrapper around the C ABI declared in `" & libName & ".h`.\n" &
    "// Requires C++17 (uses std::optional). Phase 4c will add\n" &
    "// jsoncons::cbor-backed typed request and event methods.\n" & "#ifndef " &
    guardName & "\n" & "#define " & guardName & "\n\n" & "#include \"" & libName &
    ".h\"\n\n" & "#include <cstdint>\n" & "#include <cstring>\n" &
    "#include <optional>\n" & "#include <string>\n" & "#include <utility>\n" &
    "#include <vector>\n\n" & "namespace " & libName & " {\n\n"

  # Result<T>
  h.add("// Minimal Result<T> mirroring Nim's Result[T, string] envelope on\n")
  h.add("// the wire. Constructors are private; use ok() / err() factories.\n")
  h.add("template <typename T>\n")
  h.add("class Result {\n")
  h.add(" public:\n")
  h.add("  static Result<T> ok(T value) {\n")
  h.add("    Result<T> r;\n")
  h.add("    r.ok_ = true;\n")
  h.add("    r.value_ = std::move(value);\n")
  h.add("    return r;\n")
  h.add("  }\n")
  h.add("  static Result<T> err(std::string message) {\n")
  h.add("    Result<T> r;\n")
  h.add("    r.ok_ = false;\n")
  h.add("    r.error_ = std::move(message);\n")
  h.add("    return r;\n")
  h.add("  }\n")
  h.add("  bool isOk() const { return ok_; }\n")
  h.add("  bool isErr() const { return !ok_; }\n")
  h.add("  const T& value() const { return value_; }\n")
  h.add("  T&& take() { return std::move(value_); }\n")
  h.add("  const std::string& error() const { return error_; }\n")
  h.add(" private:\n")
  h.add("  bool ok_ = false;\n")
  h.add("  T value_{};\n")
  h.add("  std::string error_;\n")
  h.add("};\n\n")

  # RAII Lib class
  h.add("// RAII wrapper around the library's context. Construction calls\n")
  h.add("// " & p & "initialize() and " & p & "createContext(); destruction calls\n")
  h.add("// " & p & "shutdown(). Non-copyable, movable.\n")
  h.add("//\n")
  h.add("// On construction failure (createContext returned 0), isOk() is false\n")
  h.add("// and lastError() carries the message from the C side. Subsequent\n")
  h.add("// rawCall() invocations short-circuit to a framework error.\n")
  h.add("class Lib {\n")
  h.add(" public:\n")
  h.add("  Lib() {\n")
  h.add("    " & p & "initialize();\n")
  h.add("    char* err = nullptr;\n")
  h.add("    ctx_ = " & p & "createContext(&err);\n")
  h.add("    if (ctx_ == 0) {\n")
  h.add("      if (err != nullptr) {\n")
  h.add("        lastError_ = err;\n")
  h.add("        " & p & "freeBuffer(err);\n")
  h.add("      } else {\n")
  h.add("        lastError_ = \"createContext returned 0 with no error message\";\n")
  h.add("      }\n")
  h.add("    }\n")
  h.add("  }\n\n")
  h.add("  ~Lib() {\n")
  h.add("    if (ctx_ != 0) {\n")
  h.add("      " & p & "shutdown(ctx_);\n")
  h.add("    }\n")
  h.add("  }\n\n")
  h.add("  Lib(const Lib&) = delete;\n")
  h.add("  Lib& operator=(const Lib&) = delete;\n")
  h.add("  Lib(Lib&& other) noexcept\n")
  h.add("      : ctx_(other.ctx_), lastError_(std::move(other.lastError_)) {\n")
  h.add("    other.ctx_ = 0;\n")
  h.add("  }\n")
  h.add("  Lib& operator=(Lib&& other) noexcept {\n")
  h.add("    if (this != &other) {\n")
  h.add("      if (ctx_ != 0) " & p & "shutdown(ctx_);\n")
  h.add("      ctx_ = other.ctx_;\n")
  h.add("      lastError_ = std::move(other.lastError_);\n")
  h.add("      other.ctx_ = 0;\n")
  h.add("    }\n")
  h.add("    return *this;\n")
  h.add("  }\n\n")
  h.add("  bool isOk() const { return ctx_ != 0; }\n")
  h.add("  const std::string& lastError() const { return lastError_; }\n")
  h.add("  uint32_t context() const { return ctx_; }\n\n")
  h.add("  // Per-request and per-event typed methods land in later phases.\n\n")
  h.add(" protected:\n")
  h.add("  // Internal: dispatch a CBOR-encoded request through the C gate\n")
  h.add("  // and return the raw response envelope bytes (or empty on\n")
  h.add("  // framework error — see lastError()).\n")
  h.add("  std::vector<uint8_t> rawCall(const char* apiName,\n")
  h.add("                                const std::vector<uint8_t>& req) {\n")
  h.add("    if (ctx_ == 0) {\n")
  h.add("      lastError_ = \"library context is not initialised\";\n")
  h.add("      return {};\n")
  h.add("    }\n")
  h.add("    void* inBuf = nullptr;\n")
  h.add("    if (!req.empty()) {\n")
  h.add("      inBuf = " & p & "allocBuffer(static_cast<int32_t>(req.size()));\n")
  h.add("      if (inBuf == nullptr) {\n")
  h.add("        lastError_ = \"allocBuffer failed\";\n")
  h.add("        return {};\n")
  h.add("      }\n")
  h.add("      std::memcpy(inBuf, req.data(), req.size());\n")
  h.add("    }\n")
  h.add("    void* respBuf = nullptr;\n")
  h.add("    int32_t respLen = 0;\n")
  h.add("    const int32_t status = " & p & "call(\n")
  h.add("        ctx_, apiName, inBuf,\n")
  h.add("        static_cast<int32_t>(req.size()), &respBuf, &respLen);\n")
  h.add("    std::vector<uint8_t> out;\n")
  h.add("    if (respBuf != nullptr && respLen > 0) {\n")
  h.add("      out.assign(\n")
  h.add("          static_cast<const uint8_t*>(respBuf),\n")
  h.add("          static_cast<const uint8_t*>(respBuf) + respLen);\n")
  h.add("      " & p & "freeBuffer(respBuf);\n")
  h.add("    }\n")
  h.add("    if (status != 0) {\n")
  h.add("      if (status == -4 && !out.empty()) {\n")
  h.add("        lastError_ = std::string(\n")
  h.add("            reinterpret_cast<const char*>(out.data()), out.size());\n")
  h.add("      } else {\n")
  h.add("        lastError_ = std::string(\"framework error: \") +\n")
  h.add("                      std::to_string(status);\n")
  h.add("      }\n")
  h.add("      return {};\n")
  h.add("    }\n")
  h.add("    return out;\n")
  h.add("  }\n\n")
  h.add(" private:\n")
  h.add("  uint32_t ctx_ = 0;\n")
  h.add("  std::string lastError_;\n")
  h.add("};\n\n")

  if requestApiNames.len > 0:
    h.add("// Documented requests:\n")
    for n in requestApiNames:
      h.add("//   \"" & n & "\"\n")
    h.add("\n")
  if eventApiNames.len > 0:
    h.add("// Documented events:\n")
    for n in eventApiNames:
      h.add("//   \"" & n & "\"\n")
    h.add("\n")

  h.add("} // namespace " & libName & "\n\n")
  h.add("#endif // " & guardName & "\n")

  try:
    writeFile(headerPath, h)
  except IOError:
    error(
      "Failed to write generated CBOR C++ header '" & headerPath & "': " &
        getCurrentExceptionMsg()
    )

{.push raises: [].}
{.pop.}
