/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c -w -ferror-limit=3 -pthread --coverage -O0 -g   -I/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib -I/Users/schwarzy/dev/status/nim-brokers/test -o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_event_broker/@m..@snimbledeps@spkgs2@schronicles-0.12.2-02febb20d088120b2836d3306cfa21f434f88f65@schronicles@sdynamic_scope.nim.c.o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_event_broker/@m..@snimbledeps@spkgs2@schronicles-0.12.2-02febb20d088120b2836d3306cfa21f434f88f65@schronicles@sdynamic_scope.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_LogRecord__gO4xSBKMOv58ve1jQb8k2g tyObject_LogRecord__gO4xSBKMOv58ve1jQb8k2g;
typedef struct tyObject_BindingsFrame__V9cH2cEZpQ6RPPWMN9aBAPfQ tyObject_BindingsFrame__V9cH2cEZpQ6RPPWMN9aBAPfQ;
typedef struct tyObject_ScopeBindingBase__G29cuFBsbyQ9bnPrY2wxVTqw tyObject_ScopeBindingBase__G29cuFBsbyQ9bnPrY2wxVTqw;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct tyObject_BindingsFrame__V9cH2cEZpQ6RPPWMN9aBAPfQ {
	tyObject_BindingsFrame__V9cH2cEZpQ6RPPWMN9aBAPfQ* prev;
	tyObject_ScopeBindingBase__G29cuFBsbyQ9bnPrY2wxVTqw** bindings;
	NI bindingsCount;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef N_NIMCALL_PTR(void, tyProc__f00v2HAlbLRQ2e349cAirAA) (tyObject_LogRecord__gO4xSBKMOv58ve1jQb8k2g* x_p0, tyObject_ScopeBindingBase__G29cuFBsbyQ9bnPrY2wxVTqw* valueAddr_p1);
struct tyObject_ScopeBindingBase__G29cuFBsbyQ9bnPrY2wxVTqw {
	RootObj Sup;
	NimStringV2 name;
	tyProc__f00v2HAlbLRQ2e349cAirAA appender;
};
N_LIB_PRIVATE N_NOINLINE(tyObject_BindingsFrame__V9cH2cEZpQ6RPPWMN9aBAPfQ**, tlsSlot__test95event95broker_u1746)(void);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4709)(void);
static N_INLINE(void, popFrame)(void);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4491;
extern NIM_THREADVAR TFrame* framePtr__system_u2723;
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4491);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2723;
	framePtr__system_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2723 = (*framePtr__system_u2723).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, logAllDynamicProperties__test95event95broker_u1741)(tyObject_LogRecord__gO4xSBKMOv58ve1jQb8k2g* r_p1) {
	tyObject_BindingsFrame__V9cH2cEZpQ6RPPWMN9aBAPfQ* frame_1;
	tyObject_BindingsFrame__V9cH2cEZpQ6RPPWMN9aBAPfQ** T1_;
NIM_BOOL* nimErr_;
	nimfr_("logAllDynamicProperties", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronicles-0.12.2-02febb20d088120b2836d3306cfa21f434f88f65/chronicles/dynamic_scope.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(54, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronicles-0.12.2-02febb20d088120b2836d3306cfa21f434f88f65/chronicles/dynamic_scope.nim");	T1_ = (tyObject_BindingsFrame__V9cH2cEZpQ6RPPWMN9aBAPfQ**)0;
	T1_ = tlsSlot__test95event95broker_u1746();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	frame_1 = (*T1_);
	{
		nimln_(55);		while (1) {
			if (!!((frame_1 == ((tyObject_BindingsFrame__V9cH2cEZpQ6RPPWMN9aBAPfQ*) NIM_NIL)))) goto LA3;
			{
				NI i_1;
				NI i_2;
				i_1 = (NI)0;
				nimlf_(128, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators_1.nim");				i_2 = ((NI)0);
				{
					nimln_(129);					while (1) {
						tyObject_ScopeBindingBase__G29cuFBsbyQ9bnPrY2wxVTqw* binding_1;
						NI TM__w3SjR0Oul1Zrz9a9cnnRzdVg_2;
						if (!(i_2 < (*frame_1).bindingsCount)) goto LA6;
						nimlf_(56, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronicles-0.12.2-02febb20d088120b2836d3306cfa21f434f88f65/chronicles/dynamic_scope.nim");						i_1 = i_2;
						nimln_(57);						binding_1 = (*frame_1).bindings[i_1];
						nimln_(59);						(*binding_1).appender(r_p1, binding_1);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						nimlf_(131, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/iterators_1.nim");						if (nimAddInt(i_2, ((NI)1), &TM__w3SjR0Oul1Zrz9a9cnnRzdVg_2)) { raiseOverflow(); goto BeforeRet_;
						};
						i_2 = (NI)(TM__w3SjR0Oul1Zrz9a9cnnRzdVg_2);
					} LA6: ;
				}
			}
			nimlf_(62, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/chronicles-0.12.2-02febb20d088120b2836d3306cfa21f434f88f65/chronicles/dynamic_scope.nim");			frame_1 = (*frame_1).prev;
		} LA3: ;
	}
	}BeforeRet_: ;
	popFrame();
}
