/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c -w -ferror-limit=3 -pthread --coverage -O0 -g   -I/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib -I/Users/schwarzy/dev/status/nim-brokers/test -o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_event_broker/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.2.4@slib@spure@sos.nim.c.o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_event_broker/@m..@s..@s..@s..@s.choosenim@stoolchains@snim-2.2.4@slib@spure@sos.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <sys/param.h>
#include <mach-o/dyld.h>
#include <stdlib.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__89azkb4JUGfhEDamui6ufig tySequence__89azkb4JUGfhEDamui6ufig;
typedef struct tySequence__89azkb4JUGfhEDamui6ufig_Content tySequence__89azkb4JUGfhEDamui6ufig_Content;
typedef struct tyObject_StackTraceEntry__w39bij9cdqZCCca2z9b9aO6Teg tyObject_StackTraceEntry__w39bij9cdqZCCca2z9b9aO6Teg;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__89azkb4JUGfhEDamui6ufig {
  NI len; tySequence__89azkb4JUGfhEDamui6ufig_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__89azkb4JUGfhEDamui6ufig trace;
	Exception* up;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_StackTraceEntry__w39bij9cdqZCCca2z9b9aO6Teg {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__89azkb4JUGfhEDamui6ufig_Content { NI cap; tyObject_StackTraceEntry__w39bij9cdqZCCca2z9b9aO6Teg data[SEQ_DECL_SIZE]; };
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2696)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosexpandFilename)(NimStringV2 filename_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__stdZoserrors_u119)(NI32 errorCode_p0, NimStringV2 additionalInfo_p1);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__stdZoserrors_u122)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4709)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___stdZtypedthreads_u223)(Exception** dest_p0, Exception* src_p1, NIM_BOOL cyclic_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nospquoteShellPosix)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, allCharsInSet__pureZstrutils_u1568)(NimStringV2 s_p0, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw theSet_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2690)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuReplaceStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NimStringV2 by_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_3 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_2};
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_4 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_2};
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_5 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_2};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_6 = { 2 | NIM_STRLIT_FLAG, "\'\'" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_7 = {2, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_6};
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__yu6cxgKBBXbNsTkT9cyMd4g_8 = {
0x00, 0x00, 0x00, 0x00, 0x20, 0xe8, 0xff, 0x27,
0xff, 0xff, 0xff, 0x87, 0xfe, 0xff, 0xff, 0x07,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_9 = { 1 | NIM_STRLIT_FLAG, "\'" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_10 = {1, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_9};
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_12 = {1, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_9};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_13 = { 5 | NIM_STRLIT_FLAG, "\'\"\'\"\'" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_14 = {5, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_13};
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_15 = {1, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_9};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4491;
extern NIM_THREADVAR TFrame* framePtr__system_u2723;
extern NIM_THREADVAR Exception* currException__system_u4136;
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4491);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2723;
	framePtr__system_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2723 = (*framePtr__system_u2723).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosexpandFilename)(NimStringV2 filename_p0) {
	NimStringV2 result;
	NCSTRING r_1;
NIM_BOOL* nimErr_;
	nimfr_("expandFilename", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/os.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(394, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/os.nim");	result = TM__yu6cxgKBBXbNsTkT9cyMd4g_4;
	nimln_(419);	r_1 = realpath(nimToCStringConv(filename_p0), ((NCSTRING) NIM_NIL));
	nimln_(420);	{
		NI32 T5_;
		if (!(r_1 == 0)) goto LA3_;
		nimln_(421);		T5_ = (NI32)0;
		T5_ = osLastError__stdZoserrors_u122();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_u119(T5_, filename_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		NimStringV2 T7_;
		nimlf_(1694, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");		nimlf_(423, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/os.nim");		T7_.len = 0; T7_.p = NIM_NIL;
		T7_ = cstrToNimstr(r_1);
		nimlf_(1694, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");		eqsink___system_u2696((&result), T7_);
		nimlf_(424, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/os.nim");		free(((void*) (r_1)));
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
	nimfr_("=destroy", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");
	popFrame();
}
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("isObjDisplayCheck", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/arc.nim");
	nimlf_(266, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system/arc.nim");	T1_ = (NIM_BOOL)0;
	T1_ = (targetDepth_p1 <= (*source_p0).depth);
	if (!(T1_)) goto LA2_;
	T1_ = ((*source_p0).display[targetDepth_p1] == token_p2);
LA2_: ;
	result = T1_;
	popFrame();
	return result;
}
static N_INLINE(Exception*, nimBorrowCurrentException)(void) {
	Exception* result;
	nimfr_("nimBorrowCurrentException", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");
	nimlf_(2301, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");	result = currException__system_u4136;
	popFrame();
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___stdZtypedthreads_u223(&currException__system_u4136, (*currException__system_u4136).up, NIM_FALSE);
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetAppFilename)(void) {
	NimStringV2 result;
	unsigned int size_1;
NIM_BOOL* nimErr_;
	nimfr_("getAppFilename", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(678, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/os.nim");	size_1 = ((NI)0);
	nimln_(679);	_NSGetExecutablePath(((NCSTRING) NIM_NIL), (&size_1));
	nimln_(680);	if ((((NI) (size_1))) < ((NI)0) || (((NI) (size_1))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(((NI) (size_1)), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((((NI) (size_1))));
	nimln_(681);	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = _NSGetExecutablePath(nimToCStringConv(result), (&size_1));
		if (!T3_) goto LA4_;
		nimlf_(1694, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");		eqsink___system_u2696((&result), TM__yu6cxgKBBXbNsTkT9cyMd4g_3);
	}
LA4_: ;
	nimlf_(683, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/os.nim");	{
		NimStringV2 T11_;
		if (!(((NI)0) < result.len)) goto LA8_;
		nimlf_(1694, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");		nimlf_(685, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/os.nim");		T11_.len = 0; T11_.p = NIM_NIL;
		T11_ = nosexpandFilename(result);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T11_); goto LA10_;}
		nimlf_(1694, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");		eqsink___system_u2696((&result), T11_);
		if (NIM_UNLIKELY(*nimErr_)) {
			LA10_:;
			if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 3, 685156096)) {
				*nimErr_ = NIM_FALSE;
				eqsink___system_u2696((&result), TM__yu6cxgKBBXbNsTkT9cyMd4g_5);
				popCurrentException();
				LA13_:;
			}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA8_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__yu6cxgKBBXbNsTkT9cyMd4g_11;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1731(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__yu6cxgKBBXbNsTkT9cyMd4g_11)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_11);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nospquoteShellPosix)(NimStringV2 s_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("quoteShellPosix", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(177, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/os.nim");	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		nimln_(178);		result = TM__yu6cxgKBBXbNsTkT9cyMd4g_7;
	}
	goto LA1_;
LA3_: ;
	{
		NIM_BOOL T6_;
		nimln_(179);		T6_ = (NIM_BOOL)0;
		T6_ = allCharsInSet__pureZstrutils_u1568(s_p0, TM__yu6cxgKBBXbNsTkT9cyMd4g_8);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T6_) goto LA7_;
		nimlf_(1694, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");		eqcopy___system_u2690((&result), s_p0);
	}
	goto LA1_;
LA7_: ;
	{
		NimStringV2 colontmpD_;
		NimStringV2 T10_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		nimlf_(182, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/os.nim");		T10_.len = 0; T10_.p = NIM_NIL;
		colontmpD_ = nsuReplaceStr(s_p0, TM__yu6cxgKBBXbNsTkT9cyMd4g_12, TM__yu6cxgKBBXbNsTkT9cyMd4g_14);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T10_ = rawNewString(colontmpD_.len + 2);
appendString((&T10_), TM__yu6cxgKBBXbNsTkT9cyMd4g_10);
appendString((&T10_), colontmpD_);
appendString((&T10_), TM__yu6cxgKBBXbNsTkT9cyMd4g_15);
		result = T10_;
		nimlf_(394, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nospquoteShell)(NimStringV2 s_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("quoteShell", "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(193, "/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib/pure/os.nim");	result = nospquoteShellPosix(s_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
