/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c -w -ferror-limit=3 -pthread --coverage -O0 -g   -I/Users/schwarzy/.choosenim/toolchains/nim-2.2.4/lib -I/Users/schwarzy/dev/status/nim-brokers/test -o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_api_event_teardown_isolation/@m..@snimbledeps@spkgs2@sserialization-0.5.2-fa35c1bb76a0a02a2379fe86eaae0957c7527cb8@sserialization.nim.c.o /Users/schwarzy/dev/status/nim-brokers/.cov-cache/c/test_api_event_teardown_isolation/@m..@snimbledeps@spkgs2@sserialization-0.5.2-fa35c1bb76a0a02a2379fe86eaae0957c7527cb8@sserialization.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
N_LIB_PRIVATE N_NIMCALL(void, read__test95api95event95teardown95isolation_u5608)(tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw* r_p0, NimStringV2* value_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4709)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, read__test95api95event95teardown95isolation_u26090)(tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw* r_p0, NI32* value_p1);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4491;
extern NIM_THREADVAR TFrame* framePtr__system_u2723;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4491);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2723 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2723).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2723;
	framePtr__system_u2723 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4709();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2723 = (*framePtr__system_u2723).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readValue__test95api95event95teardown95isolation_u5592)(tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw* reader_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("readValue", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/serialization-0.5.2-fa35c1bb76a0a02a2379fe86eaae0957c7527cb8/serialization.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(33, "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/serialization-0.5.2-fa35c1bb76a0a02a2379fe86eaae0957c7527cb8/serialization.nim");	read__test95api95event95teardown95isolation_u5608(reader_p0, (&result));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI32, readValue__test95api95event95teardown95isolation_u26074)(tyObject_CborReader__Xr0LJ4eLPeuNkcxUSS5ZOw* reader_p0) {
	NI32 result;
NIM_BOOL* nimErr_;
	nimfr_("readValue", "/Users/schwarzy/dev/status/nim-brokers/nimbledeps/pkgs2/serialization-0.5.2-fa35c1bb76a0a02a2379fe86eaae0957c7527cb8/serialization.nim");
{nimErr_ = nimErrorFlag();
	result = (NI32)0;
	nimln_(33);	read__test95api95event95teardown95isolation_u26090(reader_p0, (&result));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
